/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.64
 * Generated at: 2565-08-03 06:56:15 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.page;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(5);
    _jspx_dependants.put("/WEB-INF/tld/struts-bean.tld", Long.valueOf(1659502853028L));
    _jspx_dependants.put("/page/inc_header_script.jsp", Long.valueOf(1659502853038L));
    _jspx_dependants.put("/WEB-INF/tld/struts-html.tld", Long.valueOf(1659502853029L));
    _jspx_dependants.put("/WEB-INF/tld/c.tld", Long.valueOf(1659502853021L));
    _jspx_dependants.put("/WEB-INF/tld/struts-logic.tld", Long.valueOf(1659502853030L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fhtml_005fform_0026_005fstyleId_005faction;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fhtml_005fhidden_0026_005fproperty_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fhtml_005ftext_0026_005fstyleId_005fstyleClass_005fproperty_005fplaceHolder_005fonkeypress_005fmaxlength_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fhtml_005fpassword_0026_005fstyleId_005fstyleClass_005fproperty_005fplaceHolder_005fonkeypress_005fmaxlength_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fbean_005fdefine_0026_005fvalue_005fid_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005flogic_005fequal_0026_005fvalue_005fname;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fhtml_005fform_0026_005fstyleId_005faction = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fhtml_005fhidden_0026_005fproperty_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fhtml_005ftext_0026_005fstyleId_005fstyleClass_005fproperty_005fplaceHolder_005fonkeypress_005fmaxlength_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fhtml_005fpassword_0026_005fstyleId_005fstyleClass_005fproperty_005fplaceHolder_005fonkeypress_005fmaxlength_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fbean_005fdefine_0026_005fvalue_005fid_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005flogic_005fequal_0026_005fvalue_005fname = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fhtml_005fform_0026_005fstyleId_005faction.release();
    _005fjspx_005ftagPool_005fhtml_005fhidden_0026_005fproperty_005fnobody.release();
    _005fjspx_005ftagPool_005fhtml_005ftext_0026_005fstyleId_005fstyleClass_005fproperty_005fplaceHolder_005fonkeypress_005fmaxlength_005fnobody.release();
    _005fjspx_005ftagPool_005fhtml_005fpassword_0026_005fstyleId_005fstyleClass_005fproperty_005fplaceHolder_005fonkeypress_005fmaxlength_005fnobody.release();
    _005fjspx_005ftagPool_005fbean_005fdefine_0026_005fvalue_005fid_005fnobody.release();
    _005fjspx_005ftagPool_005flogic_005fequal_0026_005fvalue_005fname.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("	<!DOCTYPE html>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("	<meta charset=\"utf-8\">\r\n");
      out.write("	<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("	<meta name=\"description\" content=\"\">\r\n");
      out.write("	<meta name=\"author\" content=\"\">\r\n");
      out.write("	<meta name=\"keyword\" content=\"\">\r\n");
      out.write("	\r\n");
      out.write("	<title>Service Tracking</title>\r\n");
      out.write("\r\n");
      out.write("	\r\n");
      out.write("	 \r\n");
      out.write("	 <script src=\"//cdn.jsdelivr.net/npm/sweetalert2@11\"></script>\r\n");
      out.write("	 <!-- Font Awesome -->\r\n");
      out.write("	 <linkhref=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css\" rel=\"stylesheet\"/>\r\n");
      out.write("	 <!-- Google Fonts -->\r\n");
      out.write("	 <linkhref=\"https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap\" rel=\"stylesheet\"/>\r\n");
      out.write("	 <!-- MDB -->\r\n");
      out.write("	 <linkhref=\"https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/4.2.0/mdb.min.css\"rel=\"stylesheet\"/>\r\n");
      out.write("	 <!-- MDB -->\r\n");
      out.write("	 <scripttype=\"text/javascript\" src=\"https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/4.2.0/mdb.min.js\"></script>\r\n");
      out.write("	<!-- font -->\r\n");
      out.write("	<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/ui/fonts/webfont.css\" rel=\"stylesheet\" />\r\n");
      out.write("	<!-- font icon -->\r\n");
      out.write("	<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/ui/css/elegant-icons-style.css\" rel=\"stylesheet\" />\r\n");
      out.write("	<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/ui/css/font-awesome.min.css\" rel=\"stylesheet\" />\r\n");
      out.write("	<!-- datatable -->\r\n");
      out.write("	<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/ui/css/dataTables.bootstrap.css\" rel=\"stylesheet\"/>\r\n");
      out.write("	<!-- Custom styles -->\r\n");
      out.write("	<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/ui/css/style-responsive.css\" rel=\"stylesheet\" />\r\n");
      out.write("	<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/ui/css/jquery-ui-10.12.1.css\" rel=\"stylesheet\"/>\r\n");
      out.write("	<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/ui/css/style-button.css\" rel=\"stylesheet\"/>\r\n");
      out.write("	<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/ui/css/bootstrap-select.css\" rel=\"stylesheet\"/>\r\n");
      out.write("	<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/ui/css/materialize-color.css\" rel=\"stylesheet\"/>\r\n");
      out.write("	<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/ui/sweetalert/css/sweetalert.css\" rel=\"stylesheet\"/>\r\n");
      out.write("\r\n");
      out.write("	<!-- javascripts -->\r\n");
      out.write("	<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/ui/js/jquery-1.12.4.js\"></script>\r\n");
      out.write("	<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/ui/js/jquery-ui-1.10.4.min.js\"></script>\r\n");
      out.write("	<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/ui/js/jquery-1.8.3.min.js\"></script>\r\n");
      out.write("	<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/ui/js/jquery-ui-1.9.2.custom.min.js\" type=\"text/javascript\"></script>\r\n");
      out.write("	<!-- for set format thai -->\r\n");
      out.write("	<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/ui/js/jquery.ui.1.8.10.offset.datepicker.min.js\" type=\"text/javascript\"></script>\r\n");
      out.write("	\r\n");
      out.write("	<!-- bootstrap -->\r\n");
      out.write("	<!-- nice scroll -->\r\n");
      out.write("	<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/ui/js/jquery.scrollTo.min.js\"></script>\r\n");
      out.write("	<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/ui/js/jquery.nicescroll.js\" type=\"text/javascript\"></script>\r\n");
      out.write("	<!-- custom select -->\r\n");
      out.write("	<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/ui/js/jquery.customSelect.min.js\"></script>\r\n");
      out.write("	<link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css\" rel=\"stylesheet\" integrity=\"sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor\" crossorigin=\"anonymous\">\r\n");
      out.write("	<!--custome script for all page-->\r\n");
      out.write("	<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/ui/js/scripts.js\"></script>\r\n");
      out.write("	\r\n");
      out.write("	<!-- custom script for this page-->\r\n");
      out.write("	<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/ui/js/jquery.autosize.min.js\"></script>\r\n");
      out.write("	<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/ui/js/jquery.placeholder.min.js\"></script>\r\n");
      out.write("	<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/ui/js/jquery.slimscroll.min.js\"></script>\r\n");
      out.write("	<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/ui/js/bootbox.js\"></script>\r\n");
      out.write("	<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/ui/js/bootstrap-select.js\"></script>\r\n");
      out.write("	<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/ui/js/bootstrap-typeahead.js\"></script>\r\n");
      out.write("	<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js\" integrity=\"sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("	<!-- datatable -->\r\n");
      out.write("	<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/ui/js/jquery.dataTables.js\" type=\"text/javascript\"></script>\r\n");
      out.write("	<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/ui/js/dataTables.bootstrap.js\" type=\"text/javascript\"></script>\r\n");
      out.write("	\r\n");
      out.write("	<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/ui/js/jquery.validate.min.js\" type=\"text/javascript\"></script>\r\n");
      out.write("	<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/ui/js/quotwaiting-forquot-modal-dialog.js\" type=\"text/javascript\"></script>\r\n");
      out.write("	<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/ui/sweetalert/js/sweetalert.min.js\" type=\"text/javascript\"></script>\r\n");
      out.write("	\r\n");
      out.write("	<script type=\"text/javascript\">\r\n");
      out.write(" 		$(document).ready(function () {\r\n");
      out.write(" 			\r\n");
      out.write(" 			$(\"#msgSuccess\").delay(800).fadeOut(1000);\r\n");
      out.write(" 			$(\"#msgWarning\").delay(800).fadeOut(1000);\r\n");
      out.write(" 			\r\n");
      out.write("			try {\r\n");
      out.write("				var variables = {};\r\n");
      out.write("		      	variables = {\r\n");
      out.write("						\"sProcessing\": \"กำลังดำเนินการ...\",\r\n");
      out.write("						\"sLengthMenu\": \"แสดง _MENU_  แถว\",\r\n");
      out.write("						\"sZeroRecords\": \"ไม่พบข้อมูล\",\r\n");
      out.write("						\"sInfo\": \"แสดง _START_ ถึง _END_ จาก _TOTAL_ แถว\",\r\n");
      out.write("						\"sInfoEmpty\": \"แสดง 0 ถึง 0 จาก 0 แถว\",\r\n");
      out.write("						\"sInfoFiltered\": \"(กรองข้อมูล _MAX_ ทุกแถว)\",\r\n");
      out.write("						\"sInfoPostFix\": \"\",\r\n");
      out.write("						\"sSearch\": \"ค้นหา: \",\r\n");
      out.write("						\"sUrl\": \"\",\r\n");
      out.write("						\"oPaginate\": {\r\n");
      out.write("						    \"sFirst\": \"เริ่มต้น\",\r\n");
      out.write("						    \"sPrevious\": \"ก่อนหน้า\",\r\n");
      out.write("						    \"sNext\": \"ถัดไป\",\r\n");
      out.write("						    \"sLast\": \"สุดท้าย\"\r\n");
      out.write("						}\r\n");
      out.write("				};\r\n");
      out.write("			\r\n");
      out.write("				var options = { \"aoColumnDefs\": [{ bSortable: false, aTargets: ['no-sort'] }],\"oLanguage\": variables};\r\n");
      out.write("				var optionsHundred = { \"aoColumnDefs\": [{ bSortable: false, aTargets: ['no-sort'] }],\"iDisplayLength\": 100,\"oLanguage\": variables};\r\n");
      out.write("				var optionsFive = { \"aoColumnDefs\": [{ bSortable: false, aTargets: ['no-sort'] }],\"iDisplayLength\": 5,\"oLanguage\": variables};\r\n");
      out.write("			\r\n");
      out.write("				$(\".grid-default\").dataTable(options);\r\n");
      out.write("				$(\".grid-hundred\").dataTable(optionsHundred);\r\n");
      out.write("				$(\".grid-five\").dataTable(optionsFive);\r\n");
      out.write("			} catch (e) {\r\n");
      out.write("			}\r\n");
      out.write("			\r\n");
      out.write("			$.datepicker.isBuddhist ={\r\n");
      out.write("				isBuddhist: true,\r\n");
      out.write("				changeMonth: true,\r\n");
      out.write("		        changeYear: true,\r\n");
      out.write("		        buttonImageOnly: false,\r\n");
      out.write("		        dateFormat: 'dd/mm/yy',\r\n");
      out.write("		        dayNames: ['อาทิตย์', 'จันทร์', 'อังคาร', 'พุธ', 'พฤหัสบดี', 'ศุกร์', 'เสาร์'],\r\n");
      out.write("		        dayNamesMin: ['อา', 'จ', 'อ', 'พ', 'พฤ', 'ศ', 'ส'],\r\n");
      out.write("		        monthNames: ['มกราคม', 'กุมภาพันธ์', 'มีนาคม', 'เมษายน', 'พฤษภาคม', 'มิถุนายน', 'กรกฎาคม', 'สิงหาคม', 'กันยายน', 'ตุลาคม', 'พฤศจิกายน', 'ธันวาคม'],\r\n");
      out.write("		        //monthNamesShort: ['มกราคม', 'กุมภาพันธ์', 'มีนาคม', 'เมษายน', 'พฤษภาคม', 'มิถุนายน', 'กรกฎาคม', 'สิงหาคม', 'กันยายน', 'ตุลาคม', 'พฤศจิกายน', 'ธันวาคม'],\r\n");
      out.write("		        monthNamesShort: ['ม.ค.', 'ก.พ.', 'มี.ค.', 'เม.ย.', 'พ.ค.', 'มิ.ย.', 'ก.ค.', 'ส.ค.', 'ก.ย.', 'ต.ค.', 'พ.ย.', 'ธ.ค.'],\r\n");
      out.write("		        constrainInput: true,	\r\n");
      out.write("		        prevText: 'ก่อนหน้า',\r\n");
      out.write("		        nextText: 'ถัดไป',\r\n");
      out.write("		        yearRange: '-200:+10',\r\n");
      out.write("		        buttonText: 'เลือก'\r\n");
      out.write("		    };\r\n");
      out.write("			\r\n");
      out.write("			$.datepicker.twomonth ={\r\n");
      out.write("				isBuddhist: true,\r\n");
      out.write("				changeMonth: false,\r\n");
      out.write("		        changeYear: false,\r\n");
      out.write("		        buttonImageOnly: false,\r\n");
      out.write("		        dateFormat: 'dd/mm/yy',\r\n");
      out.write("		        dayNames: ['อาทิตย์', 'จันทร์', 'อังคาร', 'พุธ', 'พฤหัสบดี', 'ศุกร์', 'เสาร์'],\r\n");
      out.write("		        dayNamesMin: ['อา', 'จ', 'อ', 'พ', 'พฤ', 'ศ', 'ส'],\r\n");
      out.write("		        monthNames: ['มกราคม', 'กุมภาพันธ์', 'มีนาคม', 'เมษายน', 'พฤษภาคม', 'มิถุนายน', 'กรกฎาคม', 'สิงหาคม', 'กันยายน', 'ตุลาคม', 'พฤศจิกายน', 'ธันวาคม'],\r\n");
      out.write("		        //monthNamesShort: ['มกราคม', 'กุมภาพันธ์', 'มีนาคม', 'เมษายน', 'พฤษภาคม', 'มิถุนายน', 'กรกฎาคม', 'สิงหาคม', 'กันยายน', 'ตุลาคม', 'พฤศจิกายน', 'ธันวาคม'],\r\n");
      out.write("		        monthNamesShort: ['ม.ค.', 'ก.พ.', 'มี.ค.', 'เม.ย.', 'พ.ค.', 'มิ.ย.', 'ก.ค.', 'ส.ค.', 'ก.ย.', 'ต.ค.', 'พ.ย.', 'ธ.ค.'],\r\n");
      out.write("		        constrainInput: true,	\r\n");
      out.write("		        prevText: 'ก่อนหน้า',\r\n");
      out.write("		        nextText: 'ถัดไป',\r\n");
      out.write("		        yearRange: '-200:+10',\r\n");
      out.write("		        buttonText: 'เลือก',\r\n");
      out.write("		        numberOfMonths: 2\r\n");
      out.write("		    };\r\n");
      out.write(" 			$('.i-calendar').datepicker($.datepicker.isBuddhist);\r\n");
      out.write("			$('.t-calendar').datepicker($.datepicker.twomonth);\r\n");
      out.write("			\r\n");
      out.write("			$( \"#dateStart\" ).datepicker({\r\n");
      out.write("		    	isBuddhist: true,\r\n");
      out.write("				changeMonth: true,\r\n");
      out.write("		        changeYear: true,\r\n");
      out.write("		        buttonImageOnly: false,\r\n");
      out.write("		        dateFormat: 'dd/mm/yy',\r\n");
      out.write("		        dayNames: ['อาทิตย์', 'จันทร์', 'อังคาร', 'พุธ', 'พฤหัสบดี', 'ศุกร์', 'เสาร์'],\r\n");
      out.write("		        dayNamesMin: ['อา', 'จ', 'อ', 'พ', 'พฤ', 'ศ', 'ส'],\r\n");
      out.write("		        monthNames: ['มกราคม', 'กุมภาพันธ์', 'มีนาคม', 'เมษายน', 'พฤษภาคม', 'มิถุนายน', 'กรกฎาคม', 'สิงหาคม', 'กันยายน', 'ตุลาคม', 'พฤศจิกายน', 'ธันวาคม'],\r\n");
      out.write("		        monthNamesShort: ['ม.ค.', 'ก.พ.', 'มี.ค.', 'เม.ย.', 'พ.ค.', 'มิ.ย.', 'ก.ค.', 'ส.ค.', 'ก.ย.', 'ต.ค.', 'พ.ย.', 'ธ.ค.'],\r\n");
      out.write("		        constrainInput: true,	\r\n");
      out.write("		        prevText: 'ก่อนหน้า',\r\n");
      out.write("		        nextText: 'ถัดไป',\r\n");
      out.write("		        yearRange: '-200:+5',\r\n");
      out.write("		        buttonText: 'เลือก',\r\n");
      out.write("		        numberOfMonths: 2,\r\n");
      out.write("		      	onClose: function( selectedDate ) {\r\n");
      out.write("		        	$( \"#dateStop\" ).datepicker( \"option\", \"minDate\", selectedDate );\r\n");
      out.write("		      	}\r\n");
      out.write("		    });\r\n");
      out.write("			\r\n");
      out.write("		    $( \"#dateStop\" ).datepicker({\r\n");
      out.write("		    	isBuddhist: true,\r\n");
      out.write("				changeMonth: true,\r\n");
      out.write("		        changeYear: true,\r\n");
      out.write("		        buttonImageOnly: false,\r\n");
      out.write("		        dateFormat: 'dd/mm/yy',\r\n");
      out.write("		        dayNames: ['อาทิตย์', 'จันทร์', 'อังคาร', 'พุธ', 'พฤหัสบดี', 'ศุกร์', 'เสาร์'],\r\n");
      out.write("		        dayNamesMin: ['อา', 'จ', 'อ', 'พ', 'พฤ', 'ศ', 'ส'],\r\n");
      out.write("		        monthNames: ['มกราคม', 'กุมภาพันธ์', 'มีนาคม', 'เมษายน', 'พฤษภาคม', 'มิถุนายน', 'กรกฎาคม', 'สิงหาคม', 'กันยายน', 'ตุลาคม', 'พฤศจิกายน', 'ธันวาคม'],\r\n");
      out.write("		        monthNamesShort: ['ม.ค.', 'ก.พ.', 'มี.ค.', 'เม.ย.', 'พ.ค.', 'มิ.ย.', 'ก.ค.', 'ส.ค.', 'ก.ย.', 'ต.ค.', 'พ.ย.', 'ธ.ค.'],\r\n");
      out.write("		        constrainInput: true,	\r\n");
      out.write("		        prevText: 'ก่อนหน้า',\r\n");
      out.write("		        nextText: 'ถัดไป',\r\n");
      out.write("		        yearRange: '-200:+5',\r\n");
      out.write("		        buttonText: 'เลือก',\r\n");
      out.write("		        numberOfMonths: 2,\r\n");
      out.write("		      onClose: function( selectedDate ) {\r\n");
      out.write("		        $( \"#dateStart\" ).datepicker( \"option\", \"maxDate\", selectedDate );\r\n");
      out.write("		      }\r\n");
      out.write("		    });\r\n");
      out.write("        });\r\n");
      out.write(" 		\r\n");
      out.write(" 		function showDialogContent(url,title,size){\r\n");
      out.write(" 			\r\n");
      out.write(" 			$.post(url,{}, \r\n");
      out.write(" 				function(results) {	 \r\n");
      out.write(" 				var textAndPic = $('<div id=\"dialogs\">'+results+'</div>');	\r\n");
      out.write(" 				var bootdialog = bootbox.dialog({\r\n");
      out.write(" 				    title: title,\r\n");
      out.write(" 				    message: textAndPic,\r\n");
      out.write(" 				    className: size\r\n");
      out.write(" 				});\r\n");
      out.write(" 				\r\n");
      out.write(" 				$('.selectpicker').selectpicker('refresh');\r\n");
      out.write(" 				\r\n");
      out.write(" 				/* dialog.init(function(){\r\n");
      out.write(" 				    setTimeout(function(){\r\n");
      out.write(" 				        dialog.find('.bootbox-body').html(textAndPic);\r\n");
      out.write(" 				    }, 3000);\r\n");
      out.write(" 				}); */	\r\n");
      out.write(" 				\r\n");
      out.write(" 			});	\r\n");
      out.write(" 		}\r\n");
      out.write(" 		\r\n");
      out.write(" 		function showDialog(url,t,w,h){    		\r\n");
      out.write(" 	        $('#dialogs').dialog({\r\n");
      out.write(" 	        	modal: true,\r\n");
      out.write(" 	        	show: {\r\n");
      out.write(" 					effect: \"fade\",\r\n");
      out.write(" 					duration: 200\r\n");
      out.write(" 				},\r\n");
      out.write(" 	        	title: t,\r\n");
      out.write(" 	            width: w,\r\n");
      out.write(" 	            height: h,\r\n");
      out.write(" 	            closeOnEscape: true,\r\n");
      out.write(" 	            open: function () {\r\n");
      out.write(" 	                $.post(url,{}, \r\n");
      out.write(" 	              	function(results) {	 \r\n");
      out.write(" 	              		$('#dialogs').html(results);	\r\n");
      out.write(" 	              		$('#dialogs').siblings('.ui-dialog-titlebar').find('button').blur(); \r\n");
      out.write(" 	              		\r\n");
      out.write(" 	             	});\r\n");
      out.write(" 	            }\r\n");
      out.write(" 	        });\r\n");
      out.write(" 		}\r\n");
      out.write(" 		\r\n");
      out.write(" 		function showLoadingSwal() {\r\n");
      out.write(" 			swal({\r\n");
      out.write("      		  	title: \"กำลังโหลดข้อมูล...\",\r\n");
      out.write("      		  	imageUrl: '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/ui/sweetalert/image/entering-comment-loader.gif',\r\n");
      out.write("      			closeOnConfirm: false,\r\n");
      out.write("      			showCancelButton: false,\r\n");
      out.write("      			showConfirmButton: false,\r\n");
      out.write("      		});\r\n");
      out.write(" 		}\r\n");
      out.write(" 		function success() {\r\n");
      out.write(" 	        swal.close()\r\n");
      out.write(" 	    }\r\n");
      out.write("	</script>\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("	.popup-dialog .modal-dialog { width: 700px; }\r\n");
      out.write("	.popuplg-dialog .modal-dialog { width: 1000px; }\r\n");
      out.write("</style>\r\n");
      out.write("</head>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<script language=\"javascript\" type=\"text/javascript\">\r\n");
      out.write("	$(document).ready(function() {\r\n");
      out.write("		\r\n");
      out.write("		jQuery.ajaxSetup({\r\n");
      out.write("			  beforeSend: function() {\r\n");
      out.write("			     $('#loader').show();\r\n");
      out.write("			  },\r\n");
      out.write("			  complete: function(){\r\n");
      out.write("			     $('#loader').hide();\r\n");
      out.write("			  },\r\n");
      out.write("			  success: function() {}\r\n");
      out.write("		});\r\n");
      out.write("\r\n");
      out.write("		$(\"#eduForm\").validate({\r\n");
      out.write("			rules: {\r\n");
      out.write("				un: \"required\",\r\n");
      out.write("				pw: \"required\",\r\n");
      out.write("			},\r\n");
      out.write("			highlight: function(element) {\r\n");
      out.write("	            $(element).closest('.form-control').addClass('has-error-input');\r\n");
      out.write("	        },\r\n");
      out.write("	        unhighlight: function(element) {\r\n");
      out.write("	            $(element).closest('.form-control').removeClass('has-error-input');\r\n");
      out.write("	        },\r\n");
      out.write("	        errorElement: 'span',\r\n");
      out.write("	        errorClass: 'has-error-block',\r\n");
      out.write("	        errorPlacement: function(error, element) {},\r\n");
      out.write("	      	submitHandler: function(form) {\r\n");
      out.write("	      		document.forms[0].mode.value = 'login';\r\n");
      out.write("		   	 	document.forms[0].submit();\r\n");
      out.write("			}\r\n");
      out.write("		});\r\n");
      out.write("		\r\n");
      out.write("		$('#un').focus();\r\n");
      out.write("	});\r\n");
      out.write("  	\r\n");
      out.write("	function submitEnter() {\r\n");
      out.write("		if (checkKeyEnter() == true) submitFormLogin();\r\n");
      out.write("	}\r\n");
      out.write("	function checkKeyEnter(){\r\n");
      out.write("	   if(event.keyCode==13) return true;\r\n");
      out.write("	}\r\n");
      out.write("	function submitFormLogin() {\r\n");
      out.write("		$(\"#eduForm\").submit();\r\n");
      out.write("		document.forms[0].action = 'login.htm?mode=login';\r\n");
      out.write("   	 	document.forms[0].submit();\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	function showDialogLogin(url,title,size){\r\n");
      out.write("		$.post(url,{}, \r\n");
      out.write("			function(results) {\r\n");
      out.write("				var $textAndPic = $('<div id=\"dialogs\"></div>');\r\n");
      out.write("				$textAndPic.append(results);\r\n");
      out.write("				BootstrapDialog.show({\r\n");
      out.write("					type: BootstrapDialog.TYPE_DEFAULT,\r\n");
      out.write("					title: title,\r\n");
      out.write("		          	cssClass : size,\r\n");
      out.write("		          	message: $textAndPic,\r\n");
      out.write("		          	draggable: true	 ,\r\n");
      out.write("		          	buttons:[{\r\n");
      out.write("		                 label: 'ปิดหน้าจอ',\r\n");
      out.write("		                 action: function(dialogItself){\r\n");
      out.write("		                     dialogItself.close();\r\n");
      out.write("		                 }\r\n");
      out.write("		            }]\r\n");
      out.write("		       });				 \r\n");
      out.write("		});	\r\n");
      out.write("	}\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("	html,body{\r\n");
      out.write("	    position: relative;\r\n");
      out.write("	    height: 100%;\r\n");
      out.write("	}\r\n");
      out.write("	body {\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	position: center;\r\n");
      out.write("	width: 100%;\r\n");
      out.write("	height: 100%;\r\n");
      out.write("	left: 0px;\r\n");
      out.write("	top: 0px;\r\n");
      out.write("	\r\n");
      out.write("	background: linear-gradient(136.16deg, #042153 5.45%, #1DA1B0 60.18%);\r\n");
      out.write("	\r\n");
      out.write("	}\r\n");
      out.write("	#main-login {\r\n");
      out.write("		position: absolute;\r\n");
      out.write("		min-width: 400px;\r\n");
      out.write("		min-height: 350px; /* 450px */\r\n");
      out.write("		width: 400px;\r\n");
      out.write("		height: 350px; /* 450px */\r\n");
      out.write("	   	right: 200px ;\r\n");
      out.write("	   	top:240px;\r\n");
      out.write("	    background-color: #ffffff;\r\n");
      out.write("	    padding: 5px 0px 0px 0px;\r\n");
      out.write("	    -webkit-border-radius: 8px;\r\n");
      out.write("		-moz-border-radius: 8px;\r\n");
      out.write("		-ms-user-select: none;\r\n");
      out.write("		border-radius: 8px;\r\n");
      out.write("		box-shadow: 0 0 10px rgba(0, 0, 0, 0.3) !important;	\r\n");
      out.write("			margin: 0 auto;\r\n");
      out.write("		\r\n");
      out.write("	}\r\n");
      out.write("	#login-left {\r\n");
      out.write("		background-image: url(\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/vec/ui/img/bg/bg_login_left.png\");\r\n");
      out.write("		background-repeat: no-repeat;\r\n");
      out.write("		background-position: bottom left;\r\n");
      out.write("		background-color: #f57c00;\r\n");
      out.write("		height: 100%;\r\n");
      out.write("		-webkit-border-radius: 8px 0px 0px 8px;\r\n");
      out.write("		-moz-border-radius: 8px 0px 0px 8px;\r\n");
      out.write("		-ms-user-select: none;\r\n");
      out.write("		border-radius: 8px 0px 0px 8px;\r\n");
      out.write("		font-family: pridien;\r\n");
      out.write("		color: #ffffff;\r\n");
      out.write("	}\r\n");
      out.write("	.login-title {\r\n");
      out.write("		color: #000; /* #ff6e7b */\r\n");
      out.write("		font-family: pridi, pridien;\r\n");
      out.write("		font-size: 1.8em;\r\n");
      out.write("		font-weight: bold;\r\n");
      out.write("	}\r\n");
      out.write("	.login-box {\r\n");
      out.write("		margin-top: 25px;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	.login-box a {\r\n");
      out.write("		color: #999;\r\n");
      out.write("		text-decoration: underline;\r\n");
      out.write("	}\r\n");
      out.write("	.login-box a:hover, .login-box a:focus {\r\n");
      out.write("		color: '#f57c00';\r\n");
      out.write("		text-decoration: underline;\r\n");
      out.write("	}\r\n");
      out.write("	.logo{\r\n");
      out.write("	  	padding: 300px 0px 50px 20px;\r\n");
      out.write("	  	-webkit-border-radius: 8px;\r\n");
      out.write("		-moz-border-radius: 8px;\r\n");
      out.write("		color: white; /* #ff6e7b */\r\n");
      out.write("		font-family: pridi, pridien;\r\n");
      out.write("		font-size: 1.8em;\r\n");
      out.write("		font-weight: bold;\r\n");
      out.write("		}\r\n");
      out.write("	\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      //  html:form
      org.apache.struts.taglib.html.FormTag _jspx_th_html_005fform_005f0 = (org.apache.struts.taglib.html.FormTag) _005fjspx_005ftagPool_005fhtml_005fform_0026_005fstyleId_005faction.get(org.apache.struts.taglib.html.FormTag.class);
      boolean _jspx_th_html_005fform_005f0_reused = false;
      try {
        _jspx_th_html_005fform_005f0.setPageContext(_jspx_page_context);
        _jspx_th_html_005fform_005f0.setParent(null);
        // /page/index.jsp(161,0) name = action type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_html_005fform_005f0.setAction("/login");
        // /page/index.jsp(161,0) name = styleId type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_html_005fform_005f0.setStyleId("eduForm");
        int _jspx_eval_html_005fform_005f0 = _jspx_th_html_005fform_005f0.doStartTag();
        if (_jspx_eval_html_005fform_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write('\r');
            out.write('\n');
            if (_jspx_meth_html_005fhidden_005f0(_jspx_th_html_005fform_005f0, _jspx_page_context))
              return;
            out.write("\r\n");
            out.write("\r\n");
            out.write("	<div class=\"container\">\r\n");
            out.write("		<div class=\"logo\" >\r\n");
            out.write("			<img src=\"https://www.gtt2004.com/img/GTT_WHITE.png\" alt=\"\" width=\"200\" height=\"220\">    \r\n");
            out.write("			สวัสดีครับสมาชิกชมรมคนชอบ\r\n");
            out.write("		</div>\r\n");
            out.write("		<div class=\"row\" style=\"margin-top:10px\">\r\n");
            out.write("			<div id=\"main-login\">\r\n");
            out.write("				<div class=\"col-sm-12\" style=\"min-width: 300px;\">\r\n");
            out.write("					<div style=\"text-align: center;margin-top: 50px;\">\r\n");
            out.write("						");
            out.write("\r\n");
            out.write("					</div>\r\n");
            out.write("					<div style=\"text-align: center;margin-top: 5px;\">\r\n");
            out.write("						<div class=\"login-title\">LOGIN</div>\r\n");
            out.write("						<div class=\"login-box\">\r\n");
            out.write("							<!-- <div style=\"margin-bottom: 5px;\">เข้าใช้งานระบบ</div> -->\r\n");
            out.write("							\r\n");
            out.write("							<div class=\"form-group\">\r\n");
            out.write("								<div class=\"col-sm-10\" style=\"margin: 0 auto;float: none;\">\r\n");
            out.write("									");
            if (_jspx_meth_html_005ftext_005f0(_jspx_th_html_005fform_005f0, _jspx_page_context))
              return;
            out.write("\r\n");
            out.write("								</div>\r\n");
            out.write("							</div>\r\n");
            out.write("							<div class=\"form-group\">\r\n");
            out.write("								<div class=\"col-sm-10\" style=\"margin: 0 auto;float: none;\">\r\n");
            out.write("									");
            if (_jspx_meth_html_005fpassword_005f0(_jspx_th_html_005fform_005f0, _jspx_page_context))
              return;
            out.write("\r\n");
            out.write("								</div>\r\n");
            out.write("							</div>\r\n");
            out.write("							<div class=\"form-group\">\r\n");
            out.write("								<div class=\"col-sm-10\" style=\"margin: 0 auto;float: none;\">\r\n");
            out.write("									<button type=\"button\" class=\"btn btn-blue btn-sm\" style=\"width:100%;\" onclick=\"submitFormLogin();\">เข้าสู่ระบบ</button>\r\n");
            out.write("								</div>\r\n");
            out.write("							</div>\r\n");
            out.write("							\r\n");
            out.write("							<div class=\"form-group\">\r\n");
            out.write("							");
            //  bean:define
            org.apache.struts.taglib.bean.DefineTag _jspx_th_bean_005fdefine_005f0 = (org.apache.struts.taglib.bean.DefineTag) _005fjspx_005ftagPool_005fbean_005fdefine_0026_005fvalue_005fid_005fnobody.get(org.apache.struts.taglib.bean.DefineTag.class);
            boolean _jspx_th_bean_005fdefine_005f0_reused = false;
            try {
              _jspx_th_bean_005fdefine_005f0.setPageContext(_jspx_page_context);
              _jspx_th_bean_005fdefine_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_html_005fform_005f0);
              // /page/index.jsp(197,7) name = id type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
              _jspx_th_bean_005fdefine_005f0.setId("msgErrorCheck");
              // /page/index.jsp(197,7) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
              _jspx_th_bean_005fdefine_005f0.setValue((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${not empty msgError}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
              int _jspx_eval_bean_005fdefine_005f0 = _jspx_th_bean_005fdefine_005f0.doStartTag();
              if (_jspx_th_bean_005fdefine_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
                return;
              }
              _005fjspx_005ftagPool_005fbean_005fdefine_0026_005fvalue_005fid_005fnobody.reuse(_jspx_th_bean_005fdefine_005f0);
              _jspx_th_bean_005fdefine_005f0_reused = true;
            } finally {
              org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_bean_005fdefine_005f0, _jsp_getInstanceManager(), _jspx_th_bean_005fdefine_005f0_reused);
            }
            java.lang.String msgErrorCheck = null;
            msgErrorCheck = (java.lang.String) _jspx_page_context.findAttribute("msgErrorCheck");
            out.write("\r\n");
            out.write("							");
            if (_jspx_meth_logic_005fequal_005f0(_jspx_th_html_005fform_005f0, _jspx_page_context))
              return;
            out.write("\r\n");
            out.write("							");
            if (_jspx_meth_logic_005fequal_005f1(_jspx_th_html_005fform_005f0, _jspx_page_context))
              return;
            out.write("\r\n");
            out.write("							</div>\r\n");
            out.write("							\r\n");
            out.write("							\r\n");
            out.write("						</div>\r\n");
            out.write("					</div>\r\n");
            out.write("				</div>\r\n");
            out.write("			</div>\r\n");
            out.write("		</div>\r\n");
            out.write("	</div>\r\n");
            out.write("\r\n");
            int evalDoAfterBody = _jspx_th_html_005fform_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_html_005fform_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return;
        }
        _005fjspx_005ftagPool_005fhtml_005fform_0026_005fstyleId_005faction.reuse(_jspx_th_html_005fform_005f0);
        _jspx_th_html_005fform_005f0_reused = true;
      } finally {
        org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_html_005fform_005f0, _jsp_getInstanceManager(), _jspx_th_html_005fform_005f0_reused);
      }
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_html_005fhidden_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_html_005fform_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  html:hidden
    org.apache.struts.taglib.html.HiddenTag _jspx_th_html_005fhidden_005f0 = (org.apache.struts.taglib.html.HiddenTag) _005fjspx_005ftagPool_005fhtml_005fhidden_0026_005fproperty_005fnobody.get(org.apache.struts.taglib.html.HiddenTag.class);
    boolean _jspx_th_html_005fhidden_005f0_reused = false;
    try {
      _jspx_th_html_005fhidden_005f0.setPageContext(_jspx_page_context);
      _jspx_th_html_005fhidden_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_html_005fform_005f0);
      // /page/index.jsp(162,0) name = property type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_html_005fhidden_005f0.setProperty("mode");
      int _jspx_eval_html_005fhidden_005f0 = _jspx_th_html_005fhidden_005f0.doStartTag();
      if (_jspx_th_html_005fhidden_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fhtml_005fhidden_0026_005fproperty_005fnobody.reuse(_jspx_th_html_005fhidden_005f0);
      _jspx_th_html_005fhidden_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_html_005fhidden_005f0, _jsp_getInstanceManager(), _jspx_th_html_005fhidden_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_html_005ftext_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_html_005fform_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  html:text
    org.apache.struts.taglib.html.TextTag _jspx_th_html_005ftext_005f0 = (org.apache.struts.taglib.html.TextTag) _005fjspx_005ftagPool_005fhtml_005ftext_0026_005fstyleId_005fstyleClass_005fproperty_005fplaceHolder_005fonkeypress_005fmaxlength_005fnobody.get(org.apache.struts.taglib.html.TextTag.class);
    boolean _jspx_th_html_005ftext_005f0_reused = false;
    try {
      _jspx_th_html_005ftext_005f0.setPageContext(_jspx_page_context);
      _jspx_th_html_005ftext_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_html_005fform_005f0);
      // /page/index.jsp(182,9) name = property type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_html_005ftext_005f0.setProperty("un");
      // /page/index.jsp(182,9) name = maxlength type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_html_005ftext_005f0.setMaxlength("75");
      // /page/index.jsp(182,9) name = styleClass type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_html_005ftext_005f0.setStyleClass("form-control");
      // /page/index.jsp(182,9) name = styleId type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_html_005ftext_005f0.setStyleId("un");
      // /page/index.jsp(182,9) name = onkeypress type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_html_005ftext_005f0.setOnkeypress("submitEnter();");
      // /page/index.jsp(182,9) name = placeHolder type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_html_005ftext_005f0.setPlaceHolder("ชื่อผู้ใช้งาน");
      int _jspx_eval_html_005ftext_005f0 = _jspx_th_html_005ftext_005f0.doStartTag();
      if (_jspx_th_html_005ftext_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fhtml_005ftext_0026_005fstyleId_005fstyleClass_005fproperty_005fplaceHolder_005fonkeypress_005fmaxlength_005fnobody.reuse(_jspx_th_html_005ftext_005f0);
      _jspx_th_html_005ftext_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_html_005ftext_005f0, _jsp_getInstanceManager(), _jspx_th_html_005ftext_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_html_005fpassword_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_html_005fform_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  html:password
    org.apache.struts.taglib.html.PasswordTag _jspx_th_html_005fpassword_005f0 = (org.apache.struts.taglib.html.PasswordTag) _005fjspx_005ftagPool_005fhtml_005fpassword_0026_005fstyleId_005fstyleClass_005fproperty_005fplaceHolder_005fonkeypress_005fmaxlength_005fnobody.get(org.apache.struts.taglib.html.PasswordTag.class);
    boolean _jspx_th_html_005fpassword_005f0_reused = false;
    try {
      _jspx_th_html_005fpassword_005f0.setPageContext(_jspx_page_context);
      _jspx_th_html_005fpassword_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_html_005fform_005f0);
      // /page/index.jsp(187,9) name = property type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_html_005fpassword_005f0.setProperty("pw");
      // /page/index.jsp(187,9) name = maxlength type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_html_005fpassword_005f0.setMaxlength("75");
      // /page/index.jsp(187,9) name = styleClass type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_html_005fpassword_005f0.setStyleClass("form-control");
      // /page/index.jsp(187,9) name = styleId type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_html_005fpassword_005f0.setStyleId("pw");
      // /page/index.jsp(187,9) name = onkeypress type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_html_005fpassword_005f0.setOnkeypress("submitEnter();");
      // /page/index.jsp(187,9) name = placeHolder type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_html_005fpassword_005f0.setPlaceHolder("รหัสผ่าน");
      int _jspx_eval_html_005fpassword_005f0 = _jspx_th_html_005fpassword_005f0.doStartTag();
      if (_jspx_th_html_005fpassword_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fhtml_005fpassword_0026_005fstyleId_005fstyleClass_005fproperty_005fplaceHolder_005fonkeypress_005fmaxlength_005fnobody.reuse(_jspx_th_html_005fpassword_005f0);
      _jspx_th_html_005fpassword_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_html_005fpassword_005f0, _jsp_getInstanceManager(), _jspx_th_html_005fpassword_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_logic_005fequal_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_html_005fform_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  logic:equal
    org.apache.struts.taglib.logic.EqualTag _jspx_th_logic_005fequal_005f0 = (org.apache.struts.taglib.logic.EqualTag) _005fjspx_005ftagPool_005flogic_005fequal_0026_005fvalue_005fname.get(org.apache.struts.taglib.logic.EqualTag.class);
    boolean _jspx_th_logic_005fequal_005f0_reused = false;
    try {
      _jspx_th_logic_005fequal_005f0.setPageContext(_jspx_page_context);
      _jspx_th_logic_005fequal_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_html_005fform_005f0);
      // /page/index.jsp(198,7) name = name type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_logic_005fequal_005f0.setName("msgErrorCheck");
      // /page/index.jsp(198,7) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_logic_005fequal_005f0.setValue("true");
      int _jspx_eval_logic_005fequal_005f0 = _jspx_th_logic_005fequal_005f0.doStartTag();
      if (_jspx_eval_logic_005fequal_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("								<div class=\"col-sm-10 fred\" style=\"margin: 0 auto;float: none;\">\r\n");
          out.write("									<div class=\"alert alert-danger\" style=\"padding: 5px;font-size: 12px;\">");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${msgError}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</div>\r\n");
          out.write("								</div>\r\n");
          out.write("							");
          int evalDoAfterBody = _jspx_th_logic_005fequal_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_logic_005fequal_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005flogic_005fequal_0026_005fvalue_005fname.reuse(_jspx_th_logic_005fequal_005f0);
      _jspx_th_logic_005fequal_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_logic_005fequal_005f0, _jsp_getInstanceManager(), _jspx_th_logic_005fequal_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_logic_005fequal_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_html_005fform_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  logic:equal
    org.apache.struts.taglib.logic.EqualTag _jspx_th_logic_005fequal_005f1 = (org.apache.struts.taglib.logic.EqualTag) _005fjspx_005ftagPool_005flogic_005fequal_0026_005fvalue_005fname.get(org.apache.struts.taglib.logic.EqualTag.class);
    boolean _jspx_th_logic_005fequal_005f1_reused = false;
    try {
      _jspx_th_logic_005fequal_005f1.setPageContext(_jspx_page_context);
      _jspx_th_logic_005fequal_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_html_005fform_005f0);
      // /page/index.jsp(203,7) name = name type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_logic_005fequal_005f1.setName("msgErrorCheck");
      // /page/index.jsp(203,7) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_logic_005fequal_005f1.setValue("false");
      int _jspx_eval_logic_005fequal_005f1 = _jspx_th_logic_005fequal_005f1.doStartTag();
      if (_jspx_eval_logic_005fequal_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("								<div class=\"col-sm-10\" style=\"margin: 0 auto;float: none;\">&nbsp;</div>\r\n");
          out.write("							");
          int evalDoAfterBody = _jspx_th_logic_005fequal_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_logic_005fequal_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005flogic_005fequal_0026_005fvalue_005fname.reuse(_jspx_th_logic_005fequal_005f1);
      _jspx_th_logic_005fequal_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_logic_005fequal_005f1, _jsp_getInstanceManager(), _jspx_th_logic_005fequal_005f1_reused);
    }
    return false;
  }
}
