/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.64
 * Generated at: 2565-08-03 04:27:07 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.page.feature;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class addRequest_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(7);
    _jspx_dependants.put("/page/inc_header.jsp", Long.valueOf(1659496623067L));
    _jspx_dependants.put("/WEB-INF/tld/fn.tld", Long.valueOf(1659496623061L));
    _jspx_dependants.put("/WEB-INF/tld/struts-bean.tld", Long.valueOf(1659496623063L));
    _jspx_dependants.put("/page/inc_header_script.jsp", Long.valueOf(1659500588543L));
    _jspx_dependants.put("/WEB-INF/tld/struts-html.tld", Long.valueOf(1659496623063L));
    _jspx_dependants.put("/WEB-INF/tld/c.tld", Long.valueOf(1659496623059L));
    _jspx_dependants.put("/WEB-INF/tld/struts-logic.tld", Long.valueOf(1659496623064L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fhtml_005fform_0026_005fstyleId_005faction;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fhtml_005fhidden_0026_005fproperty_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fhtml_005fselect_0026_005fstyleClass_005fproperty;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fhtml_005foptionsCollection_0026_005fvalue_005fproperty_005flabel_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fhtml_005ftext_0026_005fstyleId_005fstyleClass_005fproperty_005fplaceHolder_005fonkeypress_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fhtml_005fform_0026_005fstyleId_005faction = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fhtml_005fhidden_0026_005fproperty_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fhtml_005fselect_0026_005fstyleClass_005fproperty = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fhtml_005foptionsCollection_0026_005fvalue_005fproperty_005flabel_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fhtml_005ftext_0026_005fstyleId_005fstyleClass_005fproperty_005fplaceHolder_005fonkeypress_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fhtml_005fform_0026_005fstyleId_005faction.release();
    _005fjspx_005ftagPool_005fhtml_005fhidden_0026_005fproperty_005fnobody.release();
    _005fjspx_005ftagPool_005fhtml_005fselect_0026_005fstyleClass_005fproperty.release();
    _005fjspx_005ftagPool_005fhtml_005foptionsCollection_0026_005fvalue_005fproperty_005flabel_005fnobody.release();
    _005fjspx_005ftagPool_005fhtml_005ftext_0026_005fstyleId_005fstyleClass_005fproperty_005fplaceHolder_005fonkeypress_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("	<meta charset=\"utf-8\">\r\n");
      out.write("	<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("	<meta name=\"description\" content=\"\">\r\n");
      out.write("	<meta name=\"author\" content=\"\">\r\n");
      out.write("	<meta name=\"keyword\" content=\"\">\r\n");
      out.write("	\r\n");
      out.write("	<title>Service Tracking</title>\r\n");
      out.write("\r\n");
      out.write("	\r\n");
      out.write("	 \r\n");
      out.write("	 <script src=\"//cdn.jsdelivr.net/npm/sweetalert2@11\"></script>\r\n");
      out.write("	 <!-- Font Awesome -->\r\n");
      out.write("	 <linkhref=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css\" rel=\"stylesheet\"/>\r\n");
      out.write("	 <!-- Google Fonts -->\r\n");
      out.write("	 <linkhref=\"https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap\" rel=\"stylesheet\"/>\r\n");
      out.write("	 <!-- MDB -->\r\n");
      out.write("	 <linkhref=\"https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/4.2.0/mdb.min.css\"rel=\"stylesheet\"/>\r\n");
      out.write("	 <!-- MDB -->\r\n");
      out.write("	 <scripttype=\"text/javascript\" src=\"https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/4.2.0/mdb.min.js\"></script>\r\n");
      out.write("	<!-- font -->\r\n");
      out.write("	<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/ui/fonts/webfont.css\" rel=\"stylesheet\" />\r\n");
      out.write("	<!-- font icon -->\r\n");
      out.write("	<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/ui/css/elegant-icons-style.css\" rel=\"stylesheet\" />\r\n");
      out.write("	<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/ui/css/font-awesome.min.css\" rel=\"stylesheet\" />\r\n");
      out.write("	<!-- datatable -->\r\n");
      out.write("	<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/ui/css/dataTables.bootstrap.css\" rel=\"stylesheet\"/>\r\n");
      out.write("	<!-- Custom styles -->\r\n");
      out.write("	<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/ui/css/style-responsive.css\" rel=\"stylesheet\" />\r\n");
      out.write("	<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/ui/css/jquery-ui-10.12.1.css\" rel=\"stylesheet\"/>\r\n");
      out.write("	<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/ui/css/style-button.css\" rel=\"stylesheet\"/>\r\n");
      out.write("	<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/ui/css/bootstrap-select.css\" rel=\"stylesheet\"/>\r\n");
      out.write("	<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/ui/css/materialize-color.css\" rel=\"stylesheet\"/>\r\n");
      out.write("	<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/ui/sweetalert/css/sweetalert.css\" rel=\"stylesheet\"/>\r\n");
      out.write("\r\n");
      out.write("	<!-- javascripts -->\r\n");
      out.write("	<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/ui/js/jquery-1.12.4.js\"></script>\r\n");
      out.write("	<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/ui/js/jquery-ui-1.10.4.min.js\"></script>\r\n");
      out.write("	<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/ui/js/jquery-1.8.3.min.js\"></script>\r\n");
      out.write("	<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/ui/js/jquery-ui-1.9.2.custom.min.js\" type=\"text/javascript\"></script>\r\n");
      out.write("	<!-- for set format thai -->\r\n");
      out.write("	<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/ui/js/jquery.ui.1.8.10.offset.datepicker.min.js\" type=\"text/javascript\"></script>\r\n");
      out.write("	\r\n");
      out.write("	<!-- bootstrap -->\r\n");
      out.write("	<!-- nice scroll -->\r\n");
      out.write("	<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/ui/js/jquery.scrollTo.min.js\"></script>\r\n");
      out.write("	<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/ui/js/jquery.nicescroll.js\" type=\"text/javascript\"></script>\r\n");
      out.write("	<!-- custom select -->\r\n");
      out.write("	<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/ui/js/jquery.customSelect.min.js\"></script>\r\n");
      out.write("	<link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css\" rel=\"stylesheet\" integrity=\"sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor\" crossorigin=\"anonymous\">\r\n");
      out.write("	<!--custome script for all page-->\r\n");
      out.write("	<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/ui/js/scripts.js\"></script>\r\n");
      out.write("	\r\n");
      out.write("	<!-- custom script for this page-->\r\n");
      out.write("	<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/ui/js/jquery.autosize.min.js\"></script>\r\n");
      out.write("	<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/ui/js/jquery.placeholder.min.js\"></script>\r\n");
      out.write("	<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/ui/js/jquery.slimscroll.min.js\"></script>\r\n");
      out.write("	<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/ui/js/bootbox.js\"></script>\r\n");
      out.write("	<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/ui/js/bootstrap-select.js\"></script>\r\n");
      out.write("	<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/ui/js/bootstrap-typeahead.js\"></script>\r\n");
      out.write("	<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js\" integrity=\"sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("	<!-- datatable -->\r\n");
      out.write("	<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/ui/js/jquery.dataTables.js\" type=\"text/javascript\"></script>\r\n");
      out.write("	<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/ui/js/dataTables.bootstrap.js\" type=\"text/javascript\"></script>\r\n");
      out.write("	\r\n");
      out.write("	<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/ui/js/jquery.validate.min.js\" type=\"text/javascript\"></script>\r\n");
      out.write("	<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/ui/js/quotwaiting-forquot-modal-dialog.js\" type=\"text/javascript\"></script>\r\n");
      out.write("	<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/ui/sweetalert/js/sweetalert.min.js\" type=\"text/javascript\"></script>\r\n");
      out.write("	\r\n");
      out.write("	<script type=\"text/javascript\">\r\n");
      out.write(" 		$(document).ready(function () {\r\n");
      out.write(" 			\r\n");
      out.write(" 			$(\"#msgSuccess\").delay(800).fadeOut(1000);\r\n");
      out.write(" 			$(\"#msgWarning\").delay(800).fadeOut(1000);\r\n");
      out.write(" 			\r\n");
      out.write("			try {\r\n");
      out.write("				var variables = {};\r\n");
      out.write("		      	variables = {\r\n");
      out.write("						\"sProcessing\": \"กำลังดำเนินการ...\",\r\n");
      out.write("						\"sLengthMenu\": \"แสดง _MENU_  แถว\",\r\n");
      out.write("						\"sZeroRecords\": \"ไม่พบข้อมูล\",\r\n");
      out.write("						\"sInfo\": \"แสดง _START_ ถึง _END_ จาก _TOTAL_ แถว\",\r\n");
      out.write("						\"sInfoEmpty\": \"แสดง 0 ถึง 0 จาก 0 แถว\",\r\n");
      out.write("						\"sInfoFiltered\": \"(กรองข้อมูล _MAX_ ทุกแถว)\",\r\n");
      out.write("						\"sInfoPostFix\": \"\",\r\n");
      out.write("						\"sSearch\": \"ค้นหา: \",\r\n");
      out.write("						\"sUrl\": \"\",\r\n");
      out.write("						\"oPaginate\": {\r\n");
      out.write("						    \"sFirst\": \"เริ่มต้น\",\r\n");
      out.write("						    \"sPrevious\": \"ก่อนหน้า\",\r\n");
      out.write("						    \"sNext\": \"ถัดไป\",\r\n");
      out.write("						    \"sLast\": \"สุดท้าย\"\r\n");
      out.write("						}\r\n");
      out.write("				};\r\n");
      out.write("			\r\n");
      out.write("				var options = { \"aoColumnDefs\": [{ bSortable: false, aTargets: ['no-sort'] }],\"oLanguage\": variables};\r\n");
      out.write("				var optionsHundred = { \"aoColumnDefs\": [{ bSortable: false, aTargets: ['no-sort'] }],\"iDisplayLength\": 100,\"oLanguage\": variables};\r\n");
      out.write("				var optionsFive = { \"aoColumnDefs\": [{ bSortable: false, aTargets: ['no-sort'] }],\"iDisplayLength\": 5,\"oLanguage\": variables};\r\n");
      out.write("			\r\n");
      out.write("				$(\".grid-default\").dataTable(options);\r\n");
      out.write("				$(\".grid-hundred\").dataTable(optionsHundred);\r\n");
      out.write("				$(\".grid-five\").dataTable(optionsFive);\r\n");
      out.write("			} catch (e) {\r\n");
      out.write("			}\r\n");
      out.write("			\r\n");
      out.write("			$.datepicker.isBuddhist ={\r\n");
      out.write("				isBuddhist: true,\r\n");
      out.write("				changeMonth: true,\r\n");
      out.write("		        changeYear: true,\r\n");
      out.write("		        buttonImageOnly: false,\r\n");
      out.write("		        dateFormat: 'dd/mm/yy',\r\n");
      out.write("		        dayNames: ['อาทิตย์', 'จันทร์', 'อังคาร', 'พุธ', 'พฤหัสบดี', 'ศุกร์', 'เสาร์'],\r\n");
      out.write("		        dayNamesMin: ['อา', 'จ', 'อ', 'พ', 'พฤ', 'ศ', 'ส'],\r\n");
      out.write("		        monthNames: ['มกราคม', 'กุมภาพันธ์', 'มีนาคม', 'เมษายน', 'พฤษภาคม', 'มิถุนายน', 'กรกฎาคม', 'สิงหาคม', 'กันยายน', 'ตุลาคม', 'พฤศจิกายน', 'ธันวาคม'],\r\n");
      out.write("		        //monthNamesShort: ['มกราคม', 'กุมภาพันธ์', 'มีนาคม', 'เมษายน', 'พฤษภาคม', 'มิถุนายน', 'กรกฎาคม', 'สิงหาคม', 'กันยายน', 'ตุลาคม', 'พฤศจิกายน', 'ธันวาคม'],\r\n");
      out.write("		        monthNamesShort: ['ม.ค.', 'ก.พ.', 'มี.ค.', 'เม.ย.', 'พ.ค.', 'มิ.ย.', 'ก.ค.', 'ส.ค.', 'ก.ย.', 'ต.ค.', 'พ.ย.', 'ธ.ค.'],\r\n");
      out.write("		        constrainInput: true,	\r\n");
      out.write("		        prevText: 'ก่อนหน้า',\r\n");
      out.write("		        nextText: 'ถัดไป',\r\n");
      out.write("		        yearRange: '-200:+10',\r\n");
      out.write("		        buttonText: 'เลือก'\r\n");
      out.write("		    };\r\n");
      out.write("			\r\n");
      out.write("			$.datepicker.twomonth ={\r\n");
      out.write("				isBuddhist: true,\r\n");
      out.write("				changeMonth: false,\r\n");
      out.write("		        changeYear: false,\r\n");
      out.write("		        buttonImageOnly: false,\r\n");
      out.write("		        dateFormat: 'dd/mm/yy',\r\n");
      out.write("		        dayNames: ['อาทิตย์', 'จันทร์', 'อังคาร', 'พุธ', 'พฤหัสบดี', 'ศุกร์', 'เสาร์'],\r\n");
      out.write("		        dayNamesMin: ['อา', 'จ', 'อ', 'พ', 'พฤ', 'ศ', 'ส'],\r\n");
      out.write("		        monthNames: ['มกราคม', 'กุมภาพันธ์', 'มีนาคม', 'เมษายน', 'พฤษภาคม', 'มิถุนายน', 'กรกฎาคม', 'สิงหาคม', 'กันยายน', 'ตุลาคม', 'พฤศจิกายน', 'ธันวาคม'],\r\n");
      out.write("		        //monthNamesShort: ['มกราคม', 'กุมภาพันธ์', 'มีนาคม', 'เมษายน', 'พฤษภาคม', 'มิถุนายน', 'กรกฎาคม', 'สิงหาคม', 'กันยายน', 'ตุลาคม', 'พฤศจิกายน', 'ธันวาคม'],\r\n");
      out.write("		        monthNamesShort: ['ม.ค.', 'ก.พ.', 'มี.ค.', 'เม.ย.', 'พ.ค.', 'มิ.ย.', 'ก.ค.', 'ส.ค.', 'ก.ย.', 'ต.ค.', 'พ.ย.', 'ธ.ค.'],\r\n");
      out.write("		        constrainInput: true,	\r\n");
      out.write("		        prevText: 'ก่อนหน้า',\r\n");
      out.write("		        nextText: 'ถัดไป',\r\n");
      out.write("		        yearRange: '-200:+10',\r\n");
      out.write("		        buttonText: 'เลือก',\r\n");
      out.write("		        numberOfMonths: 2\r\n");
      out.write("		    };\r\n");
      out.write(" 			$('.i-calendar').datepicker($.datepicker.isBuddhist);\r\n");
      out.write("			$('.t-calendar').datepicker($.datepicker.twomonth);\r\n");
      out.write("			\r\n");
      out.write("			$( \"#dateStart\" ).datepicker({\r\n");
      out.write("		    	isBuddhist: true,\r\n");
      out.write("				changeMonth: true,\r\n");
      out.write("		        changeYear: true,\r\n");
      out.write("		        buttonImageOnly: false,\r\n");
      out.write("		        dateFormat: 'dd/mm/yy',\r\n");
      out.write("		        dayNames: ['อาทิตย์', 'จันทร์', 'อังคาร', 'พุธ', 'พฤหัสบดี', 'ศุกร์', 'เสาร์'],\r\n");
      out.write("		        dayNamesMin: ['อา', 'จ', 'อ', 'พ', 'พฤ', 'ศ', 'ส'],\r\n");
      out.write("		        monthNames: ['มกราคม', 'กุมภาพันธ์', 'มีนาคม', 'เมษายน', 'พฤษภาคม', 'มิถุนายน', 'กรกฎาคม', 'สิงหาคม', 'กันยายน', 'ตุลาคม', 'พฤศจิกายน', 'ธันวาคม'],\r\n");
      out.write("		        monthNamesShort: ['ม.ค.', 'ก.พ.', 'มี.ค.', 'เม.ย.', 'พ.ค.', 'มิ.ย.', 'ก.ค.', 'ส.ค.', 'ก.ย.', 'ต.ค.', 'พ.ย.', 'ธ.ค.'],\r\n");
      out.write("		        constrainInput: true,	\r\n");
      out.write("		        prevText: 'ก่อนหน้า',\r\n");
      out.write("		        nextText: 'ถัดไป',\r\n");
      out.write("		        yearRange: '-200:+5',\r\n");
      out.write("		        buttonText: 'เลือก',\r\n");
      out.write("		        numberOfMonths: 2,\r\n");
      out.write("		      	onClose: function( selectedDate ) {\r\n");
      out.write("		        	$( \"#dateStop\" ).datepicker( \"option\", \"minDate\", selectedDate );\r\n");
      out.write("		      	}\r\n");
      out.write("		    });\r\n");
      out.write("			\r\n");
      out.write("		    $( \"#dateStop\" ).datepicker({\r\n");
      out.write("		    	isBuddhist: true,\r\n");
      out.write("				changeMonth: true,\r\n");
      out.write("		        changeYear: true,\r\n");
      out.write("		        buttonImageOnly: false,\r\n");
      out.write("		        dateFormat: 'dd/mm/yy',\r\n");
      out.write("		        dayNames: ['อาทิตย์', 'จันทร์', 'อังคาร', 'พุธ', 'พฤหัสบดี', 'ศุกร์', 'เสาร์'],\r\n");
      out.write("		        dayNamesMin: ['อา', 'จ', 'อ', 'พ', 'พฤ', 'ศ', 'ส'],\r\n");
      out.write("		        monthNames: ['มกราคม', 'กุมภาพันธ์', 'มีนาคม', 'เมษายน', 'พฤษภาคม', 'มิถุนายน', 'กรกฎาคม', 'สิงหาคม', 'กันยายน', 'ตุลาคม', 'พฤศจิกายน', 'ธันวาคม'],\r\n");
      out.write("		        monthNamesShort: ['ม.ค.', 'ก.พ.', 'มี.ค.', 'เม.ย.', 'พ.ค.', 'มิ.ย.', 'ก.ค.', 'ส.ค.', 'ก.ย.', 'ต.ค.', 'พ.ย.', 'ธ.ค.'],\r\n");
      out.write("		        constrainInput: true,	\r\n");
      out.write("		        prevText: 'ก่อนหน้า',\r\n");
      out.write("		        nextText: 'ถัดไป',\r\n");
      out.write("		        yearRange: '-200:+5',\r\n");
      out.write("		        buttonText: 'เลือก',\r\n");
      out.write("		        numberOfMonths: 2,\r\n");
      out.write("		      onClose: function( selectedDate ) {\r\n");
      out.write("		        $( \"#dateStart\" ).datepicker( \"option\", \"maxDate\", selectedDate );\r\n");
      out.write("		      }\r\n");
      out.write("		    });\r\n");
      out.write("        });\r\n");
      out.write(" 		\r\n");
      out.write(" 		function showDialogContent(url,title,size){\r\n");
      out.write(" 			\r\n");
      out.write(" 			$.post(url,{}, \r\n");
      out.write(" 				function(results) {	 \r\n");
      out.write(" 				var textAndPic = $('<div id=\"dialogs\">'+results+'</div>');	\r\n");
      out.write(" 				var bootdialog = bootbox.dialog({\r\n");
      out.write(" 				    title: title,\r\n");
      out.write(" 				    message: textAndPic,\r\n");
      out.write(" 				    className: size\r\n");
      out.write(" 				});\r\n");
      out.write(" 				\r\n");
      out.write(" 				$('.selectpicker').selectpicker('refresh');\r\n");
      out.write(" 				\r\n");
      out.write(" 				/* dialog.init(function(){\r\n");
      out.write(" 				    setTimeout(function(){\r\n");
      out.write(" 				        dialog.find('.bootbox-body').html(textAndPic);\r\n");
      out.write(" 				    }, 3000);\r\n");
      out.write(" 				}); */	\r\n");
      out.write(" 				\r\n");
      out.write(" 			});	\r\n");
      out.write(" 		}\r\n");
      out.write(" 		\r\n");
      out.write(" 		function showDialog(url,t,w,h){    		\r\n");
      out.write(" 	        $('#dialogs').dialog({\r\n");
      out.write(" 	        	modal: true,\r\n");
      out.write(" 	        	show: {\r\n");
      out.write(" 					effect: \"fade\",\r\n");
      out.write(" 					duration: 200\r\n");
      out.write(" 				},\r\n");
      out.write(" 	        	title: t,\r\n");
      out.write(" 	            width: w,\r\n");
      out.write(" 	            height: h,\r\n");
      out.write(" 	            closeOnEscape: true,\r\n");
      out.write(" 	            open: function () {\r\n");
      out.write(" 	                $.post(url,{}, \r\n");
      out.write(" 	              	function(results) {	 \r\n");
      out.write(" 	              		$('#dialogs').html(results);	\r\n");
      out.write(" 	              		$('#dialogs').siblings('.ui-dialog-titlebar').find('button').blur(); \r\n");
      out.write(" 	              		\r\n");
      out.write(" 	             	});\r\n");
      out.write(" 	            }\r\n");
      out.write(" 	        });\r\n");
      out.write(" 		}\r\n");
      out.write(" 		\r\n");
      out.write(" 		function showLoadingSwal() {\r\n");
      out.write(" 			swal({\r\n");
      out.write("      		  	title: \"กำลังโหลดข้อมูล...\",\r\n");
      out.write("      		  	imageUrl: '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/ui/sweetalert/image/entering-comment-loader.gif',\r\n");
      out.write("      			closeOnConfirm: false,\r\n");
      out.write("      			showCancelButton: false,\r\n");
      out.write("      			showConfirmButton: false,\r\n");
      out.write("      		});\r\n");
      out.write(" 		}\r\n");
      out.write(" 		function success() {\r\n");
      out.write(" 	        swal.close()\r\n");
      out.write(" 	    }\r\n");
      out.write("	</script>\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("	.popup-dialog .modal-dialog { width: 700px; }\r\n");
      out.write("	.popuplg-dialog .modal-dialog { width: 1000px; }\r\n");
      out.write("</style>\r\n");
      out.write("</head>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script src=\"//cdn.jsdelivr.net/npm/sweetalert2@11\"></script>\r\n");
      out.write("\r\n");
      out.write("<script language=\"javascript\" type=\"text/javascript\">\r\n");
      out.write("	function add() {\r\n");
      out.write("		Swal.fire({\r\n");
      out.write("			  title: 'Are you sure?',\r\n");
      out.write("			  text: \"You want to logout!\",\r\n");
      out.write("			  icon: 'warning',\r\n");
      out.write("			  showCancelButton: true,\r\n");
      out.write("			  confirmButtonColor: '#3085d6',\r\n");
      out.write("			  cancelButtonColor: '#d33',\r\n");
      out.write("			  confirmButtonText: 'Yes'\r\n");
      out.write("			}).then((result) => {\r\n");
      out.write("				if(result.isConfirmed){\r\n");
      out.write("					document.forms[0].mode.value = \"addRequest\";\r\n");
      out.write("					document.forms[0].submit();\r\n");
      out.write("				}\r\n");
      out.write("			    \r\n");
      out.write("			  })\r\n");
      out.write("		\r\n");
      out.write("	}\r\n");
      out.write("	function back() {\r\n");
      out.write("		document.forms[0].mode.value = \"getRequest\";\r\n");
      out.write("		document.forms[0].submit();\r\n");
      out.write("	}\r\n");
      out.write("	function submitEnter() {\r\n");
      out.write("		if (checkKeyEnter() == true) submitFormLogin();\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	function checkKeyEnter(){\r\n");
      out.write("		   if(event.keyCode==13) return true;\r\n");
      out.write("	}\r\n");
      out.write("		\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      if (_jspx_meth_html_005fform_005f0(_jspx_page_context))
        return;
      out.write("   \r\n");
      out.write("\r\n");
      out.write("</body>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_html_005fform_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  html:form
    org.apache.struts.taglib.html.FormTag _jspx_th_html_005fform_005f0 = (org.apache.struts.taglib.html.FormTag) _005fjspx_005ftagPool_005fhtml_005fform_0026_005fstyleId_005faction.get(org.apache.struts.taglib.html.FormTag.class);
    boolean _jspx_th_html_005fform_005f0_reused = false;
    try {
      _jspx_th_html_005fform_005f0.setPageContext(_jspx_page_context);
      _jspx_th_html_005fform_005f0.setParent(null);
      // /page/feature/addRequest.jsp(46,0) name = action type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_html_005fform_005f0.setAction("/index");
      // /page/feature/addRequest.jsp(46,0) name = styleId type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_html_005fform_005f0.setStyleId("eduForm");
      int _jspx_eval_html_005fform_005f0 = _jspx_th_html_005fform_005f0.doStartTag();
      if (_jspx_eval_html_005fform_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write('\r');
          out.write('\n');
          if (_jspx_meth_html_005fhidden_005f0(_jspx_th_html_005fform_005f0, _jspx_page_context))
            return true;
          out.write('\r');
          out.write('\n');
          out.write('	');
          out.write("\r\n");
          out.write("\r\n");
          out.write("\r\n");
          out.write("\r\n");
          out.write("\r\n");
          out.write("\r\n");
          out.write("\r\n");
          out.write("\r\n");
          out.write("<html>\r\n");
          out.write("<head>\r\n");
          out.write("	<meta charset=\"utf-8\">\r\n");
          out.write("	<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
          out.write("	<meta name=\"description\" content=\"\">\r\n");
          out.write("	<meta name=\"author\" content=\"\">\r\n");
          out.write("	<meta name=\"keyword\" content=\"\">\r\n");
          out.write("	\r\n");
          out.write("	<title>Service Tracking</title>\r\n");
          out.write("\r\n");
          out.write("	\r\n");
          out.write("	 \r\n");
          out.write("	 <script src=\"//cdn.jsdelivr.net/npm/sweetalert2@11\"></script>\r\n");
          out.write("	 <!-- Font Awesome -->\r\n");
          out.write("	 <linkhref=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css\" rel=\"stylesheet\"/>\r\n");
          out.write("	 <!-- Google Fonts -->\r\n");
          out.write("	 <linkhref=\"https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap\" rel=\"stylesheet\"/>\r\n");
          out.write("	 <!-- MDB -->\r\n");
          out.write("	 <linkhref=\"https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/4.2.0/mdb.min.css\"rel=\"stylesheet\"/>\r\n");
          out.write("	 <!-- MDB -->\r\n");
          out.write("	 <scripttype=\"text/javascript\" src=\"https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/4.2.0/mdb.min.js\"></script>\r\n");
          out.write("	<!-- font -->\r\n");
          out.write("	<link href=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/ui/fonts/webfont.css\" rel=\"stylesheet\" />\r\n");
          out.write("	<!-- font icon -->\r\n");
          out.write("	<link href=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/ui/css/elegant-icons-style.css\" rel=\"stylesheet\" />\r\n");
          out.write("	<link href=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/ui/css/font-awesome.min.css\" rel=\"stylesheet\" />\r\n");
          out.write("	<!-- datatable -->\r\n");
          out.write("	<link href=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/ui/css/dataTables.bootstrap.css\" rel=\"stylesheet\"/>\r\n");
          out.write("	<!-- Custom styles -->\r\n");
          out.write("	<link href=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/ui/css/style-responsive.css\" rel=\"stylesheet\" />\r\n");
          out.write("	<link href=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/ui/css/jquery-ui-10.12.1.css\" rel=\"stylesheet\"/>\r\n");
          out.write("	<link href=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/ui/css/style-button.css\" rel=\"stylesheet\"/>\r\n");
          out.write("	<link href=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/ui/css/bootstrap-select.css\" rel=\"stylesheet\"/>\r\n");
          out.write("	<link href=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/ui/css/materialize-color.css\" rel=\"stylesheet\"/>\r\n");
          out.write("	<link href=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/ui/sweetalert/css/sweetalert.css\" rel=\"stylesheet\"/>\r\n");
          out.write("\r\n");
          out.write("	<!-- javascripts -->\r\n");
          out.write("	<script src=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/ui/js/jquery-1.12.4.js\"></script>\r\n");
          out.write("	<script src=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/ui/js/jquery-ui-1.10.4.min.js\"></script>\r\n");
          out.write("	<script src=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/ui/js/jquery-1.8.3.min.js\"></script>\r\n");
          out.write("	<script src=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/ui/js/jquery-ui-1.9.2.custom.min.js\" type=\"text/javascript\"></script>\r\n");
          out.write("	<!-- for set format thai -->\r\n");
          out.write("	<script src=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/ui/js/jquery.ui.1.8.10.offset.datepicker.min.js\" type=\"text/javascript\"></script>\r\n");
          out.write("	\r\n");
          out.write("	<!-- bootstrap -->\r\n");
          out.write("	<!-- nice scroll -->\r\n");
          out.write("	<script src=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/ui/js/jquery.scrollTo.min.js\"></script>\r\n");
          out.write("	<script src=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/ui/js/jquery.nicescroll.js\" type=\"text/javascript\"></script>\r\n");
          out.write("	<!-- custom select -->\r\n");
          out.write("	<script src=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/ui/js/jquery.customSelect.min.js\"></script>\r\n");
          out.write("	<link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css\" rel=\"stylesheet\" integrity=\"sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor\" crossorigin=\"anonymous\">\r\n");
          out.write("	<!--custome script for all page-->\r\n");
          out.write("	<script src=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/ui/js/scripts.js\"></script>\r\n");
          out.write("	\r\n");
          out.write("	<!-- custom script for this page-->\r\n");
          out.write("	<script src=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/ui/js/jquery.autosize.min.js\"></script>\r\n");
          out.write("	<script src=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/ui/js/jquery.placeholder.min.js\"></script>\r\n");
          out.write("	<script src=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/ui/js/jquery.slimscroll.min.js\"></script>\r\n");
          out.write("	<script src=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/ui/js/bootbox.js\"></script>\r\n");
          out.write("	<script src=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/ui/js/bootstrap-select.js\"></script>\r\n");
          out.write("	<script src=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/ui/js/bootstrap-typeahead.js\"></script>\r\n");
          out.write("	<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js\" integrity=\"sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM\" crossorigin=\"anonymous\"></script>\r\n");
          out.write("	<!-- datatable -->\r\n");
          out.write("	<script src=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/ui/js/jquery.dataTables.js\" type=\"text/javascript\"></script>\r\n");
          out.write("	<script src=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/ui/js/dataTables.bootstrap.js\" type=\"text/javascript\"></script>\r\n");
          out.write("	\r\n");
          out.write("	<script src=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/ui/js/jquery.validate.min.js\" type=\"text/javascript\"></script>\r\n");
          out.write("	<script src=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/ui/js/quotwaiting-forquot-modal-dialog.js\" type=\"text/javascript\"></script>\r\n");
          out.write("	<script src=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/ui/sweetalert/js/sweetalert.min.js\" type=\"text/javascript\"></script>\r\n");
          out.write("	\r\n");
          out.write("	<script type=\"text/javascript\">\r\n");
          out.write(" 		$(document).ready(function () {\r\n");
          out.write(" 			\r\n");
          out.write(" 			$(\"#msgSuccess\").delay(800).fadeOut(1000);\r\n");
          out.write(" 			$(\"#msgWarning\").delay(800).fadeOut(1000);\r\n");
          out.write(" 			\r\n");
          out.write("			try {\r\n");
          out.write("				var variables = {};\r\n");
          out.write("		      	variables = {\r\n");
          out.write("						\"sProcessing\": \"กำลังดำเนินการ...\",\r\n");
          out.write("						\"sLengthMenu\": \"แสดง _MENU_  แถว\",\r\n");
          out.write("						\"sZeroRecords\": \"ไม่พบข้อมูล\",\r\n");
          out.write("						\"sInfo\": \"แสดง _START_ ถึง _END_ จาก _TOTAL_ แถว\",\r\n");
          out.write("						\"sInfoEmpty\": \"แสดง 0 ถึง 0 จาก 0 แถว\",\r\n");
          out.write("						\"sInfoFiltered\": \"(กรองข้อมูล _MAX_ ทุกแถว)\",\r\n");
          out.write("						\"sInfoPostFix\": \"\",\r\n");
          out.write("						\"sSearch\": \"ค้นหา: \",\r\n");
          out.write("						\"sUrl\": \"\",\r\n");
          out.write("						\"oPaginate\": {\r\n");
          out.write("						    \"sFirst\": \"เริ่มต้น\",\r\n");
          out.write("						    \"sPrevious\": \"ก่อนหน้า\",\r\n");
          out.write("						    \"sNext\": \"ถัดไป\",\r\n");
          out.write("						    \"sLast\": \"สุดท้าย\"\r\n");
          out.write("						}\r\n");
          out.write("				};\r\n");
          out.write("			\r\n");
          out.write("				var options = { \"aoColumnDefs\": [{ bSortable: false, aTargets: ['no-sort'] }],\"oLanguage\": variables};\r\n");
          out.write("				var optionsHundred = { \"aoColumnDefs\": [{ bSortable: false, aTargets: ['no-sort'] }],\"iDisplayLength\": 100,\"oLanguage\": variables};\r\n");
          out.write("				var optionsFive = { \"aoColumnDefs\": [{ bSortable: false, aTargets: ['no-sort'] }],\"iDisplayLength\": 5,\"oLanguage\": variables};\r\n");
          out.write("			\r\n");
          out.write("				$(\".grid-default\").dataTable(options);\r\n");
          out.write("				$(\".grid-hundred\").dataTable(optionsHundred);\r\n");
          out.write("				$(\".grid-five\").dataTable(optionsFive);\r\n");
          out.write("			} catch (e) {\r\n");
          out.write("			}\r\n");
          out.write("			\r\n");
          out.write("			$.datepicker.isBuddhist ={\r\n");
          out.write("				isBuddhist: true,\r\n");
          out.write("				changeMonth: true,\r\n");
          out.write("		        changeYear: true,\r\n");
          out.write("		        buttonImageOnly: false,\r\n");
          out.write("		        dateFormat: 'dd/mm/yy',\r\n");
          out.write("		        dayNames: ['อาทิตย์', 'จันทร์', 'อังคาร', 'พุธ', 'พฤหัสบดี', 'ศุกร์', 'เสาร์'],\r\n");
          out.write("		        dayNamesMin: ['อา', 'จ', 'อ', 'พ', 'พฤ', 'ศ', 'ส'],\r\n");
          out.write("		        monthNames: ['มกราคม', 'กุมภาพันธ์', 'มีนาคม', 'เมษายน', 'พฤษภาคม', 'มิถุนายน', 'กรกฎาคม', 'สิงหาคม', 'กันยายน', 'ตุลาคม', 'พฤศจิกายน', 'ธันวาคม'],\r\n");
          out.write("		        //monthNamesShort: ['มกราคม', 'กุมภาพันธ์', 'มีนาคม', 'เมษายน', 'พฤษภาคม', 'มิถุนายน', 'กรกฎาคม', 'สิงหาคม', 'กันยายน', 'ตุลาคม', 'พฤศจิกายน', 'ธันวาคม'],\r\n");
          out.write("		        monthNamesShort: ['ม.ค.', 'ก.พ.', 'มี.ค.', 'เม.ย.', 'พ.ค.', 'มิ.ย.', 'ก.ค.', 'ส.ค.', 'ก.ย.', 'ต.ค.', 'พ.ย.', 'ธ.ค.'],\r\n");
          out.write("		        constrainInput: true,	\r\n");
          out.write("		        prevText: 'ก่อนหน้า',\r\n");
          out.write("		        nextText: 'ถัดไป',\r\n");
          out.write("		        yearRange: '-200:+10',\r\n");
          out.write("		        buttonText: 'เลือก'\r\n");
          out.write("		    };\r\n");
          out.write("			\r\n");
          out.write("			$.datepicker.twomonth ={\r\n");
          out.write("				isBuddhist: true,\r\n");
          out.write("				changeMonth: false,\r\n");
          out.write("		        changeYear: false,\r\n");
          out.write("		        buttonImageOnly: false,\r\n");
          out.write("		        dateFormat: 'dd/mm/yy',\r\n");
          out.write("		        dayNames: ['อาทิตย์', 'จันทร์', 'อังคาร', 'พุธ', 'พฤหัสบดี', 'ศุกร์', 'เสาร์'],\r\n");
          out.write("		        dayNamesMin: ['อา', 'จ', 'อ', 'พ', 'พฤ', 'ศ', 'ส'],\r\n");
          out.write("		        monthNames: ['มกราคม', 'กุมภาพันธ์', 'มีนาคม', 'เมษายน', 'พฤษภาคม', 'มิถุนายน', 'กรกฎาคม', 'สิงหาคม', 'กันยายน', 'ตุลาคม', 'พฤศจิกายน', 'ธันวาคม'],\r\n");
          out.write("		        //monthNamesShort: ['มกราคม', 'กุมภาพันธ์', 'มีนาคม', 'เมษายน', 'พฤษภาคม', 'มิถุนายน', 'กรกฎาคม', 'สิงหาคม', 'กันยายน', 'ตุลาคม', 'พฤศจิกายน', 'ธันวาคม'],\r\n");
          out.write("		        monthNamesShort: ['ม.ค.', 'ก.พ.', 'มี.ค.', 'เม.ย.', 'พ.ค.', 'มิ.ย.', 'ก.ค.', 'ส.ค.', 'ก.ย.', 'ต.ค.', 'พ.ย.', 'ธ.ค.'],\r\n");
          out.write("		        constrainInput: true,	\r\n");
          out.write("		        prevText: 'ก่อนหน้า',\r\n");
          out.write("		        nextText: 'ถัดไป',\r\n");
          out.write("		        yearRange: '-200:+10',\r\n");
          out.write("		        buttonText: 'เลือก',\r\n");
          out.write("		        numberOfMonths: 2\r\n");
          out.write("		    };\r\n");
          out.write(" 			$('.i-calendar').datepicker($.datepicker.isBuddhist);\r\n");
          out.write("			$('.t-calendar').datepicker($.datepicker.twomonth);\r\n");
          out.write("			\r\n");
          out.write("			$( \"#dateStart\" ).datepicker({\r\n");
          out.write("		    	isBuddhist: true,\r\n");
          out.write("				changeMonth: true,\r\n");
          out.write("		        changeYear: true,\r\n");
          out.write("		        buttonImageOnly: false,\r\n");
          out.write("		        dateFormat: 'dd/mm/yy',\r\n");
          out.write("		        dayNames: ['อาทิตย์', 'จันทร์', 'อังคาร', 'พุธ', 'พฤหัสบดี', 'ศุกร์', 'เสาร์'],\r\n");
          out.write("		        dayNamesMin: ['อา', 'จ', 'อ', 'พ', 'พฤ', 'ศ', 'ส'],\r\n");
          out.write("		        monthNames: ['มกราคม', 'กุมภาพันธ์', 'มีนาคม', 'เมษายน', 'พฤษภาคม', 'มิถุนายน', 'กรกฎาคม', 'สิงหาคม', 'กันยายน', 'ตุลาคม', 'พฤศจิกายน', 'ธันวาคม'],\r\n");
          out.write("		        monthNamesShort: ['ม.ค.', 'ก.พ.', 'มี.ค.', 'เม.ย.', 'พ.ค.', 'มิ.ย.', 'ก.ค.', 'ส.ค.', 'ก.ย.', 'ต.ค.', 'พ.ย.', 'ธ.ค.'],\r\n");
          out.write("		        constrainInput: true,	\r\n");
          out.write("		        prevText: 'ก่อนหน้า',\r\n");
          out.write("		        nextText: 'ถัดไป',\r\n");
          out.write("		        yearRange: '-200:+5',\r\n");
          out.write("		        buttonText: 'เลือก',\r\n");
          out.write("		        numberOfMonths: 2,\r\n");
          out.write("		      	onClose: function( selectedDate ) {\r\n");
          out.write("		        	$( \"#dateStop\" ).datepicker( \"option\", \"minDate\", selectedDate );\r\n");
          out.write("		      	}\r\n");
          out.write("		    });\r\n");
          out.write("			\r\n");
          out.write("		    $( \"#dateStop\" ).datepicker({\r\n");
          out.write("		    	isBuddhist: true,\r\n");
          out.write("				changeMonth: true,\r\n");
          out.write("		        changeYear: true,\r\n");
          out.write("		        buttonImageOnly: false,\r\n");
          out.write("		        dateFormat: 'dd/mm/yy',\r\n");
          out.write("		        dayNames: ['อาทิตย์', 'จันทร์', 'อังคาร', 'พุธ', 'พฤหัสบดี', 'ศุกร์', 'เสาร์'],\r\n");
          out.write("		        dayNamesMin: ['อา', 'จ', 'อ', 'พ', 'พฤ', 'ศ', 'ส'],\r\n");
          out.write("		        monthNames: ['มกราคม', 'กุมภาพันธ์', 'มีนาคม', 'เมษายน', 'พฤษภาคม', 'มิถุนายน', 'กรกฎาคม', 'สิงหาคม', 'กันยายน', 'ตุลาคม', 'พฤศจิกายน', 'ธันวาคม'],\r\n");
          out.write("		        monthNamesShort: ['ม.ค.', 'ก.พ.', 'มี.ค.', 'เม.ย.', 'พ.ค.', 'มิ.ย.', 'ก.ค.', 'ส.ค.', 'ก.ย.', 'ต.ค.', 'พ.ย.', 'ธ.ค.'],\r\n");
          out.write("		        constrainInput: true,	\r\n");
          out.write("		        prevText: 'ก่อนหน้า',\r\n");
          out.write("		        nextText: 'ถัดไป',\r\n");
          out.write("		        yearRange: '-200:+5',\r\n");
          out.write("		        buttonText: 'เลือก',\r\n");
          out.write("		        numberOfMonths: 2,\r\n");
          out.write("		      onClose: function( selectedDate ) {\r\n");
          out.write("		        $( \"#dateStart\" ).datepicker( \"option\", \"maxDate\", selectedDate );\r\n");
          out.write("		      }\r\n");
          out.write("		    });\r\n");
          out.write("        });\r\n");
          out.write(" 		\r\n");
          out.write(" 		function showDialogContent(url,title,size){\r\n");
          out.write(" 			\r\n");
          out.write(" 			$.post(url,{}, \r\n");
          out.write(" 				function(results) {	 \r\n");
          out.write(" 				var textAndPic = $('<div id=\"dialogs\">'+results+'</div>');	\r\n");
          out.write(" 				var bootdialog = bootbox.dialog({\r\n");
          out.write(" 				    title: title,\r\n");
          out.write(" 				    message: textAndPic,\r\n");
          out.write(" 				    className: size\r\n");
          out.write(" 				});\r\n");
          out.write(" 				\r\n");
          out.write(" 				$('.selectpicker').selectpicker('refresh');\r\n");
          out.write(" 				\r\n");
          out.write(" 				/* dialog.init(function(){\r\n");
          out.write(" 				    setTimeout(function(){\r\n");
          out.write(" 				        dialog.find('.bootbox-body').html(textAndPic);\r\n");
          out.write(" 				    }, 3000);\r\n");
          out.write(" 				}); */	\r\n");
          out.write(" 				\r\n");
          out.write(" 			});	\r\n");
          out.write(" 		}\r\n");
          out.write(" 		\r\n");
          out.write(" 		function showDialog(url,t,w,h){    		\r\n");
          out.write(" 	        $('#dialogs').dialog({\r\n");
          out.write(" 	        	modal: true,\r\n");
          out.write(" 	        	show: {\r\n");
          out.write(" 					effect: \"fade\",\r\n");
          out.write(" 					duration: 200\r\n");
          out.write(" 				},\r\n");
          out.write(" 	        	title: t,\r\n");
          out.write(" 	            width: w,\r\n");
          out.write(" 	            height: h,\r\n");
          out.write(" 	            closeOnEscape: true,\r\n");
          out.write(" 	            open: function () {\r\n");
          out.write(" 	                $.post(url,{}, \r\n");
          out.write(" 	              	function(results) {	 \r\n");
          out.write(" 	              		$('#dialogs').html(results);	\r\n");
          out.write(" 	              		$('#dialogs').siblings('.ui-dialog-titlebar').find('button').blur(); \r\n");
          out.write(" 	              		\r\n");
          out.write(" 	             	});\r\n");
          out.write(" 	            }\r\n");
          out.write(" 	        });\r\n");
          out.write(" 		}\r\n");
          out.write(" 		\r\n");
          out.write(" 		function showLoadingSwal() {\r\n");
          out.write(" 			swal({\r\n");
          out.write("      		  	title: \"กำลังโหลดข้อมูล...\",\r\n");
          out.write("      		  	imageUrl: '");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/ui/sweetalert/image/entering-comment-loader.gif',\r\n");
          out.write("      			closeOnConfirm: false,\r\n");
          out.write("      			showCancelButton: false,\r\n");
          out.write("      			showConfirmButton: false,\r\n");
          out.write("      		});\r\n");
          out.write(" 		}\r\n");
          out.write(" 		function success() {\r\n");
          out.write(" 	        swal.close()\r\n");
          out.write(" 	    }\r\n");
          out.write("	</script>\r\n");
          out.write("<style type=\"text/css\">\r\n");
          out.write("	.popup-dialog .modal-dialog { width: 700px; }\r\n");
          out.write("	.popuplg-dialog .modal-dialog { width: 1000px; }\r\n");
          out.write("</style>\r\n");
          out.write("</head>");
          out.write("\r\n");
          out.write("\r\n");
          out.write("<style>\r\n");
          out.write(".login-userpic img {\r\n");
          out.write("	width: 100%;\r\n");
          out.write("	height: 100%;\r\n");
          out.write("	-webkit-border-radius: 50% !important;\r\n");
          out.write("	-moz-border-radius: 50% !important;\r\n");
          out.write("	border-radius: 50% !important;\r\n");
          out.write("	border: 2px solid #337ab7;\r\n");
          out.write("}\r\n");
          out.write(".student-dialog .modal-dialog {\r\n");
          out.write("	width: 900px;\r\n");
          out.write("}\r\n");
          out.write(".header {\r\n");
          out.write("	position: fixed;\r\n");
          out.write("	left: 0;\r\n");
          out.write("	right: 0;\r\n");
          out.write("	z-index: 1002;\r\n");
          out.write("	box-shadow: 0 2px 5px rgba(0, 0, 0, 0.176) !important;\r\n");
          out.write("	background-color: #00afda;\r\n");
          out.write("	background: -webkit-linear-gradient(left, #00afda, #1b5dab);\r\n");
          out.write("	background: -o-linear-gradient(right, #00afda, #1b5dab);\r\n");
          out.write("	background: -moz-linear-gradient(right, #00afda, #1b5dab);\r\n");
          out.write("	background: linear-gradient(to right, #00afda, #1b5dab);\r\n");
          out.write("}\r\n");
          out.write("</style>\r\n");
          out.write("<style type=\"text/css\">\r\n");
          out.write("<script src=\"https://example.com/fontawesome/v6.1.1/js/all.js\" data-auto-replace-svg=\"nest\"></script>\r\n");
          out.write("\r\n");
          out.write("</style>\r\n");
          out.write("<nav class=\"navbar navbar-expand-lg navbar-light bg-light \">\r\n");
          out.write("  <!-- Container wrapper -->\r\n");
          out.write("  <div class=\"container\">\r\n");
          out.write("    <!-- Navbar brand -->\r\n");
          out.write("    <!-- Search form -->\r\n");
          out.write("  \r\n");
          out.write("    <!-- Toggle button -->\r\n");
          out.write("    <button class=\"navbar-toggler\" type=\"button\" data-mdb-toggle=\"collapse\"\r\n");
          out.write("      data-mdb-target=\"#navbarSupportedContent\" aria-controls=\"navbarSupportedContent\" aria-expanded=\"false\"\r\n");
          out.write("      aria-label=\"Toggle navigation\">\r\n");
          out.write("      <i class=\"fas fa-bars\"></i>\r\n");
          out.write("    </button>\r\n");
          out.write("\r\n");
          out.write("    <!-- Collapsible wrapper -->\r\n");
          out.write("    <div class=\"collapse navbar-collapse\" id=\"navbarSupportedContent\" style=\"margin-right:30px;\">\r\n");
          out.write("      <!-- Left links -->\r\n");
          out.write("      <ul class=\"navbar-nav ms-auto mb-2 mb-lg-0\">\r\n");
          out.write("        \r\n");
          out.write("        \r\n");
          out.write("        <li class=\"nav-item dropdown\">\r\n");
          out.write("          <a\r\n");
          out.write("            class=\"nav-link dropdown-toggle d-flex align-items-center\"\r\n");
          out.write("            href=\"#\"\r\n");
          out.write("            id=\"navbarDropdownMenuLink\"\r\n");
          out.write("            role=\"button\"\r\n");
          out.write("            data-mdb-toggle=\"dropdown\"\r\n");
          out.write("            aria-expanded=\"false\"\r\n");
          out.write("          >\r\n");
          out.write("            <span class=\"\">");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${SSUser.username}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</span>\r\n");
          out.write("            <img\r\n");
          out.write("              src=\"https://mdbootstrap.com/img/Photos/Avatars/img%20(9).jpg\"\r\n");
          out.write("              class=\"rounded-circle\"\r\n");
          out.write("              height=\"30\"\r\n");
          out.write("              alt=\"\"\r\n");
          out.write("              loading=\"lazy\"\r\n");
          out.write("            />\r\n");
          out.write("          </a>\r\n");
          out.write("          <ul class=\"dropdown-menu\" aria-labelledby=\"navbarDropdownMenuLink\">\r\n");
          out.write("            <li><a class=\"dropdown-item\" href=\"login.htm?mode=initProfile\">My profile</a></li>\r\n");
          out.write("            <li><a class=\"dropdown-item\" href=\"login.htm?mode=initChange\">Change Password</a></li>\r\n");
          out.write("            <li><a class=\"dropdown-item\" href=\"login.htm?mode=index\">Logout</a></li>\r\n");
          out.write("          </ul>\r\n");
          out.write("        </li>\r\n");
          out.write("      </ul>\r\n");
          out.write("      <!-- Left links -->\r\n");
          out.write("    </div>\r\n");
          out.write("    <!-- Collapsible wrapper -->\r\n");
          out.write("  </div>\r\n");
          out.write("  <!-- Container wrapper -->\r\n");
          out.write("</nav>\r\n");
          out.write("	\r\n");
          out.write("<!--header end-->\r\n");
          out.write("\r\n");
          out.write("\r\n");
          out.write("		<section id=\"main-content\">\r\n");
          out.write("		<section class=\"wrapper\">\r\n");
          out.write("         <div>\r\n");
          out.write("         	<h2>รายงานปัญหา</h2>\r\n");
          out.write("         	<label>ชื่อโครงการ</label>\r\n");
          out.write("         	");
          if (_jspx_meth_html_005fselect_005f0(_jspx_th_html_005fform_005f0, _jspx_page_context))
            return true;
          out.write(" \r\n");
          out.write("         </div>\r\n");
          out.write("         \r\n");
          out.write("         <div>\r\n");
          out.write("         	<label>หัวข้อปัญหา</label>\r\n");
          out.write("         	");
          if (_jspx_meth_html_005ftext_005f0(_jspx_th_html_005fform_005f0, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("         </div>\r\n");
          out.write("         \r\n");
          out.write("        <div>\r\n");
          out.write("        <label>Select a file to upload: </label>\r\n");
          out.write("         <input property=\"request_file\" type = \"file\" accept=\".pdf, .png, .jpg, .jpeg\"/>\r\n");
          out.write("        </div>\r\n");
          out.write("        \r\n");
          out.write("        <div>\r\n");
          out.write("        <label>ปัญหาที่เกิด</label>\r\n");
          out.write("         ");
          if (_jspx_meth_html_005ftext_005f1(_jspx_th_html_005fform_005f0, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("        </div>\r\n");
          out.write("         \r\n");
          out.write("         <button class=\"btn-blue btn-sm\" onClick=\"add()\">upload file</button>\r\n");
          out.write("         <button class=\"btn-blue btn-sm\" onclick=\"back()\">back</button>\r\n");
          out.write("         \r\n");
          out.write("         \r\n");
          out.write("		</section>\r\n");
          out.write("		</section>\r\n");
          out.write(" </html>\r\n");
          int evalDoAfterBody = _jspx_th_html_005fform_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_html_005fform_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fhtml_005fform_0026_005fstyleId_005faction.reuse(_jspx_th_html_005fform_005f0);
      _jspx_th_html_005fform_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_html_005fform_005f0, _jsp_getInstanceManager(), _jspx_th_html_005fform_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_html_005fhidden_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_html_005fform_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  html:hidden
    org.apache.struts.taglib.html.HiddenTag _jspx_th_html_005fhidden_005f0 = (org.apache.struts.taglib.html.HiddenTag) _005fjspx_005ftagPool_005fhtml_005fhidden_0026_005fproperty_005fnobody.get(org.apache.struts.taglib.html.HiddenTag.class);
    boolean _jspx_th_html_005fhidden_005f0_reused = false;
    try {
      _jspx_th_html_005fhidden_005f0.setPageContext(_jspx_page_context);
      _jspx_th_html_005fhidden_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_html_005fform_005f0);
      // /page/feature/addRequest.jsp(47,0) name = property type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_html_005fhidden_005f0.setProperty("mode");
      int _jspx_eval_html_005fhidden_005f0 = _jspx_th_html_005fhidden_005f0.doStartTag();
      if (_jspx_th_html_005fhidden_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fhtml_005fhidden_0026_005fproperty_005fnobody.reuse(_jspx_th_html_005fhidden_005f0);
      _jspx_th_html_005fhidden_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_html_005fhidden_005f0, _jsp_getInstanceManager(), _jspx_th_html_005fhidden_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_html_005fselect_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_html_005fform_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  html:select
    org.apache.struts.taglib.html.SelectTag _jspx_th_html_005fselect_005f0 = (org.apache.struts.taglib.html.SelectTag) _005fjspx_005ftagPool_005fhtml_005fselect_0026_005fstyleClass_005fproperty.get(org.apache.struts.taglib.html.SelectTag.class);
    boolean _jspx_th_html_005fselect_005f0_reused = false;
    try {
      _jspx_th_html_005fselect_005f0.setPageContext(_jspx_page_context);
      _jspx_th_html_005fselect_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_html_005fform_005f0);
      // /page/feature/addRequest.jsp(54,10) name = property type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_html_005fselect_005f0.setProperty("id_project");
      // /page/feature/addRequest.jsp(54,10) name = styleClass type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_html_005fselect_005f0.setStyleClass("form-control");
      int _jspx_eval_html_005fselect_005f0 = _jspx_th_html_005fselect_005f0.doStartTag();
      if (_jspx_eval_html_005fselect_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        if (_jspx_eval_html_005fselect_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
          out = org.apache.jasper.runtime.JspRuntimeLibrary.startBufferedBody(_jspx_page_context, _jspx_th_html_005fselect_005f0);
        }
        do {
          out.write("\r\n");
          out.write("         		<option value=\"\" disabled selected>Select your project</option> \r\n");
          out.write("				");
          if (_jspx_meth_html_005foptionsCollection_005f0(_jspx_th_html_005fselect_005f0, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("			");
          int evalDoAfterBody = _jspx_th_html_005fselect_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
        if (_jspx_eval_html_005fselect_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
          out = _jspx_page_context.popBody();
        }
      }
      if (_jspx_th_html_005fselect_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fhtml_005fselect_0026_005fstyleClass_005fproperty.reuse(_jspx_th_html_005fselect_005f0);
      _jspx_th_html_005fselect_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_html_005fselect_005f0, _jsp_getInstanceManager(), _jspx_th_html_005fselect_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_html_005foptionsCollection_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_html_005fselect_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  html:optionsCollection
    org.apache.struts.taglib.html.OptionsCollectionTag _jspx_th_html_005foptionsCollection_005f0 = (org.apache.struts.taglib.html.OptionsCollectionTag) _005fjspx_005ftagPool_005fhtml_005foptionsCollection_0026_005fvalue_005fproperty_005flabel_005fnobody.get(org.apache.struts.taglib.html.OptionsCollectionTag.class);
    boolean _jspx_th_html_005foptionsCollection_005f0_reused = false;
    try {
      _jspx_th_html_005foptionsCollection_005f0.setPageContext(_jspx_page_context);
      _jspx_th_html_005foptionsCollection_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_html_005fselect_005f0);
      // /page/feature/addRequest.jsp(56,4) name = property type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_html_005foptionsCollection_005f0.setProperty("projectList");
      // /page/feature/addRequest.jsp(56,4) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_html_005foptionsCollection_005f0.setValue("id");
      // /page/feature/addRequest.jsp(56,4) name = label type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_html_005foptionsCollection_005f0.setLabel("project_name");
      int _jspx_eval_html_005foptionsCollection_005f0 = _jspx_th_html_005foptionsCollection_005f0.doStartTag();
      if (_jspx_th_html_005foptionsCollection_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fhtml_005foptionsCollection_0026_005fvalue_005fproperty_005flabel_005fnobody.reuse(_jspx_th_html_005foptionsCollection_005f0);
      _jspx_th_html_005foptionsCollection_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_html_005foptionsCollection_005f0, _jsp_getInstanceManager(), _jspx_th_html_005foptionsCollection_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_html_005ftext_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_html_005fform_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  html:text
    org.apache.struts.taglib.html.TextTag _jspx_th_html_005ftext_005f0 = (org.apache.struts.taglib.html.TextTag) _005fjspx_005ftagPool_005fhtml_005ftext_0026_005fstyleId_005fstyleClass_005fproperty_005fplaceHolder_005fonkeypress_005fnobody.get(org.apache.struts.taglib.html.TextTag.class);
    boolean _jspx_th_html_005ftext_005f0_reused = false;
    try {
      _jspx_th_html_005ftext_005f0.setPageContext(_jspx_page_context);
      _jspx_th_html_005ftext_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_html_005fform_005f0);
      // /page/feature/addRequest.jsp(62,10) name = property type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_html_005ftext_005f0.setProperty("request_title");
      // /page/feature/addRequest.jsp(62,10) name = onkeypress type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_html_005ftext_005f0.setOnkeypress("submitEnter();");
      // /page/feature/addRequest.jsp(62,10) name = styleClass type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_html_005ftext_005f0.setStyleClass("form-control");
      // /page/feature/addRequest.jsp(62,10) name = styleId type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_html_005ftext_005f0.setStyleId("title");
      // /page/feature/addRequest.jsp(62,10) name = placeHolder type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_html_005ftext_005f0.setPlaceHolder("หัวข้อปัญหา");
      int _jspx_eval_html_005ftext_005f0 = _jspx_th_html_005ftext_005f0.doStartTag();
      if (_jspx_th_html_005ftext_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fhtml_005ftext_0026_005fstyleId_005fstyleClass_005fproperty_005fplaceHolder_005fonkeypress_005fnobody.reuse(_jspx_th_html_005ftext_005f0);
      _jspx_th_html_005ftext_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_html_005ftext_005f0, _jsp_getInstanceManager(), _jspx_th_html_005ftext_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_html_005ftext_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_html_005fform_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  html:text
    org.apache.struts.taglib.html.TextTag _jspx_th_html_005ftext_005f1 = (org.apache.struts.taglib.html.TextTag) _005fjspx_005ftagPool_005fhtml_005ftext_0026_005fstyleId_005fstyleClass_005fproperty_005fplaceHolder_005fonkeypress_005fnobody.get(org.apache.struts.taglib.html.TextTag.class);
    boolean _jspx_th_html_005ftext_005f1_reused = false;
    try {
      _jspx_th_html_005ftext_005f1.setPageContext(_jspx_page_context);
      _jspx_th_html_005ftext_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_html_005fform_005f0);
      // /page/feature/addRequest.jsp(72,9) name = property type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_html_005ftext_005f1.setProperty("request_remark");
      // /page/feature/addRequest.jsp(72,9) name = onkeypress type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_html_005ftext_005f1.setOnkeypress("submitEnter();");
      // /page/feature/addRequest.jsp(72,9) name = styleClass type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_html_005ftext_005f1.setStyleClass("form-control");
      // /page/feature/addRequest.jsp(72,9) name = styleId type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_html_005ftext_005f1.setStyleId("remark");
      // /page/feature/addRequest.jsp(72,9) name = placeHolder type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_html_005ftext_005f1.setPlaceHolder("ปัญหาที่เกิด");
      int _jspx_eval_html_005ftext_005f1 = _jspx_th_html_005ftext_005f1.doStartTag();
      if (_jspx_th_html_005ftext_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fhtml_005ftext_0026_005fstyleId_005fstyleClass_005fproperty_005fplaceHolder_005fonkeypress_005fnobody.reuse(_jspx_th_html_005ftext_005f1);
      _jspx_th_html_005ftext_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_html_005ftext_005f1, _jsp_getInstanceManager(), _jspx_th_html_005ftext_005f1_reused);
    }
    return false;
  }
}
