/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.64
 * Generated at: 2565-08-02 06:51:52 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.page.feature;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class addRequest_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(7);
    _jspx_dependants.put("/page/inc_header.jsp", Long.valueOf(1658809064641L));
    _jspx_dependants.put("/WEB-INF/tld/fn.tld", Long.valueOf(1655975438917L));
    _jspx_dependants.put("/WEB-INF/tld/struts-bean.tld", Long.valueOf(1655975438920L));
    _jspx_dependants.put("/page/inc_header_script.jsp", Long.valueOf(1659407833651L));
    _jspx_dependants.put("/WEB-INF/tld/struts-html.tld", Long.valueOf(1655975438921L));
    _jspx_dependants.put("/WEB-INF/tld/c.tld", Long.valueOf(1655975438913L));
    _jspx_dependants.put("/WEB-INF/tld/struts-logic.tld", Long.valueOf(1655975438922L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fhtml_005fform_0026_005fstyleId_005faction;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fhtml_005fhidden_0026_005fproperty_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fhtml_005ftext_0026_005fstyleId_005fstyleClass_005fproperty_005fplaceHolder_005fonkeypress_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fhtml_005fform_0026_005fstyleId_005faction = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fhtml_005fhidden_0026_005fproperty_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fhtml_005ftext_0026_005fstyleId_005fstyleClass_005fproperty_005fplaceHolder_005fonkeypress_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fhtml_005fform_0026_005fstyleId_005faction.release();
    _005fjspx_005ftagPool_005fhtml_005fhidden_0026_005fproperty_005fnobody.release();
    _005fjspx_005ftagPool_005fhtml_005ftext_0026_005fstyleId_005fstyleClass_005fproperty_005fplaceHolder_005fonkeypress_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\n");
      out.write("\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("	<meta charset=\"utf-8\">\n");
      out.write("	<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("	<meta name=\"description\" content=\"\">\n");
      out.write("	<meta name=\"author\" content=\"\">\n");
      out.write("	<meta name=\"keyword\" content=\"\">\n");
      out.write("	\n");
      out.write("	<title>รายงานปัญหา</title>\n");
      out.write("	\n");
      out.write("	\n");
      out.write("	\n");
      out.write("	<script src=\"//cdn.jsdelivr.net/npm/sweetalert2@11\"></script>\n");
      out.write("	<!-- Font Awesome -->\n");
      out.write("	<link\n");
      out.write("	  href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css\"\n");
      out.write("	  rel=\"stylesheet\"\n");
      out.write("	/>\n");
      out.write("	<!-- Google Fonts -->\n");
      out.write("	<link\n");
      out.write("	  href=\"https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap\"\n");
      out.write("	  rel=\"stylesheet\"\n");
      out.write("	/>\n");
      out.write("	<!-- MDB -->\n");
      out.write("	<link\n");
      out.write("	  href=\"https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/4.2.0/mdb.min.css\"\n");
      out.write("	  rel=\"stylesheet\"\n");
      out.write("	/>\n");
      out.write("	<!-- MDB -->\n");
      out.write("	<script\n");
      out.write("	  type=\"text/javascript\"\n");
      out.write("	  src=\"https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/4.2.0/mdb.min.js\"\n");
      out.write("	></script>\n");
      out.write("	<!-- Bootstrap CSS -->\n");
      out.write("	<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/ui/css/bootstrap.min.css\" rel=\"stylesheet\"/>\n");
      out.write("	<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/ui/css/bootstrap-theme.css\" rel=\"stylesheet\"/>\n");
      out.write("	<!-- CSS only -->\n");
      out.write("	<link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css\" rel=\"stylesheet\" integrity=\"sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor\" crossorigin=\"anonymous\">\n");
      out.write("	<!-- font -->\n");
      out.write("	<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/ui/fonts/webfont.css\" rel=\"stylesheet\" />\n");
      out.write("	<!-- font icon -->\n");
      out.write("	<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/ui/css/elegant-icons-style.css\" rel=\"stylesheet\" />\n");
      out.write("	<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/ui/css/font-awesome.min.css\" rel=\"stylesheet\" />\n");
      out.write("	<!-- datatable -->\n");
      out.write("	<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/ui/css/dataTables.bootstrap.css\" rel=\"stylesheet\"/>\n");
      out.write("	<!-- Custom styles -->\n");
      out.write("	<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/ui/css/style.css\" rel=\"stylesheet\"/>\n");
      out.write("	<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/ui/css/style-responsive.css\" rel=\"stylesheet\" />\n");
      out.write("	<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/ui/css/jquery-ui-10.12.1.css\" rel=\"stylesheet\"/>\n");
      out.write("	<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/ui/css/style-button.css\" rel=\"stylesheet\"/>\n");
      out.write("	<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/ui/css/bootstrap-select.css\" rel=\"stylesheet\"/>\n");
      out.write("	<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/ui/css/materialize-color.css\" rel=\"stylesheet\"/>\n");
      out.write("	<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/ui/sweetalert/css/sweetalert.css\" rel=\"stylesheet\"/>\n");
      out.write("\n");
      out.write("	<!-- javascripts -->\n");
      out.write("	<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/ui/js/jquery-1.12.4.js\"></script>\n");
      out.write("	<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/ui/js/jquery-ui-1.10.4.min.js\"></script>\n");
      out.write("	<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/ui/js/jquery-1.8.3.min.js\"></script>\n");
      out.write("	<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/ui/js/jquery-ui-1.9.2.custom.min.js\" type=\"text/javascript\"></script>\n");
      out.write("	<!-- for set format thai -->\n");
      out.write("	<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/ui/js/jquery.ui.1.8.10.offset.datepicker.min.js\" type=\"text/javascript\"></script>\n");
      out.write("	\n");
      out.write("	<!-- bootstrap -->\n");
      out.write("	<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/ui/js/bootstrap.min.js\"></script>\n");
      out.write("	<!-- nice scroll -->\n");
      out.write("	<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/ui/js/jquery.scrollTo.min.js\"></script>\n");
      out.write("	<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/ui/js/jquery.nicescroll.js\" type=\"text/javascript\"></script>\n");
      out.write("	<!-- custom select -->\n");
      out.write("	<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/ui/js/jquery.customSelect.min.js\"></script>\n");
      out.write("	<!-- JavaScript Bundle with Popper -->\n");
      out.write("	<!--custome script for all page-->\n");
      out.write("	<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/ui/js/scripts.js\"></script>\n");
      out.write("	\n");
      out.write("	<!-- custom script for this page-->\n");
      out.write("	<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/ui/js/jquery.autosize.min.js\"></script>\n");
      out.write("	<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/ui/js/jquery.placeholder.min.js\"></script>\n");
      out.write("	<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/ui/js/jquery.slimscroll.min.js\"></script>\n");
      out.write("	<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/ui/js/bootbox.js\"></script>\n");
      out.write("\n");
      out.write("	<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/ui/js/bootstrap-select.js\"></script>\n");
      out.write("	<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/ui/js/bootstrap-typeahead.js\"></script>\n");
      out.write("	\n");
      out.write("	<!-- datatable -->\n");
      out.write("	<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/ui/js/jquery.dataTables.js\" type=\"text/javascript\"></script>\n");
      out.write("	<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/ui/js/dataTables.bootstrap.js\" type=\"text/javascript\"></script>\n");
      out.write("	\n");
      out.write("	<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/ui/js/jquery.validate.min.js\" type=\"text/javascript\"></script>\n");
      out.write("	<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/ui/js/quotwaiting-forquot-modal-dialog.js\" type=\"text/javascript\"></script>\n");
      out.write("	<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/ui/sweetalert/js/sweetalert.min.js\" type=\"text/javascript\"></script>\n");
      out.write("	\n");
      out.write("	<script type=\"text/javascript\">\n");
      out.write(" 		$(document).ready(function () {\n");
      out.write(" 			\n");
      out.write(" 			$(\"#msgSuccess\").delay(800).fadeOut(1000);\n");
      out.write(" 			$(\"#msgWarning\").delay(800).fadeOut(1000);\n");
      out.write(" 			\n");
      out.write("			try {\n");
      out.write("				var variables = {};\n");
      out.write("		      	variables = {\n");
      out.write("						\"sProcessing\": \"กำลังดำเนินการ...\",\n");
      out.write("						\"sLengthMenu\": \"แสดง _MENU_  แถว\",\n");
      out.write("						\"sZeroRecords\": \"ไม่พบข้อมูล\",\n");
      out.write("						\"sInfo\": \"แสดง _START_ ถึง _END_ จาก _TOTAL_ แถว\",\n");
      out.write("						\"sInfoEmpty\": \"แสดง 0 ถึง 0 จาก 0 แถว\",\n");
      out.write("						\"sInfoFiltered\": \"(กรองข้อมูล _MAX_ ทุกแถว)\",\n");
      out.write("						\"sInfoPostFix\": \"\",\n");
      out.write("						\"sSearch\": \"ค้นหา: \",\n");
      out.write("						\"sUrl\": \"\",\n");
      out.write("						\"oPaginate\": {\n");
      out.write("						    \"sFirst\": \"เริ่มต้น\",\n");
      out.write("						    \"sPrevious\": \"ก่อนหน้า\",\n");
      out.write("						    \"sNext\": \"ถัดไป\",\n");
      out.write("						    \"sLast\": \"สุดท้าย\"\n");
      out.write("						}\n");
      out.write("				};\n");
      out.write("			\n");
      out.write("				var options = { \"aoColumnDefs\": [{ bSortable: false, aTargets: ['no-sort'] }],\"oLanguage\": variables};\n");
      out.write("				var optionsHundred = { \"aoColumnDefs\": [{ bSortable: false, aTargets: ['no-sort'] }],\"iDisplayLength\": 100,\"oLanguage\": variables};\n");
      out.write("				var optionsFive = { \"aoColumnDefs\": [{ bSortable: false, aTargets: ['no-sort'] }],\"iDisplayLength\": 5,\"oLanguage\": variables};\n");
      out.write("			\n");
      out.write("				$(\".grid-default\").dataTable(options);\n");
      out.write("				$(\".grid-hundred\").dataTable(optionsHundred);\n");
      out.write("				$(\".grid-five\").dataTable(optionsFive);\n");
      out.write("			} catch (e) {\n");
      out.write("			}\n");
      out.write("			\n");
      out.write("			$.datepicker.isBuddhist ={\n");
      out.write("				isBuddhist: true,\n");
      out.write("				changeMonth: true,\n");
      out.write("		        changeYear: true,\n");
      out.write("		        buttonImageOnly: false,\n");
      out.write("		        dateFormat: 'dd/mm/yy',\n");
      out.write("		        dayNames: ['อาทิตย์', 'จันทร์', 'อังคาร', 'พุธ', 'พฤหัสบดี', 'ศุกร์', 'เสาร์'],\n");
      out.write("		        dayNamesMin: ['อา', 'จ', 'อ', 'พ', 'พฤ', 'ศ', 'ส'],\n");
      out.write("		        monthNames: ['มกราคม', 'กุมภาพันธ์', 'มีนาคม', 'เมษายน', 'พฤษภาคม', 'มิถุนายน', 'กรกฎาคม', 'สิงหาคม', 'กันยายน', 'ตุลาคม', 'พฤศจิกายน', 'ธันวาคม'],\n");
      out.write("		        //monthNamesShort: ['มกราคม', 'กุมภาพันธ์', 'มีนาคม', 'เมษายน', 'พฤษภาคม', 'มิถุนายน', 'กรกฎาคม', 'สิงหาคม', 'กันยายน', 'ตุลาคม', 'พฤศจิกายน', 'ธันวาคม'],\n");
      out.write("		        monthNamesShort: ['ม.ค.', 'ก.พ.', 'มี.ค.', 'เม.ย.', 'พ.ค.', 'มิ.ย.', 'ก.ค.', 'ส.ค.', 'ก.ย.', 'ต.ค.', 'พ.ย.', 'ธ.ค.'],\n");
      out.write("		        constrainInput: true,	\n");
      out.write("		        prevText: 'ก่อนหน้า',\n");
      out.write("		        nextText: 'ถัดไป',\n");
      out.write("		        yearRange: '-200:+10',\n");
      out.write("		        buttonText: 'เลือก'\n");
      out.write("		    };\n");
      out.write("			\n");
      out.write("			$.datepicker.twomonth ={\n");
      out.write("				isBuddhist: true,\n");
      out.write("				changeMonth: false,\n");
      out.write("		        changeYear: false,\n");
      out.write("		        buttonImageOnly: false,\n");
      out.write("		        dateFormat: 'dd/mm/yy',\n");
      out.write("		        dayNames: ['อาทิตย์', 'จันทร์', 'อังคาร', 'พุธ', 'พฤหัสบดี', 'ศุกร์', 'เสาร์'],\n");
      out.write("		        dayNamesMin: ['อา', 'จ', 'อ', 'พ', 'พฤ', 'ศ', 'ส'],\n");
      out.write("		        monthNames: ['มกราคม', 'กุมภาพันธ์', 'มีนาคม', 'เมษายน', 'พฤษภาคม', 'มิถุนายน', 'กรกฎาคม', 'สิงหาคม', 'กันยายน', 'ตุลาคม', 'พฤศจิกายน', 'ธันวาคม'],\n");
      out.write("		        //monthNamesShort: ['มกราคม', 'กุมภาพันธ์', 'มีนาคม', 'เมษายน', 'พฤษภาคม', 'มิถุนายน', 'กรกฎาคม', 'สิงหาคม', 'กันยายน', 'ตุลาคม', 'พฤศจิกายน', 'ธันวาคม'],\n");
      out.write("		        monthNamesShort: ['ม.ค.', 'ก.พ.', 'มี.ค.', 'เม.ย.', 'พ.ค.', 'มิ.ย.', 'ก.ค.', 'ส.ค.', 'ก.ย.', 'ต.ค.', 'พ.ย.', 'ธ.ค.'],\n");
      out.write("		        constrainInput: true,	\n");
      out.write("		        prevText: 'ก่อนหน้า',\n");
      out.write("		        nextText: 'ถัดไป',\n");
      out.write("		        yearRange: '-200:+10',\n");
      out.write("		        buttonText: 'เลือก',\n");
      out.write("		        numberOfMonths: 2\n");
      out.write("		    };\n");
      out.write(" 			$('.i-calendar').datepicker($.datepicker.isBuddhist);\n");
      out.write("			$('.t-calendar').datepicker($.datepicker.twomonth);\n");
      out.write("			\n");
      out.write("			$( \"#dateStart\" ).datepicker({\n");
      out.write("		    	isBuddhist: true,\n");
      out.write("				changeMonth: true,\n");
      out.write("		        changeYear: true,\n");
      out.write("		        buttonImageOnly: false,\n");
      out.write("		        dateFormat: 'dd/mm/yy',\n");
      out.write("		        dayNames: ['อาทิตย์', 'จันทร์', 'อังคาร', 'พุธ', 'พฤหัสบดี', 'ศุกร์', 'เสาร์'],\n");
      out.write("		        dayNamesMin: ['อา', 'จ', 'อ', 'พ', 'พฤ', 'ศ', 'ส'],\n");
      out.write("		        monthNames: ['มกราคม', 'กุมภาพันธ์', 'มีนาคม', 'เมษายน', 'พฤษภาคม', 'มิถุนายน', 'กรกฎาคม', 'สิงหาคม', 'กันยายน', 'ตุลาคม', 'พฤศจิกายน', 'ธันวาคม'],\n");
      out.write("		        monthNamesShort: ['ม.ค.', 'ก.พ.', 'มี.ค.', 'เม.ย.', 'พ.ค.', 'มิ.ย.', 'ก.ค.', 'ส.ค.', 'ก.ย.', 'ต.ค.', 'พ.ย.', 'ธ.ค.'],\n");
      out.write("		        constrainInput: true,	\n");
      out.write("		        prevText: 'ก่อนหน้า',\n");
      out.write("		        nextText: 'ถัดไป',\n");
      out.write("		        yearRange: '-200:+5',\n");
      out.write("		        buttonText: 'เลือก',\n");
      out.write("		        numberOfMonths: 2,\n");
      out.write("		      	onClose: function( selectedDate ) {\n");
      out.write("		        	$( \"#dateStop\" ).datepicker( \"option\", \"minDate\", selectedDate );\n");
      out.write("		      	}\n");
      out.write("		    });\n");
      out.write("			\n");
      out.write("		    $( \"#dateStop\" ).datepicker({\n");
      out.write("		    	isBuddhist: true,\n");
      out.write("				changeMonth: true,\n");
      out.write("		        changeYear: true,\n");
      out.write("		        buttonImageOnly: false,\n");
      out.write("		        dateFormat: 'dd/mm/yy',\n");
      out.write("		        dayNames: ['อาทิตย์', 'จันทร์', 'อังคาร', 'พุธ', 'พฤหัสบดี', 'ศุกร์', 'เสาร์'],\n");
      out.write("		        dayNamesMin: ['อา', 'จ', 'อ', 'พ', 'พฤ', 'ศ', 'ส'],\n");
      out.write("		        monthNames: ['มกราคม', 'กุมภาพันธ์', 'มีนาคม', 'เมษายน', 'พฤษภาคม', 'มิถุนายน', 'กรกฎาคม', 'สิงหาคม', 'กันยายน', 'ตุลาคม', 'พฤศจิกายน', 'ธันวาคม'],\n");
      out.write("		        monthNamesShort: ['ม.ค.', 'ก.พ.', 'มี.ค.', 'เม.ย.', 'พ.ค.', 'มิ.ย.', 'ก.ค.', 'ส.ค.', 'ก.ย.', 'ต.ค.', 'พ.ย.', 'ธ.ค.'],\n");
      out.write("		        constrainInput: true,	\n");
      out.write("		        prevText: 'ก่อนหน้า',\n");
      out.write("		        nextText: 'ถัดไป',\n");
      out.write("		        yearRange: '-200:+5',\n");
      out.write("		        buttonText: 'เลือก',\n");
      out.write("		        numberOfMonths: 2,\n");
      out.write("		      onClose: function( selectedDate ) {\n");
      out.write("		        $( \"#dateStart\" ).datepicker( \"option\", \"maxDate\", selectedDate );\n");
      out.write("		      }\n");
      out.write("		    });\n");
      out.write("        });\n");
      out.write(" 		\n");
      out.write(" 		function showDialogContent(url,title,size){\n");
      out.write(" 			\n");
      out.write(" 			$.post(url,{}, \n");
      out.write(" 				function(results) {	 \n");
      out.write(" 				var textAndPic = $('<div id=\"dialogs\">'+results+'</div>');	\n");
      out.write(" 				var bootdialog = bootbox.dialog({\n");
      out.write(" 				    title: title,\n");
      out.write(" 				    message: textAndPic,\n");
      out.write(" 				    className: size\n");
      out.write(" 				});\n");
      out.write(" 				\n");
      out.write(" 				$('.selectpicker').selectpicker('refresh');\n");
      out.write(" 				\n");
      out.write(" 				/* dialog.init(function(){\n");
      out.write(" 				    setTimeout(function(){\n");
      out.write(" 				        dialog.find('.bootbox-body').html(textAndPic);\n");
      out.write(" 				    }, 3000);\n");
      out.write(" 				}); */	\n");
      out.write(" 				\n");
      out.write(" 			});	\n");
      out.write(" 		}\n");
      out.write(" 		\n");
      out.write(" 		function showDialog(url,t,w,h){    		\n");
      out.write(" 	        $('#dialogs').dialog({\n");
      out.write(" 	        	modal: true,\n");
      out.write(" 	        	show: {\n");
      out.write(" 					effect: \"fade\",\n");
      out.write(" 					duration: 200\n");
      out.write(" 				},\n");
      out.write(" 	        	title: t,\n");
      out.write(" 	            width: w,\n");
      out.write(" 	            height: h,\n");
      out.write(" 	            closeOnEscape: true,\n");
      out.write(" 	            open: function () {\n");
      out.write(" 	                $.post(url,{}, \n");
      out.write(" 	              	function(results) {	 \n");
      out.write(" 	              		$('#dialogs').html(results);	\n");
      out.write(" 	              		$('#dialogs').siblings('.ui-dialog-titlebar').find('button').blur(); \n");
      out.write(" 	              		\n");
      out.write("\n");
      out.write(" 	             	});\n");
      out.write(" 	            }\n");
      out.write(" 	        });\n");
      out.write(" 		}\n");
      out.write(" 		\n");
      out.write(" 		function showLoadingSwal() {\n");
      out.write(" 			swal({\n");
      out.write("      		  	title: \"กำลังโหลดข้อมูล...\",\n");
      out.write("      		  	imageUrl: '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/ui/sweetalert/image/entering-comment-loader.gif',\n");
      out.write("      			closeOnConfirm: false,\n");
      out.write("      			showCancelButton: false,\n");
      out.write("      			showConfirmButton: false,\n");
      out.write("      		});\n");
      out.write(" 		}\n");
      out.write(" 		function success() {\n");
      out.write(" 	        swal.close()\n");
      out.write(" 	    }\n");
      out.write("	</script>\n");
      out.write("<style type=\"text/css\">\n");
      out.write("	.popup-dialog .modal-dialog { width: 700px; }\n");
      out.write("	.popuplg-dialog .modal-dialog { width: 1000px; }\n");
      out.write("</style>\n");
      out.write("</head>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script src=\"//cdn.jsdelivr.net/npm/sweetalert2@11\"></script>\r\n");
      out.write("\r\n");
      out.write("<script language=\"javascript\" type=\"text/javascript\">\r\n");
      out.write("\r\n");
      out.write("	function add() {\r\n");
      out.write("		Swal.fire({\r\n");
      out.write("			  title: 'Are you sure?',\r\n");
      out.write("			  text: \"You want to logout!\",\r\n");
      out.write("			  icon: 'warning',\r\n");
      out.write("			  showCancelButton: true,\r\n");
      out.write("			  confirmButtonColor: '#3085d6',\r\n");
      out.write("			  cancelButtonColor: '#d33',\r\n");
      out.write("			  confirmButtonText: 'Yes'\r\n");
      out.write("			}).then((result) => {\r\n");
      out.write("				if(result.isConfirmed){\r\n");
      out.write("					document.forms[0].mode.value = \"addRequest\";\r\n");
      out.write("					document.forms[0].submit();\r\n");
      out.write("				}\r\n");
      out.write("			    \r\n");
      out.write("			  })\r\n");
      out.write("		\r\n");
      out.write("	}\r\n");
      out.write("	function back() {\r\n");
      out.write("		document.forms[0].mode.value = \"getRequest\";\r\n");
      out.write("		document.forms[0].submit();\r\n");
      out.write("	}\r\n");
      out.write("	function submitEnter() {\r\n");
      out.write("		if (checkKeyEnter() == true) submitFormLogin();\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	function checkKeyEnter(){\r\n");
      out.write("		   if(event.keyCode==13) return true;\r\n");
      out.write("	}\r\n");
      out.write("		\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      if (_jspx_meth_html_005fform_005f0(_jspx_page_context))
        return;
      out.write("   \r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_html_005fform_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  html:form
    org.apache.struts.taglib.html.FormTag _jspx_th_html_005fform_005f0 = (org.apache.struts.taglib.html.FormTag) _005fjspx_005ftagPool_005fhtml_005fform_0026_005fstyleId_005faction.get(org.apache.struts.taglib.html.FormTag.class);
    boolean _jspx_th_html_005fform_005f0_reused = false;
    try {
      _jspx_th_html_005fform_005f0.setPageContext(_jspx_page_context);
      _jspx_th_html_005fform_005f0.setParent(null);
      // /page/feature/addRequest.jsp(47,0) name = action type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_html_005fform_005f0.setAction("/index");
      // /page/feature/addRequest.jsp(47,0) name = styleId type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_html_005fform_005f0.setStyleId("eduForm");
      int _jspx_eval_html_005fform_005f0 = _jspx_th_html_005fform_005f0.doStartTag();
      if (_jspx_eval_html_005fform_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write('\r');
          out.write('\n');
          if (_jspx_meth_html_005fhidden_005f0(_jspx_th_html_005fform_005f0, _jspx_page_context))
            return true;
          out.write('\r');
          out.write('\n');
          out.write('	');
          out.write("\n");
          out.write("\n");
          out.write("\n");
          out.write("\n");
          out.write("\n");
          out.write("\n");
          out.write("\n");
          out.write("\n");
          out.write("<html>\n");
          out.write("<head>\n");
          out.write("	<meta charset=\"utf-8\">\n");
          out.write("	<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
          out.write("	<meta name=\"description\" content=\"\">\n");
          out.write("	<meta name=\"author\" content=\"\">\n");
          out.write("	<meta name=\"keyword\" content=\"\">\n");
          out.write("	\n");
          out.write("	<title>รายงานปัญหา</title>\n");
          out.write("	\n");
          out.write("	\n");
          out.write("	\n");
          out.write("	<script src=\"//cdn.jsdelivr.net/npm/sweetalert2@11\"></script>\n");
          out.write("	<!-- Font Awesome -->\n");
          out.write("	<link\n");
          out.write("	  href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css\"\n");
          out.write("	  rel=\"stylesheet\"\n");
          out.write("	/>\n");
          out.write("	<!-- Google Fonts -->\n");
          out.write("	<link\n");
          out.write("	  href=\"https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap\"\n");
          out.write("	  rel=\"stylesheet\"\n");
          out.write("	/>\n");
          out.write("	<!-- MDB -->\n");
          out.write("	<link\n");
          out.write("	  href=\"https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/4.2.0/mdb.min.css\"\n");
          out.write("	  rel=\"stylesheet\"\n");
          out.write("	/>\n");
          out.write("	<!-- MDB -->\n");
          out.write("	<script\n");
          out.write("	  type=\"text/javascript\"\n");
          out.write("	  src=\"https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/4.2.0/mdb.min.js\"\n");
          out.write("	></script>\n");
          out.write("	<!-- Bootstrap CSS -->\n");
          out.write("	<link href=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/ui/css/bootstrap.min.css\" rel=\"stylesheet\"/>\n");
          out.write("	<link href=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/ui/css/bootstrap-theme.css\" rel=\"stylesheet\"/>\n");
          out.write("	<!-- CSS only -->\n");
          out.write("	<link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css\" rel=\"stylesheet\" integrity=\"sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor\" crossorigin=\"anonymous\">\n");
          out.write("	<!-- font -->\n");
          out.write("	<link href=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/ui/fonts/webfont.css\" rel=\"stylesheet\" />\n");
          out.write("	<!-- font icon -->\n");
          out.write("	<link href=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/ui/css/elegant-icons-style.css\" rel=\"stylesheet\" />\n");
          out.write("	<link href=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/ui/css/font-awesome.min.css\" rel=\"stylesheet\" />\n");
          out.write("	<!-- datatable -->\n");
          out.write("	<link href=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/ui/css/dataTables.bootstrap.css\" rel=\"stylesheet\"/>\n");
          out.write("	<!-- Custom styles -->\n");
          out.write("	<link href=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/ui/css/style.css\" rel=\"stylesheet\"/>\n");
          out.write("	<link href=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/ui/css/style-responsive.css\" rel=\"stylesheet\" />\n");
          out.write("	<link href=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/ui/css/jquery-ui-10.12.1.css\" rel=\"stylesheet\"/>\n");
          out.write("	<link href=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/ui/css/style-button.css\" rel=\"stylesheet\"/>\n");
          out.write("	<link href=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/ui/css/bootstrap-select.css\" rel=\"stylesheet\"/>\n");
          out.write("	<link href=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/ui/css/materialize-color.css\" rel=\"stylesheet\"/>\n");
          out.write("	<link href=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/ui/sweetalert/css/sweetalert.css\" rel=\"stylesheet\"/>\n");
          out.write("\n");
          out.write("	<!-- javascripts -->\n");
          out.write("	<script src=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/ui/js/jquery-1.12.4.js\"></script>\n");
          out.write("	<script src=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/ui/js/jquery-ui-1.10.4.min.js\"></script>\n");
          out.write("	<script src=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/ui/js/jquery-1.8.3.min.js\"></script>\n");
          out.write("	<script src=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/ui/js/jquery-ui-1.9.2.custom.min.js\" type=\"text/javascript\"></script>\n");
          out.write("	<!-- for set format thai -->\n");
          out.write("	<script src=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/ui/js/jquery.ui.1.8.10.offset.datepicker.min.js\" type=\"text/javascript\"></script>\n");
          out.write("	\n");
          out.write("	<!-- bootstrap -->\n");
          out.write("	<script src=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/ui/js/bootstrap.min.js\"></script>\n");
          out.write("	<!-- nice scroll -->\n");
          out.write("	<script src=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/ui/js/jquery.scrollTo.min.js\"></script>\n");
          out.write("	<script src=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/ui/js/jquery.nicescroll.js\" type=\"text/javascript\"></script>\n");
          out.write("	<!-- custom select -->\n");
          out.write("	<script src=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/ui/js/jquery.customSelect.min.js\"></script>\n");
          out.write("	<!-- JavaScript Bundle with Popper -->\n");
          out.write("	<!--custome script for all page-->\n");
          out.write("	<script src=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/ui/js/scripts.js\"></script>\n");
          out.write("	\n");
          out.write("	<!-- custom script for this page-->\n");
          out.write("	<script src=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/ui/js/jquery.autosize.min.js\"></script>\n");
          out.write("	<script src=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/ui/js/jquery.placeholder.min.js\"></script>\n");
          out.write("	<script src=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/ui/js/jquery.slimscroll.min.js\"></script>\n");
          out.write("	<script src=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/ui/js/bootbox.js\"></script>\n");
          out.write("\n");
          out.write("	<script src=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/ui/js/bootstrap-select.js\"></script>\n");
          out.write("	<script src=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/ui/js/bootstrap-typeahead.js\"></script>\n");
          out.write("	\n");
          out.write("	<!-- datatable -->\n");
          out.write("	<script src=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/ui/js/jquery.dataTables.js\" type=\"text/javascript\"></script>\n");
          out.write("	<script src=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/ui/js/dataTables.bootstrap.js\" type=\"text/javascript\"></script>\n");
          out.write("	\n");
          out.write("	<script src=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/ui/js/jquery.validate.min.js\" type=\"text/javascript\"></script>\n");
          out.write("	<script src=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/ui/js/quotwaiting-forquot-modal-dialog.js\" type=\"text/javascript\"></script>\n");
          out.write("	<script src=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/ui/sweetalert/js/sweetalert.min.js\" type=\"text/javascript\"></script>\n");
          out.write("	\n");
          out.write("	<script type=\"text/javascript\">\n");
          out.write(" 		$(document).ready(function () {\n");
          out.write(" 			\n");
          out.write(" 			$(\"#msgSuccess\").delay(800).fadeOut(1000);\n");
          out.write(" 			$(\"#msgWarning\").delay(800).fadeOut(1000);\n");
          out.write(" 			\n");
          out.write("			try {\n");
          out.write("				var variables = {};\n");
          out.write("		      	variables = {\n");
          out.write("						\"sProcessing\": \"กำลังดำเนินการ...\",\n");
          out.write("						\"sLengthMenu\": \"แสดง _MENU_  แถว\",\n");
          out.write("						\"sZeroRecords\": \"ไม่พบข้อมูล\",\n");
          out.write("						\"sInfo\": \"แสดง _START_ ถึง _END_ จาก _TOTAL_ แถว\",\n");
          out.write("						\"sInfoEmpty\": \"แสดง 0 ถึง 0 จาก 0 แถว\",\n");
          out.write("						\"sInfoFiltered\": \"(กรองข้อมูล _MAX_ ทุกแถว)\",\n");
          out.write("						\"sInfoPostFix\": \"\",\n");
          out.write("						\"sSearch\": \"ค้นหา: \",\n");
          out.write("						\"sUrl\": \"\",\n");
          out.write("						\"oPaginate\": {\n");
          out.write("						    \"sFirst\": \"เริ่มต้น\",\n");
          out.write("						    \"sPrevious\": \"ก่อนหน้า\",\n");
          out.write("						    \"sNext\": \"ถัดไป\",\n");
          out.write("						    \"sLast\": \"สุดท้าย\"\n");
          out.write("						}\n");
          out.write("				};\n");
          out.write("			\n");
          out.write("				var options = { \"aoColumnDefs\": [{ bSortable: false, aTargets: ['no-sort'] }],\"oLanguage\": variables};\n");
          out.write("				var optionsHundred = { \"aoColumnDefs\": [{ bSortable: false, aTargets: ['no-sort'] }],\"iDisplayLength\": 100,\"oLanguage\": variables};\n");
          out.write("				var optionsFive = { \"aoColumnDefs\": [{ bSortable: false, aTargets: ['no-sort'] }],\"iDisplayLength\": 5,\"oLanguage\": variables};\n");
          out.write("			\n");
          out.write("				$(\".grid-default\").dataTable(options);\n");
          out.write("				$(\".grid-hundred\").dataTable(optionsHundred);\n");
          out.write("				$(\".grid-five\").dataTable(optionsFive);\n");
          out.write("			} catch (e) {\n");
          out.write("			}\n");
          out.write("			\n");
          out.write("			$.datepicker.isBuddhist ={\n");
          out.write("				isBuddhist: true,\n");
          out.write("				changeMonth: true,\n");
          out.write("		        changeYear: true,\n");
          out.write("		        buttonImageOnly: false,\n");
          out.write("		        dateFormat: 'dd/mm/yy',\n");
          out.write("		        dayNames: ['อาทิตย์', 'จันทร์', 'อังคาร', 'พุธ', 'พฤหัสบดี', 'ศุกร์', 'เสาร์'],\n");
          out.write("		        dayNamesMin: ['อา', 'จ', 'อ', 'พ', 'พฤ', 'ศ', 'ส'],\n");
          out.write("		        monthNames: ['มกราคม', 'กุมภาพันธ์', 'มีนาคม', 'เมษายน', 'พฤษภาคม', 'มิถุนายน', 'กรกฎาคม', 'สิงหาคม', 'กันยายน', 'ตุลาคม', 'พฤศจิกายน', 'ธันวาคม'],\n");
          out.write("		        //monthNamesShort: ['มกราคม', 'กุมภาพันธ์', 'มีนาคม', 'เมษายน', 'พฤษภาคม', 'มิถุนายน', 'กรกฎาคม', 'สิงหาคม', 'กันยายน', 'ตุลาคม', 'พฤศจิกายน', 'ธันวาคม'],\n");
          out.write("		        monthNamesShort: ['ม.ค.', 'ก.พ.', 'มี.ค.', 'เม.ย.', 'พ.ค.', 'มิ.ย.', 'ก.ค.', 'ส.ค.', 'ก.ย.', 'ต.ค.', 'พ.ย.', 'ธ.ค.'],\n");
          out.write("		        constrainInput: true,	\n");
          out.write("		        prevText: 'ก่อนหน้า',\n");
          out.write("		        nextText: 'ถัดไป',\n");
          out.write("		        yearRange: '-200:+10',\n");
          out.write("		        buttonText: 'เลือก'\n");
          out.write("		    };\n");
          out.write("			\n");
          out.write("			$.datepicker.twomonth ={\n");
          out.write("				isBuddhist: true,\n");
          out.write("				changeMonth: false,\n");
          out.write("		        changeYear: false,\n");
          out.write("		        buttonImageOnly: false,\n");
          out.write("		        dateFormat: 'dd/mm/yy',\n");
          out.write("		        dayNames: ['อาทิตย์', 'จันทร์', 'อังคาร', 'พุธ', 'พฤหัสบดี', 'ศุกร์', 'เสาร์'],\n");
          out.write("		        dayNamesMin: ['อา', 'จ', 'อ', 'พ', 'พฤ', 'ศ', 'ส'],\n");
          out.write("		        monthNames: ['มกราคม', 'กุมภาพันธ์', 'มีนาคม', 'เมษายน', 'พฤษภาคม', 'มิถุนายน', 'กรกฎาคม', 'สิงหาคม', 'กันยายน', 'ตุลาคม', 'พฤศจิกายน', 'ธันวาคม'],\n");
          out.write("		        //monthNamesShort: ['มกราคม', 'กุมภาพันธ์', 'มีนาคม', 'เมษายน', 'พฤษภาคม', 'มิถุนายน', 'กรกฎาคม', 'สิงหาคม', 'กันยายน', 'ตุลาคม', 'พฤศจิกายน', 'ธันวาคม'],\n");
          out.write("		        monthNamesShort: ['ม.ค.', 'ก.พ.', 'มี.ค.', 'เม.ย.', 'พ.ค.', 'มิ.ย.', 'ก.ค.', 'ส.ค.', 'ก.ย.', 'ต.ค.', 'พ.ย.', 'ธ.ค.'],\n");
          out.write("		        constrainInput: true,	\n");
          out.write("		        prevText: 'ก่อนหน้า',\n");
          out.write("		        nextText: 'ถัดไป',\n");
          out.write("		        yearRange: '-200:+10',\n");
          out.write("		        buttonText: 'เลือก',\n");
          out.write("		        numberOfMonths: 2\n");
          out.write("		    };\n");
          out.write(" 			$('.i-calendar').datepicker($.datepicker.isBuddhist);\n");
          out.write("			$('.t-calendar').datepicker($.datepicker.twomonth);\n");
          out.write("			\n");
          out.write("			$( \"#dateStart\" ).datepicker({\n");
          out.write("		    	isBuddhist: true,\n");
          out.write("				changeMonth: true,\n");
          out.write("		        changeYear: true,\n");
          out.write("		        buttonImageOnly: false,\n");
          out.write("		        dateFormat: 'dd/mm/yy',\n");
          out.write("		        dayNames: ['อาทิตย์', 'จันทร์', 'อังคาร', 'พุธ', 'พฤหัสบดี', 'ศุกร์', 'เสาร์'],\n");
          out.write("		        dayNamesMin: ['อา', 'จ', 'อ', 'พ', 'พฤ', 'ศ', 'ส'],\n");
          out.write("		        monthNames: ['มกราคม', 'กุมภาพันธ์', 'มีนาคม', 'เมษายน', 'พฤษภาคม', 'มิถุนายน', 'กรกฎาคม', 'สิงหาคม', 'กันยายน', 'ตุลาคม', 'พฤศจิกายน', 'ธันวาคม'],\n");
          out.write("		        monthNamesShort: ['ม.ค.', 'ก.พ.', 'มี.ค.', 'เม.ย.', 'พ.ค.', 'มิ.ย.', 'ก.ค.', 'ส.ค.', 'ก.ย.', 'ต.ค.', 'พ.ย.', 'ธ.ค.'],\n");
          out.write("		        constrainInput: true,	\n");
          out.write("		        prevText: 'ก่อนหน้า',\n");
          out.write("		        nextText: 'ถัดไป',\n");
          out.write("		        yearRange: '-200:+5',\n");
          out.write("		        buttonText: 'เลือก',\n");
          out.write("		        numberOfMonths: 2,\n");
          out.write("		      	onClose: function( selectedDate ) {\n");
          out.write("		        	$( \"#dateStop\" ).datepicker( \"option\", \"minDate\", selectedDate );\n");
          out.write("		      	}\n");
          out.write("		    });\n");
          out.write("			\n");
          out.write("		    $( \"#dateStop\" ).datepicker({\n");
          out.write("		    	isBuddhist: true,\n");
          out.write("				changeMonth: true,\n");
          out.write("		        changeYear: true,\n");
          out.write("		        buttonImageOnly: false,\n");
          out.write("		        dateFormat: 'dd/mm/yy',\n");
          out.write("		        dayNames: ['อาทิตย์', 'จันทร์', 'อังคาร', 'พุธ', 'พฤหัสบดี', 'ศุกร์', 'เสาร์'],\n");
          out.write("		        dayNamesMin: ['อา', 'จ', 'อ', 'พ', 'พฤ', 'ศ', 'ส'],\n");
          out.write("		        monthNames: ['มกราคม', 'กุมภาพันธ์', 'มีนาคม', 'เมษายน', 'พฤษภาคม', 'มิถุนายน', 'กรกฎาคม', 'สิงหาคม', 'กันยายน', 'ตุลาคม', 'พฤศจิกายน', 'ธันวาคม'],\n");
          out.write("		        monthNamesShort: ['ม.ค.', 'ก.พ.', 'มี.ค.', 'เม.ย.', 'พ.ค.', 'มิ.ย.', 'ก.ค.', 'ส.ค.', 'ก.ย.', 'ต.ค.', 'พ.ย.', 'ธ.ค.'],\n");
          out.write("		        constrainInput: true,	\n");
          out.write("		        prevText: 'ก่อนหน้า',\n");
          out.write("		        nextText: 'ถัดไป',\n");
          out.write("		        yearRange: '-200:+5',\n");
          out.write("		        buttonText: 'เลือก',\n");
          out.write("		        numberOfMonths: 2,\n");
          out.write("		      onClose: function( selectedDate ) {\n");
          out.write("		        $( \"#dateStart\" ).datepicker( \"option\", \"maxDate\", selectedDate );\n");
          out.write("		      }\n");
          out.write("		    });\n");
          out.write("        });\n");
          out.write(" 		\n");
          out.write(" 		function showDialogContent(url,title,size){\n");
          out.write(" 			\n");
          out.write(" 			$.post(url,{}, \n");
          out.write(" 				function(results) {	 \n");
          out.write(" 				var textAndPic = $('<div id=\"dialogs\">'+results+'</div>');	\n");
          out.write(" 				var bootdialog = bootbox.dialog({\n");
          out.write(" 				    title: title,\n");
          out.write(" 				    message: textAndPic,\n");
          out.write(" 				    className: size\n");
          out.write(" 				});\n");
          out.write(" 				\n");
          out.write(" 				$('.selectpicker').selectpicker('refresh');\n");
          out.write(" 				\n");
          out.write(" 				/* dialog.init(function(){\n");
          out.write(" 				    setTimeout(function(){\n");
          out.write(" 				        dialog.find('.bootbox-body').html(textAndPic);\n");
          out.write(" 				    }, 3000);\n");
          out.write(" 				}); */	\n");
          out.write(" 				\n");
          out.write(" 			});	\n");
          out.write(" 		}\n");
          out.write(" 		\n");
          out.write(" 		function showDialog(url,t,w,h){    		\n");
          out.write(" 	        $('#dialogs').dialog({\n");
          out.write(" 	        	modal: true,\n");
          out.write(" 	        	show: {\n");
          out.write(" 					effect: \"fade\",\n");
          out.write(" 					duration: 200\n");
          out.write(" 				},\n");
          out.write(" 	        	title: t,\n");
          out.write(" 	            width: w,\n");
          out.write(" 	            height: h,\n");
          out.write(" 	            closeOnEscape: true,\n");
          out.write(" 	            open: function () {\n");
          out.write(" 	                $.post(url,{}, \n");
          out.write(" 	              	function(results) {	 \n");
          out.write(" 	              		$('#dialogs').html(results);	\n");
          out.write(" 	              		$('#dialogs').siblings('.ui-dialog-titlebar').find('button').blur(); \n");
          out.write(" 	              		\n");
          out.write("\n");
          out.write(" 	             	});\n");
          out.write(" 	            }\n");
          out.write(" 	        });\n");
          out.write(" 		}\n");
          out.write(" 		\n");
          out.write(" 		function showLoadingSwal() {\n");
          out.write(" 			swal({\n");
          out.write("      		  	title: \"กำลังโหลดข้อมูล...\",\n");
          out.write("      		  	imageUrl: '");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/ui/sweetalert/image/entering-comment-loader.gif',\n");
          out.write("      			closeOnConfirm: false,\n");
          out.write("      			showCancelButton: false,\n");
          out.write("      			showConfirmButton: false,\n");
          out.write("      		});\n");
          out.write(" 		}\n");
          out.write(" 		function success() {\n");
          out.write(" 	        swal.close()\n");
          out.write(" 	    }\n");
          out.write("	</script>\n");
          out.write("<style type=\"text/css\">\n");
          out.write("	.popup-dialog .modal-dialog { width: 700px; }\n");
          out.write("	.popuplg-dialog .modal-dialog { width: 1000px; }\n");
          out.write("</style>\n");
          out.write("</head>");
          out.write("\n");
          out.write("\n");
          out.write("<style>\n");
          out.write(".login-userpic img {\n");
          out.write("	width: 100%;\n");
          out.write("	height: 100%;\n");
          out.write("	-webkit-border-radius: 50% !important;\n");
          out.write("	-moz-border-radius: 50% !important;\n");
          out.write("	border-radius: 50% !important;\n");
          out.write("	border: 2px solid #337ab7;\n");
          out.write("}\n");
          out.write(".student-dialog .modal-dialog {\n");
          out.write("	width: 900px;\n");
          out.write("}\n");
          out.write(".header {\n");
          out.write("	position: fixed;\n");
          out.write("	left: 0;\n");
          out.write("	right: 0;\n");
          out.write("	z-index: 1002;\n");
          out.write("	box-shadow: 0 2px 5px rgba(0, 0, 0, 0.176) !important;\n");
          out.write("	background-color: #00afda;\n");
          out.write("	background: -webkit-linear-gradient(left, #00afda, #1b5dab);\n");
          out.write("	background: -o-linear-gradient(right, #00afda, #1b5dab);\n");
          out.write("	background: -moz-linear-gradient(right, #00afda, #1b5dab);\n");
          out.write("	background: linear-gradient(to right, #00afda, #1b5dab);\n");
          out.write("}\n");
          out.write("</style>\n");
          out.write("<style type=\"text/css\">\n");
          out.write("<script src=\"https://example.com/fontawesome/v6.1.1/js/all.js\" data-auto-replace-svg=\"nest\"></script>\n");
          out.write("\n");
          out.write("</style>\n");
          out.write("<nav class=\"navbar navbar-expand-lg navbar-light bg-light \">\n");
          out.write("  <!-- Container wrapper -->\n");
          out.write("  <div class=\"container\">\n");
          out.write("    <!-- Navbar brand -->\n");
          out.write("    <!-- Search form -->\n");
          out.write("  \n");
          out.write("    <!-- Toggle button -->\n");
          out.write("    <button class=\"navbar-toggler\" type=\"button\" data-mdb-toggle=\"collapse\"\n");
          out.write("      data-mdb-target=\"#navbarSupportedContent\" aria-controls=\"navbarSupportedContent\" aria-expanded=\"false\"\n");
          out.write("      aria-label=\"Toggle navigation\">\n");
          out.write("      <i class=\"fas fa-bars\"></i>\n");
          out.write("    </button>\n");
          out.write("\n");
          out.write("    <!-- Collapsible wrapper -->\n");
          out.write("    <div class=\"collapse navbar-collapse\" id=\"navbarSupportedContent\" style=\"margin-right:30px;\">\n");
          out.write("      <!-- Left links -->\n");
          out.write("      <ul class=\"navbar-nav ms-auto mb-2 mb-lg-0\">\n");
          out.write("        \n");
          out.write("        \n");
          out.write("        <li class=\"nav-item dropdown\">\n");
          out.write("          <a\n");
          out.write("            class=\"nav-link dropdown-toggle d-flex align-items-center\"\n");
          out.write("            href=\"#\"\n");
          out.write("            id=\"navbarDropdownMenuLink\"\n");
          out.write("            role=\"button\"\n");
          out.write("            data-mdb-toggle=\"dropdown\"\n");
          out.write("            aria-expanded=\"false\"\n");
          out.write("          >\n");
          out.write("            <span class=\"\">");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${SSUser.username}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</span>\n");
          out.write("            <img\n");
          out.write("              src=\"https://mdbootstrap.com/img/Photos/Avatars/img%20(9).jpg\"\n");
          out.write("              class=\"rounded-circle\"\n");
          out.write("              height=\"30\"\n");
          out.write("              alt=\"\"\n");
          out.write("              loading=\"lazy\"\n");
          out.write("            />\n");
          out.write("          </a>\n");
          out.write("          <ul class=\"dropdown-menu\" aria-labelledby=\"navbarDropdownMenuLink\">\n");
          out.write("            <li><a class=\"dropdown-item\" href=\"login.htm?mode=initProfile\">My profile</a></li>\n");
          out.write("            <li><a class=\"dropdown-item\" href=\"login.htm?mode=initChange\">Change Password</a></li>\n");
          out.write("            <li><a class=\"dropdown-item\" href=\"login.htm?mode=index\">Logout</a></li>\n");
          out.write("          </ul>\n");
          out.write("        </li>\n");
          out.write("      </ul>\n");
          out.write("      <!-- Left links -->\n");
          out.write("    </div>\n");
          out.write("    <!-- Collapsible wrapper -->\n");
          out.write("  </div>\n");
          out.write("  <!-- Container wrapper -->\n");
          out.write("</nav>\n");
          out.write("	\n");
          out.write("<!--header end-->\n");
          out.write("\n");
          out.write("\r\n");
          out.write("		<h2>รายงานปัญหา</h2>\r\n");
          out.write("		<section id=\"main-content\">\r\n");
          out.write("		<section class=\"wrapper\">\r\n");
          out.write("         <div>\r\n");
          out.write("         	<h2>รายงานปัญหา</h2>\r\n");
          out.write("         	<label>ชื่อโครงการ</label>\r\n");
          out.write("        	");
          out.write("\r\n");
          out.write("         </div>\r\n");
          out.write("         \r\n");
          out.write("         <div>\r\n");
          out.write("         	<label>หัวข้อปัญหา</label>\r\n");
          out.write("         	");
          if (_jspx_meth_html_005ftext_005f0(_jspx_th_html_005fform_005f0, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("         </div>\r\n");
          out.write("         \r\n");
          out.write("        <div>\r\n");
          out.write("        <label>Select a file to upload: </label>\r\n");
          out.write("         <input property=\"file\" type = \"file\" accept=\".pdf, .png, .jpg, .jpeg\"/>\r\n");
          out.write("        </div>\r\n");
          out.write("        \r\n");
          out.write("        <div>\r\n");
          out.write("        <label>ปัญหาที่เกิด</label>\r\n");
          out.write("         ");
          if (_jspx_meth_html_005ftext_005f1(_jspx_th_html_005fform_005f0, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("        </div>\r\n");
          out.write("         \r\n");
          out.write("         <button class=\"btn-blue btn-sm\" onClick=\"add()\">upload file</button>\r\n");
          out.write("         <button class=\"btn-blue btn-sm\" onclick=\"back()\">back</button>\r\n");
          out.write("         \r\n");
          out.write("         \r\n");
          out.write("		</section>\r\n");
          out.write("		</section>\r\n");
          out.write(" </html>\r\n");
          int evalDoAfterBody = _jspx_th_html_005fform_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_html_005fform_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fhtml_005fform_0026_005fstyleId_005faction.reuse(_jspx_th_html_005fform_005f0);
      _jspx_th_html_005fform_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_html_005fform_005f0, _jsp_getInstanceManager(), _jspx_th_html_005fform_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_html_005fhidden_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_html_005fform_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  html:hidden
    org.apache.struts.taglib.html.HiddenTag _jspx_th_html_005fhidden_005f0 = (org.apache.struts.taglib.html.HiddenTag) _005fjspx_005ftagPool_005fhtml_005fhidden_0026_005fproperty_005fnobody.get(org.apache.struts.taglib.html.HiddenTag.class);
    boolean _jspx_th_html_005fhidden_005f0_reused = false;
    try {
      _jspx_th_html_005fhidden_005f0.setPageContext(_jspx_page_context);
      _jspx_th_html_005fhidden_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_html_005fform_005f0);
      // /page/feature/addRequest.jsp(48,0) name = property type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_html_005fhidden_005f0.setProperty("mode");
      int _jspx_eval_html_005fhidden_005f0 = _jspx_th_html_005fhidden_005f0.doStartTag();
      if (_jspx_th_html_005fhidden_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fhtml_005fhidden_0026_005fproperty_005fnobody.reuse(_jspx_th_html_005fhidden_005f0);
      _jspx_th_html_005fhidden_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_html_005fhidden_005f0, _jsp_getInstanceManager(), _jspx_th_html_005fhidden_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_html_005ftext_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_html_005fform_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  html:text
    org.apache.struts.taglib.html.TextTag _jspx_th_html_005ftext_005f0 = (org.apache.struts.taglib.html.TextTag) _005fjspx_005ftagPool_005fhtml_005ftext_0026_005fstyleId_005fstyleClass_005fproperty_005fplaceHolder_005fonkeypress_005fnobody.get(org.apache.struts.taglib.html.TextTag.class);
    boolean _jspx_th_html_005ftext_005f0_reused = false;
    try {
      _jspx_th_html_005ftext_005f0.setPageContext(_jspx_page_context);
      _jspx_th_html_005ftext_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_html_005fform_005f0);
      // /page/feature/addRequest.jsp(64,10) name = property type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_html_005ftext_005f0.setProperty("title");
      // /page/feature/addRequest.jsp(64,10) name = onkeypress type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_html_005ftext_005f0.setOnkeypress("submitEnter();");
      // /page/feature/addRequest.jsp(64,10) name = styleClass type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_html_005ftext_005f0.setStyleClass("form-control");
      // /page/feature/addRequest.jsp(64,10) name = styleId type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_html_005ftext_005f0.setStyleId("title");
      // /page/feature/addRequest.jsp(64,10) name = placeHolder type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_html_005ftext_005f0.setPlaceHolder("หัวข้อปัญหา");
      int _jspx_eval_html_005ftext_005f0 = _jspx_th_html_005ftext_005f0.doStartTag();
      if (_jspx_th_html_005ftext_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fhtml_005ftext_0026_005fstyleId_005fstyleClass_005fproperty_005fplaceHolder_005fonkeypress_005fnobody.reuse(_jspx_th_html_005ftext_005f0);
      _jspx_th_html_005ftext_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_html_005ftext_005f0, _jsp_getInstanceManager(), _jspx_th_html_005ftext_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_html_005ftext_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_html_005fform_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  html:text
    org.apache.struts.taglib.html.TextTag _jspx_th_html_005ftext_005f1 = (org.apache.struts.taglib.html.TextTag) _005fjspx_005ftagPool_005fhtml_005ftext_0026_005fstyleId_005fstyleClass_005fproperty_005fplaceHolder_005fonkeypress_005fnobody.get(org.apache.struts.taglib.html.TextTag.class);
    boolean _jspx_th_html_005ftext_005f1_reused = false;
    try {
      _jspx_th_html_005ftext_005f1.setPageContext(_jspx_page_context);
      _jspx_th_html_005ftext_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_html_005fform_005f0);
      // /page/feature/addRequest.jsp(74,9) name = property type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_html_005ftext_005f1.setProperty("remark");
      // /page/feature/addRequest.jsp(74,9) name = onkeypress type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_html_005ftext_005f1.setOnkeypress("submitEnter();");
      // /page/feature/addRequest.jsp(74,9) name = styleClass type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_html_005ftext_005f1.setStyleClass("form-control");
      // /page/feature/addRequest.jsp(74,9) name = styleId type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_html_005ftext_005f1.setStyleId("remark");
      // /page/feature/addRequest.jsp(74,9) name = placeHolder type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_html_005ftext_005f1.setPlaceHolder("ปัญหาที่เกิด");
      int _jspx_eval_html_005ftext_005f1 = _jspx_th_html_005ftext_005f1.doStartTag();
      if (_jspx_th_html_005ftext_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fhtml_005ftext_0026_005fstyleId_005fstyleClass_005fproperty_005fplaceHolder_005fonkeypress_005fnobody.reuse(_jspx_th_html_005ftext_005f1);
      _jspx_th_html_005ftext_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_html_005ftext_005f1, _jsp_getInstanceManager(), _jspx_th_html_005ftext_005f1_reused);
    }
    return false;
  }
}
