/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.64
 * Generated at: 2565-08-02 06:49:50 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.page.feature;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class request_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(6);
    _jspx_dependants.put("/WEB-INF/tld/fn.tld", Long.valueOf(1655975438917L));
    _jspx_dependants.put("/WEB-INF/tld/struts-bean.tld", Long.valueOf(1655975438920L));
    _jspx_dependants.put("/page/inc_header_script.jsp", Long.valueOf(1659407833651L));
    _jspx_dependants.put("/WEB-INF/tld/struts-html.tld", Long.valueOf(1655975438921L));
    _jspx_dependants.put("/WEB-INF/tld/c.tld", Long.valueOf(1655975438913L));
    _jspx_dependants.put("/WEB-INF/tld/struts-logic.tld", Long.valueOf(1655975438922L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fhtml_005fform_0026_005fstyleId_005faction;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fhtml_005fhidden_0026_005fproperty_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005flogic_005fpresent_0026_005fproperty_005fname;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005flogic_005fnotEmpty_0026_005fproperty_005fname;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005flogic_005fiterate_0026_005fproperty_005fname_005findexId_005fid;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fhtml_005fselect_0026_005fstyleClass_005fproperty;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fhtml_005foptionsCollection_0026_005fvalue_005fproperty_005flabel_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fhtml_005fform_0026_005fstyleId_005faction = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fhtml_005fhidden_0026_005fproperty_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005flogic_005fpresent_0026_005fproperty_005fname = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005flogic_005fnotEmpty_0026_005fproperty_005fname = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005flogic_005fiterate_0026_005fproperty_005fname_005findexId_005fid = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fhtml_005fselect_0026_005fstyleClass_005fproperty = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fhtml_005foptionsCollection_0026_005fvalue_005fproperty_005flabel_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fhtml_005fform_0026_005fstyleId_005faction.release();
    _005fjspx_005ftagPool_005fhtml_005fhidden_0026_005fproperty_005fnobody.release();
    _005fjspx_005ftagPool_005flogic_005fpresent_0026_005fproperty_005fname.release();
    _005fjspx_005ftagPool_005flogic_005fnotEmpty_0026_005fproperty_005fname.release();
    _005fjspx_005ftagPool_005flogic_005fiterate_0026_005fproperty_005fname_005findexId_005fid.release();
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
    _005fjspx_005ftagPool_005fhtml_005fselect_0026_005fstyleClass_005fproperty.release();
    _005fjspx_005ftagPool_005fhtml_005foptionsCollection_0026_005fvalue_005fproperty_005flabel_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\n");
      out.write("\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("	<meta charset=\"utf-8\">\n");
      out.write("	<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("	<meta name=\"description\" content=\"\">\n");
      out.write("	<meta name=\"author\" content=\"\">\n");
      out.write("	<meta name=\"keyword\" content=\"\">\n");
      out.write("	\n");
      out.write("	<title>รายงานปัญหา</title>\n");
      out.write("	\n");
      out.write("	\n");
      out.write("	\n");
      out.write("	<script src=\"//cdn.jsdelivr.net/npm/sweetalert2@11\"></script>\n");
      out.write("	<!-- Font Awesome -->\n");
      out.write("	<link\n");
      out.write("	  href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css\"\n");
      out.write("	  rel=\"stylesheet\"\n");
      out.write("	/>\n");
      out.write("	<!-- Google Fonts -->\n");
      out.write("	<link\n");
      out.write("	  href=\"https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap\"\n");
      out.write("	  rel=\"stylesheet\"\n");
      out.write("	/>\n");
      out.write("	<!-- MDB -->\n");
      out.write("	<link\n");
      out.write("	  href=\"https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/4.2.0/mdb.min.css\"\n");
      out.write("	  rel=\"stylesheet\"\n");
      out.write("	/>\n");
      out.write("	<!-- MDB -->\n");
      out.write("	<script\n");
      out.write("	  type=\"text/javascript\"\n");
      out.write("	  src=\"https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/4.2.0/mdb.min.js\"\n");
      out.write("	></script>\n");
      out.write("	<!-- Bootstrap CSS -->\n");
      out.write("	<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/ui/css/bootstrap.min.css\" rel=\"stylesheet\"/>\n");
      out.write("	<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/ui/css/bootstrap-theme.css\" rel=\"stylesheet\"/>\n");
      out.write("	<!-- CSS only -->\n");
      out.write("	<link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css\" rel=\"stylesheet\" integrity=\"sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor\" crossorigin=\"anonymous\">\n");
      out.write("	<!-- font -->\n");
      out.write("	<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/ui/fonts/webfont.css\" rel=\"stylesheet\" />\n");
      out.write("	<!-- font icon -->\n");
      out.write("	<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/ui/css/elegant-icons-style.css\" rel=\"stylesheet\" />\n");
      out.write("	<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/ui/css/font-awesome.min.css\" rel=\"stylesheet\" />\n");
      out.write("	<!-- datatable -->\n");
      out.write("	<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/ui/css/dataTables.bootstrap.css\" rel=\"stylesheet\"/>\n");
      out.write("	<!-- Custom styles -->\n");
      out.write("	<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/ui/css/style.css\" rel=\"stylesheet\"/>\n");
      out.write("	<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/ui/css/style-responsive.css\" rel=\"stylesheet\" />\n");
      out.write("	<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/ui/css/jquery-ui-10.12.1.css\" rel=\"stylesheet\"/>\n");
      out.write("	<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/ui/css/style-button.css\" rel=\"stylesheet\"/>\n");
      out.write("	<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/ui/css/bootstrap-select.css\" rel=\"stylesheet\"/>\n");
      out.write("	<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/ui/css/materialize-color.css\" rel=\"stylesheet\"/>\n");
      out.write("	<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/ui/sweetalert/css/sweetalert.css\" rel=\"stylesheet\"/>\n");
      out.write("\n");
      out.write("	<!-- javascripts -->\n");
      out.write("	<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/ui/js/jquery-1.12.4.js\"></script>\n");
      out.write("	<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/ui/js/jquery-ui-1.10.4.min.js\"></script>\n");
      out.write("	<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/ui/js/jquery-1.8.3.min.js\"></script>\n");
      out.write("	<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/ui/js/jquery-ui-1.9.2.custom.min.js\" type=\"text/javascript\"></script>\n");
      out.write("	<!-- for set format thai -->\n");
      out.write("	<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/ui/js/jquery.ui.1.8.10.offset.datepicker.min.js\" type=\"text/javascript\"></script>\n");
      out.write("	\n");
      out.write("	<!-- bootstrap -->\n");
      out.write("	<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/ui/js/bootstrap.min.js\"></script>\n");
      out.write("	<!-- nice scroll -->\n");
      out.write("	<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/ui/js/jquery.scrollTo.min.js\"></script>\n");
      out.write("	<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/ui/js/jquery.nicescroll.js\" type=\"text/javascript\"></script>\n");
      out.write("	<!-- custom select -->\n");
      out.write("	<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/ui/js/jquery.customSelect.min.js\"></script>\n");
      out.write("	<!-- JavaScript Bundle with Popper -->\n");
      out.write("	<!--custome script for all page-->\n");
      out.write("	<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/ui/js/scripts.js\"></script>\n");
      out.write("	\n");
      out.write("	<!-- custom script for this page-->\n");
      out.write("	<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/ui/js/jquery.autosize.min.js\"></script>\n");
      out.write("	<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/ui/js/jquery.placeholder.min.js\"></script>\n");
      out.write("	<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/ui/js/jquery.slimscroll.min.js\"></script>\n");
      out.write("	<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/ui/js/bootbox.js\"></script>\n");
      out.write("\n");
      out.write("	<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/ui/js/bootstrap-select.js\"></script>\n");
      out.write("	<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/ui/js/bootstrap-typeahead.js\"></script>\n");
      out.write("	\n");
      out.write("	<!-- datatable -->\n");
      out.write("	<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/ui/js/jquery.dataTables.js\" type=\"text/javascript\"></script>\n");
      out.write("	<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/ui/js/dataTables.bootstrap.js\" type=\"text/javascript\"></script>\n");
      out.write("	\n");
      out.write("	<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/ui/js/jquery.validate.min.js\" type=\"text/javascript\"></script>\n");
      out.write("	<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/ui/js/quotwaiting-forquot-modal-dialog.js\" type=\"text/javascript\"></script>\n");
      out.write("	<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/ui/sweetalert/js/sweetalert.min.js\" type=\"text/javascript\"></script>\n");
      out.write("	\n");
      out.write("	<script type=\"text/javascript\">\n");
      out.write(" 		$(document).ready(function () {\n");
      out.write(" 			\n");
      out.write(" 			$(\"#msgSuccess\").delay(800).fadeOut(1000);\n");
      out.write(" 			$(\"#msgWarning\").delay(800).fadeOut(1000);\n");
      out.write(" 			\n");
      out.write("			try {\n");
      out.write("				var variables = {};\n");
      out.write("		      	variables = {\n");
      out.write("						\"sProcessing\": \"กำลังดำเนินการ...\",\n");
      out.write("						\"sLengthMenu\": \"แสดง _MENU_  แถว\",\n");
      out.write("						\"sZeroRecords\": \"ไม่พบข้อมูล\",\n");
      out.write("						\"sInfo\": \"แสดง _START_ ถึง _END_ จาก _TOTAL_ แถว\",\n");
      out.write("						\"sInfoEmpty\": \"แสดง 0 ถึง 0 จาก 0 แถว\",\n");
      out.write("						\"sInfoFiltered\": \"(กรองข้อมูล _MAX_ ทุกแถว)\",\n");
      out.write("						\"sInfoPostFix\": \"\",\n");
      out.write("						\"sSearch\": \"ค้นหา: \",\n");
      out.write("						\"sUrl\": \"\",\n");
      out.write("						\"oPaginate\": {\n");
      out.write("						    \"sFirst\": \"เริ่มต้น\",\n");
      out.write("						    \"sPrevious\": \"ก่อนหน้า\",\n");
      out.write("						    \"sNext\": \"ถัดไป\",\n");
      out.write("						    \"sLast\": \"สุดท้าย\"\n");
      out.write("						}\n");
      out.write("				};\n");
      out.write("			\n");
      out.write("				var options = { \"aoColumnDefs\": [{ bSortable: false, aTargets: ['no-sort'] }],\"oLanguage\": variables};\n");
      out.write("				var optionsHundred = { \"aoColumnDefs\": [{ bSortable: false, aTargets: ['no-sort'] }],\"iDisplayLength\": 100,\"oLanguage\": variables};\n");
      out.write("				var optionsFive = { \"aoColumnDefs\": [{ bSortable: false, aTargets: ['no-sort'] }],\"iDisplayLength\": 5,\"oLanguage\": variables};\n");
      out.write("			\n");
      out.write("				$(\".grid-default\").dataTable(options);\n");
      out.write("				$(\".grid-hundred\").dataTable(optionsHundred);\n");
      out.write("				$(\".grid-five\").dataTable(optionsFive);\n");
      out.write("			} catch (e) {\n");
      out.write("			}\n");
      out.write("			\n");
      out.write("			$.datepicker.isBuddhist ={\n");
      out.write("				isBuddhist: true,\n");
      out.write("				changeMonth: true,\n");
      out.write("		        changeYear: true,\n");
      out.write("		        buttonImageOnly: false,\n");
      out.write("		        dateFormat: 'dd/mm/yy',\n");
      out.write("		        dayNames: ['อาทิตย์', 'จันทร์', 'อังคาร', 'พุธ', 'พฤหัสบดี', 'ศุกร์', 'เสาร์'],\n");
      out.write("		        dayNamesMin: ['อา', 'จ', 'อ', 'พ', 'พฤ', 'ศ', 'ส'],\n");
      out.write("		        monthNames: ['มกราคม', 'กุมภาพันธ์', 'มีนาคม', 'เมษายน', 'พฤษภาคม', 'มิถุนายน', 'กรกฎาคม', 'สิงหาคม', 'กันยายน', 'ตุลาคม', 'พฤศจิกายน', 'ธันวาคม'],\n");
      out.write("		        //monthNamesShort: ['มกราคม', 'กุมภาพันธ์', 'มีนาคม', 'เมษายน', 'พฤษภาคม', 'มิถุนายน', 'กรกฎาคม', 'สิงหาคม', 'กันยายน', 'ตุลาคม', 'พฤศจิกายน', 'ธันวาคม'],\n");
      out.write("		        monthNamesShort: ['ม.ค.', 'ก.พ.', 'มี.ค.', 'เม.ย.', 'พ.ค.', 'มิ.ย.', 'ก.ค.', 'ส.ค.', 'ก.ย.', 'ต.ค.', 'พ.ย.', 'ธ.ค.'],\n");
      out.write("		        constrainInput: true,	\n");
      out.write("		        prevText: 'ก่อนหน้า',\n");
      out.write("		        nextText: 'ถัดไป',\n");
      out.write("		        yearRange: '-200:+10',\n");
      out.write("		        buttonText: 'เลือก'\n");
      out.write("		    };\n");
      out.write("			\n");
      out.write("			$.datepicker.twomonth ={\n");
      out.write("				isBuddhist: true,\n");
      out.write("				changeMonth: false,\n");
      out.write("		        changeYear: false,\n");
      out.write("		        buttonImageOnly: false,\n");
      out.write("		        dateFormat: 'dd/mm/yy',\n");
      out.write("		        dayNames: ['อาทิตย์', 'จันทร์', 'อังคาร', 'พุธ', 'พฤหัสบดี', 'ศุกร์', 'เสาร์'],\n");
      out.write("		        dayNamesMin: ['อา', 'จ', 'อ', 'พ', 'พฤ', 'ศ', 'ส'],\n");
      out.write("		        monthNames: ['มกราคม', 'กุมภาพันธ์', 'มีนาคม', 'เมษายน', 'พฤษภาคม', 'มิถุนายน', 'กรกฎาคม', 'สิงหาคม', 'กันยายน', 'ตุลาคม', 'พฤศจิกายน', 'ธันวาคม'],\n");
      out.write("		        //monthNamesShort: ['มกราคม', 'กุมภาพันธ์', 'มีนาคม', 'เมษายน', 'พฤษภาคม', 'มิถุนายน', 'กรกฎาคม', 'สิงหาคม', 'กันยายน', 'ตุลาคม', 'พฤศจิกายน', 'ธันวาคม'],\n");
      out.write("		        monthNamesShort: ['ม.ค.', 'ก.พ.', 'มี.ค.', 'เม.ย.', 'พ.ค.', 'มิ.ย.', 'ก.ค.', 'ส.ค.', 'ก.ย.', 'ต.ค.', 'พ.ย.', 'ธ.ค.'],\n");
      out.write("		        constrainInput: true,	\n");
      out.write("		        prevText: 'ก่อนหน้า',\n");
      out.write("		        nextText: 'ถัดไป',\n");
      out.write("		        yearRange: '-200:+10',\n");
      out.write("		        buttonText: 'เลือก',\n");
      out.write("		        numberOfMonths: 2\n");
      out.write("		    };\n");
      out.write(" 			$('.i-calendar').datepicker($.datepicker.isBuddhist);\n");
      out.write("			$('.t-calendar').datepicker($.datepicker.twomonth);\n");
      out.write("			\n");
      out.write("			$( \"#dateStart\" ).datepicker({\n");
      out.write("		    	isBuddhist: true,\n");
      out.write("				changeMonth: true,\n");
      out.write("		        changeYear: true,\n");
      out.write("		        buttonImageOnly: false,\n");
      out.write("		        dateFormat: 'dd/mm/yy',\n");
      out.write("		        dayNames: ['อาทิตย์', 'จันทร์', 'อังคาร', 'พุธ', 'พฤหัสบดี', 'ศุกร์', 'เสาร์'],\n");
      out.write("		        dayNamesMin: ['อา', 'จ', 'อ', 'พ', 'พฤ', 'ศ', 'ส'],\n");
      out.write("		        monthNames: ['มกราคม', 'กุมภาพันธ์', 'มีนาคม', 'เมษายน', 'พฤษภาคม', 'มิถุนายน', 'กรกฎาคม', 'สิงหาคม', 'กันยายน', 'ตุลาคม', 'พฤศจิกายน', 'ธันวาคม'],\n");
      out.write("		        monthNamesShort: ['ม.ค.', 'ก.พ.', 'มี.ค.', 'เม.ย.', 'พ.ค.', 'มิ.ย.', 'ก.ค.', 'ส.ค.', 'ก.ย.', 'ต.ค.', 'พ.ย.', 'ธ.ค.'],\n");
      out.write("		        constrainInput: true,	\n");
      out.write("		        prevText: 'ก่อนหน้า',\n");
      out.write("		        nextText: 'ถัดไป',\n");
      out.write("		        yearRange: '-200:+5',\n");
      out.write("		        buttonText: 'เลือก',\n");
      out.write("		        numberOfMonths: 2,\n");
      out.write("		      	onClose: function( selectedDate ) {\n");
      out.write("		        	$( \"#dateStop\" ).datepicker( \"option\", \"minDate\", selectedDate );\n");
      out.write("		      	}\n");
      out.write("		    });\n");
      out.write("			\n");
      out.write("		    $( \"#dateStop\" ).datepicker({\n");
      out.write("		    	isBuddhist: true,\n");
      out.write("				changeMonth: true,\n");
      out.write("		        changeYear: true,\n");
      out.write("		        buttonImageOnly: false,\n");
      out.write("		        dateFormat: 'dd/mm/yy',\n");
      out.write("		        dayNames: ['อาทิตย์', 'จันทร์', 'อังคาร', 'พุธ', 'พฤหัสบดี', 'ศุกร์', 'เสาร์'],\n");
      out.write("		        dayNamesMin: ['อา', 'จ', 'อ', 'พ', 'พฤ', 'ศ', 'ส'],\n");
      out.write("		        monthNames: ['มกราคม', 'กุมภาพันธ์', 'มีนาคม', 'เมษายน', 'พฤษภาคม', 'มิถุนายน', 'กรกฎาคม', 'สิงหาคม', 'กันยายน', 'ตุลาคม', 'พฤศจิกายน', 'ธันวาคม'],\n");
      out.write("		        monthNamesShort: ['ม.ค.', 'ก.พ.', 'มี.ค.', 'เม.ย.', 'พ.ค.', 'มิ.ย.', 'ก.ค.', 'ส.ค.', 'ก.ย.', 'ต.ค.', 'พ.ย.', 'ธ.ค.'],\n");
      out.write("		        constrainInput: true,	\n");
      out.write("		        prevText: 'ก่อนหน้า',\n");
      out.write("		        nextText: 'ถัดไป',\n");
      out.write("		        yearRange: '-200:+5',\n");
      out.write("		        buttonText: 'เลือก',\n");
      out.write("		        numberOfMonths: 2,\n");
      out.write("		      onClose: function( selectedDate ) {\n");
      out.write("		        $( \"#dateStart\" ).datepicker( \"option\", \"maxDate\", selectedDate );\n");
      out.write("		      }\n");
      out.write("		    });\n");
      out.write("        });\n");
      out.write(" 		\n");
      out.write(" 		function showDialogContent(url,title,size){\n");
      out.write(" 			\n");
      out.write(" 			$.post(url,{}, \n");
      out.write(" 				function(results) {	 \n");
      out.write(" 				var textAndPic = $('<div id=\"dialogs\">'+results+'</div>');	\n");
      out.write(" 				var bootdialog = bootbox.dialog({\n");
      out.write(" 				    title: title,\n");
      out.write(" 				    message: textAndPic,\n");
      out.write(" 				    className: size\n");
      out.write(" 				});\n");
      out.write(" 				\n");
      out.write(" 				$('.selectpicker').selectpicker('refresh');\n");
      out.write(" 				\n");
      out.write(" 				/* dialog.init(function(){\n");
      out.write(" 				    setTimeout(function(){\n");
      out.write(" 				        dialog.find('.bootbox-body').html(textAndPic);\n");
      out.write(" 				    }, 3000);\n");
      out.write(" 				}); */	\n");
      out.write(" 				\n");
      out.write(" 			});	\n");
      out.write(" 		}\n");
      out.write(" 		\n");
      out.write(" 		function showDialog(url,t,w,h){    		\n");
      out.write(" 	        $('#dialogs').dialog({\n");
      out.write(" 	        	modal: true,\n");
      out.write(" 	        	show: {\n");
      out.write(" 					effect: \"fade\",\n");
      out.write(" 					duration: 200\n");
      out.write(" 				},\n");
      out.write(" 	        	title: t,\n");
      out.write(" 	            width: w,\n");
      out.write(" 	            height: h,\n");
      out.write(" 	            closeOnEscape: true,\n");
      out.write(" 	            open: function () {\n");
      out.write(" 	                $.post(url,{}, \n");
      out.write(" 	              	function(results) {	 \n");
      out.write(" 	              		$('#dialogs').html(results);	\n");
      out.write(" 	              		$('#dialogs').siblings('.ui-dialog-titlebar').find('button').blur(); \n");
      out.write(" 	              		\n");
      out.write("\n");
      out.write(" 	             	});\n");
      out.write(" 	            }\n");
      out.write(" 	        });\n");
      out.write(" 		}\n");
      out.write(" 		\n");
      out.write(" 		function showLoadingSwal() {\n");
      out.write(" 			swal({\n");
      out.write("      		  	title: \"กำลังโหลดข้อมูล...\",\n");
      out.write("      		  	imageUrl: '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/ui/sweetalert/image/entering-comment-loader.gif',\n");
      out.write("      			closeOnConfirm: false,\n");
      out.write("      			showCancelButton: false,\n");
      out.write("      			showConfirmButton: false,\n");
      out.write("      		});\n");
      out.write(" 		}\n");
      out.write(" 		function success() {\n");
      out.write(" 	        swal.close()\n");
      out.write(" 	    }\n");
      out.write("	</script>\n");
      out.write("<style type=\"text/css\">\n");
      out.write("	.popup-dialog .modal-dialog { width: 700px; }\n");
      out.write("	.popuplg-dialog .modal-dialog { width: 1000px; }\n");
      out.write("</style>\n");
      out.write("</head>");
      out.write("\r\n");
      out.write("<script src=\"//cdn.jsdelivr.net/npm/sweetalert2@11\"></script>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\r\n");
      out.write("	\r\n");
      out.write("	function add(){\r\n");
      out.write("		document.forms[0].mode.value = \"requestBtn\";\r\n");
      out.write("		document.forms[0].submit();\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	function edit(id){\r\n");
      out.write("		  document.forms[0].mode.value = \"editRequest\";\r\n");
      out.write("		  document.forms[0].id.value = id;\r\n");
      out.write("		  document.forms[0].submit();\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	function del(id){\r\n");
      out.write("		Swal.fire({\r\n");
      out.write("			  title: 'Are you sure?',\r\n");
      out.write("			  text: \"You want to delete!\",\r\n");
      out.write("			  icon: 'warning',\r\n");
      out.write("			  showCancelButton: true,\r\n");
      out.write("			  confirmButtonColor: '#3085d6',\r\n");
      out.write("			  cancelButtonColor: '#d33',\r\n");
      out.write("			  confirmButtonText: 'Yes'\r\n");
      out.write("			}).then((result) => {\r\n");
      out.write("				if(result.isConfirmed){\r\n");
      out.write("					document.forms[0].mode.value = \"deleteRequest\";\r\n");
      out.write("				  	document.forms[0].id.value = id;\r\n");
      out.write("				    document.forms[0].submit();\r\n");
      out.write("				}\r\n");
      out.write("			    \r\n");
      out.write("			  })\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	function save(){\r\n");
      out.write("		Swal.fire({\r\n");
      out.write("			  title: 'Are you sure?',\r\n");
      out.write("			  text: \"You want to save change!\",\r\n");
      out.write("			  icon: 'warning',\r\n");
      out.write("			  showCancelButton: true,\r\n");
      out.write("			  confirmButtonColor: '#3085d6',\r\n");
      out.write("			  cancelButtonColor: '#d33',\r\n");
      out.write("			  confirmButtonText: 'Yes'\r\n");
      out.write("			}).then((result) => {\r\n");
      out.write("				if(result.isConfirmed){\r\n");
      out.write("					\r\n");
      out.write("\r\n");
      out.write("				}\r\n");
      out.write("			    \r\n");
      out.write("			  })\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("\r\n");
      out.write("	\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("h2{\r\n");
      out.write("	margin-top:50px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("	");
      //  html:form
      org.apache.struts.taglib.html.FormTag _jspx_th_html_005fform_005f0 = (org.apache.struts.taglib.html.FormTag) _005fjspx_005ftagPool_005fhtml_005fform_0026_005fstyleId_005faction.get(org.apache.struts.taglib.html.FormTag.class);
      boolean _jspx_th_html_005fform_005f0_reused = false;
      try {
        _jspx_th_html_005fform_005f0.setPageContext(_jspx_page_context);
        _jspx_th_html_005fform_005f0.setParent(null);
        // /page/feature/request.jsp(77,1) name = action type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_html_005fform_005f0.setAction("/index");
        // /page/feature/request.jsp(77,1) name = styleId type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_html_005fform_005f0.setStyleId("eduForm");
        int _jspx_eval_html_005fform_005f0 = _jspx_th_html_005fform_005f0.doStartTag();
        if (_jspx_eval_html_005fform_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write('\r');
            out.write('\n');
            out.write('	');
            if (_jspx_meth_html_005fhidden_005f0(_jspx_th_html_005fform_005f0, _jspx_page_context))
              return;
            out.write("\r\n");
            out.write("	<section class=\"ftco-section\">\r\n");
            out.write("		<div class=\"container\">\r\n");
            out.write("		<div class=\"wrapper\">\r\n");
            out.write("			<div class=\"row justify-content-center\">\r\n");
            out.write("				<div class=\"text-center col-lg-12\">\r\n");
            out.write("					\r\n");
            out.write("					<h2>ตารางการส่งคำร้องเรียน</h2>\r\n");
            out.write("				</div>\r\n");
            out.write("			</div>\r\n");
            out.write("			\r\n");
            out.write("			\r\n");
            out.write("				<div class=\"col-md-12\">\r\n");
            out.write("					<div class=\"table-wrap\">\r\n");
            out.write("					");
            //  logic:present
            org.apache.struts.taglib.logic.PresentTag _jspx_th_logic_005fpresent_005f0 = (org.apache.struts.taglib.logic.PresentTag) _005fjspx_005ftagPool_005flogic_005fpresent_0026_005fproperty_005fname.get(org.apache.struts.taglib.logic.PresentTag.class);
            boolean _jspx_th_logic_005fpresent_005f0_reused = false;
            try {
              _jspx_th_logic_005fpresent_005f0.setPageContext(_jspx_page_context);
              _jspx_th_logic_005fpresent_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_html_005fform_005f0);
              // /page/feature/request.jsp(92,5) name = name type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
              _jspx_th_logic_005fpresent_005f0.setName("indexForm");
              // /page/feature/request.jsp(92,5) name = property type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
              _jspx_th_logic_005fpresent_005f0.setProperty("resultList");
              int _jspx_eval_logic_005fpresent_005f0 = _jspx_th_logic_005fpresent_005f0.doStartTag();
              if (_jspx_eval_logic_005fpresent_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
                do {
                  out.write("\r\n");
                  out.write("					");
                  //  logic:notEmpty
                  org.apache.struts.taglib.logic.NotEmptyTag _jspx_th_logic_005fnotEmpty_005f0 = (org.apache.struts.taglib.logic.NotEmptyTag) _005fjspx_005ftagPool_005flogic_005fnotEmpty_0026_005fproperty_005fname.get(org.apache.struts.taglib.logic.NotEmptyTag.class);
                  boolean _jspx_th_logic_005fnotEmpty_005f0_reused = false;
                  try {
                    _jspx_th_logic_005fnotEmpty_005f0.setPageContext(_jspx_page_context);
                    _jspx_th_logic_005fnotEmpty_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_logic_005fpresent_005f0);
                    // /page/feature/request.jsp(93,5) name = name type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
                    _jspx_th_logic_005fnotEmpty_005f0.setName("indexForm");
                    // /page/feature/request.jsp(93,5) name = property type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
                    _jspx_th_logic_005fnotEmpty_005f0.setProperty("resultList");
                    int _jspx_eval_logic_005fnotEmpty_005f0 = _jspx_th_logic_005fnotEmpty_005f0.doStartTag();
                    if (_jspx_eval_logic_005fnotEmpty_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
                      do {
                        out.write("\r\n");
                        out.write("						<table class=\"table table-striped\">\r\n");
                        out.write("						  <thead>\r\n");
                        out.write("						    <tr>\r\n");
                        out.write("						      <th class = \"text-center\">NO.</th>\r\n");
                        out.write("						      <th class = \"text-center\">หัวข้อ</th>\r\n");
                        out.write("						      <th class = \"text-center\">ผู้แจ้งเรื่อง</th>\r\n");
                        out.write("						      \r\n");
                        out.write("						      <th class = \"text-center\">สถานะ</th>\r\n");
                        out.write("<!-- 						      <th>ประเภท</th> -->\r\n");
                        out.write("<!-- 						      <th>โครงการ</th> -->\r\n");
                        out.write("\r\n");
                        out.write("<!-- 						      <th>รายละเอียด</th> -->\r\n");
                        out.write("<!-- 						      <th>วันที่ส่งคำร้อง</th> -->\r\n");
                        out.write("<!-- 						      <th>ไฟล์</th> -->\r\n");
                        out.write("						    </tr>\r\n");
                        out.write("						  </thead>\r\n");
                        out.write("						  <tbody>\r\n");
                        out.write("						  	\r\n");
                        out.write("								");
                        //  logic:iterate
                        org.apache.struts.taglib.logic.IterateTag _jspx_th_logic_005fiterate_005f0 = (org.apache.struts.taglib.logic.IterateTag) _005fjspx_005ftagPool_005flogic_005fiterate_0026_005fproperty_005fname_005findexId_005fid.get(org.apache.struts.taglib.logic.IterateTag.class);
                        boolean _jspx_th_logic_005fiterate_005f0_reused = false;
                        try {
                          _jspx_th_logic_005fiterate_005f0.setPageContext(_jspx_page_context);
                          _jspx_th_logic_005fiterate_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_logic_005fnotEmpty_005f0);
                          // /page/feature/request.jsp(112,8) name = id type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
                          _jspx_th_logic_005fiterate_005f0.setId("item");
                          // /page/feature/request.jsp(112,8) name = name type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
                          _jspx_th_logic_005fiterate_005f0.setName("indexForm");
                          // /page/feature/request.jsp(112,8) name = property type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
                          _jspx_th_logic_005fiterate_005f0.setProperty("resultList");
                          // /page/feature/request.jsp(112,8) name = indexId type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
                          _jspx_th_logic_005fiterate_005f0.setIndexId("index");
                          int _jspx_eval_logic_005fiterate_005f0 = _jspx_th_logic_005fiterate_005f0.doStartTag();
                          if (_jspx_eval_logic_005fiterate_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
                            java.lang.Object item = null;
                            java.lang.Integer index = null;
                            if (_jspx_eval_logic_005fiterate_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
                              out = org.apache.jasper.runtime.JspRuntimeLibrary.startBufferedBody(_jspx_page_context, _jspx_th_logic_005fiterate_005f0);
                            }
                            item = (java.lang.Object) _jspx_page_context.findAttribute("item");
                            index = (java.lang.Integer) _jspx_page_context.findAttribute("index");
                            do {
                              out.write("\r\n");
                              out.write("								<tr>\r\n");
                              out.write("								<td align=\"center\">");
                              out.print( index+1 );
                              out.write("</td>\r\n");
                              out.write("								<td align=\"center\">");
                              out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${item.title }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
                              out.write("</td>\r\n");
                              out.write("								<td align=\"center\">");
                              out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${item.user.nickname }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
                              out.write("</td>\r\n");
                              out.write("								");
                              if (_jspx_meth_c_005fif_005f0(_jspx_th_logic_005fiterate_005f0, _jspx_page_context))
                              return;
                              out.write("\r\n");
                              out.write("								\r\n");
                              out.write("								");
                              if (_jspx_meth_c_005fif_005f1(_jspx_th_logic_005fiterate_005f0, _jspx_page_context))
                              return;
                              out.write("\r\n");
                              out.write("								\r\n");
                              out.write("								");
                              if (_jspx_meth_c_005fif_005f2(_jspx_th_logic_005fiterate_005f0, _jspx_page_context))
                              return;
                              out.write("\r\n");
                              out.write("								\r\n");
                              out.write("								");
                              if (_jspx_meth_c_005fif_005f3(_jspx_th_logic_005fiterate_005f0, _jspx_page_context))
                              return;
                              out.write("\r\n");
                              out.write("								\r\n");
                              out.write("								");
                              if (_jspx_meth_c_005fif_005f4(_jspx_th_logic_005fiterate_005f0, _jspx_page_context))
                              return;
                              out.write("\r\n");
                              out.write("								\r\n");
                              out.write("								\r\n");
                              out.write('\r');
                              out.write('\n');
                              out.write("\r\n");
                              out.write("								\r\n");
                              out.write('\r');
                              out.write('\n');
                              out.write('\r');
                              out.write('\n');
                              out.write("\r\n");
                              out.write("								");
                              if (_jspx_meth_c_005fif_005f5(_jspx_th_logic_005fiterate_005f0, _jspx_page_context))
                              return;
                              out.write("\r\n");
                              out.write("								");
                              if (_jspx_meth_c_005fif_005f6(_jspx_th_logic_005fiterate_005f0, _jspx_page_context))
                              return;
                              out.write("\r\n");
                              out.write("								</tr>\r\n");
                              out.write("												<div class=\"modal fade\" id=\"exampleModal");
                              out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${item.id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
                              out.write("\" tabindex=\"-1\"\r\n");
                              out.write("													role=\"dialog\" aria-labelledby=\"exampleModalLabel\"\r\n");
                              out.write("													aria-hidden=\"true\">\r\n");
                              out.write("													<div class=\"modal-dialog\" role=\"document\">\r\n");
                              out.write("														<div class=\"modal-content\">\r\n");
                              out.write("															<div class=\"modal-header\">\r\n");
                              out.write("																<h5 class=\"modal-title\" id=\"exampleModalLabel\">รายละเอียด : ");
                              out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${item.title }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
                              out.write("</h5>\r\n");
                              out.write("															</div>\r\n");
                              out.write("															<div class=\"modal-body\">\r\n");
                              out.write("\r\n");
                              out.write("																<p>ประเภท : ");
                              out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${item.request_type.name }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
                              out.write("</p>\r\n");
                              out.write("																<p>โครงการ : ");
                              out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${item.project.name }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
                              out.write("</p>\r\n");
                              out.write("																<p>รายละเอียด : ");
                              out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${item.remark }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
                              out.write("</p>\r\n");
                              out.write("																<p>วันที่ส่งคำร้อง : ");
                              out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${item.date }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
                              out.write("</p>\r\n");
                              out.write("																<p>ไฟล์ : ");
                              out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${item.file }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
                              out.write("</p>\r\n");
                              out.write("\r\n");
                              out.write("															</div>\r\n");
                              out.write("															<div class=\"modal-footer\">\r\n");
                              out.write("																<button type=\"button\" class=\"btn btn-primary\"\r\n");
                              out.write("																	data-dismiss=\"modal\">OK</button>\r\n");
                              out.write("															</div>\r\n");
                              out.write("														</div>\r\n");
                              out.write("													</div>\r\n");
                              out.write("												</div>\r\n");
                              out.write("												\r\n");
                              out.write("												<div class=\"modal fade\" id=\"editModal");
                              out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${item.id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
                              out.write("\" tabindex=\"-1\"\r\n");
                              out.write("													role=\"dialog\" aria-labelledby=\"exampleModalLabel\"\r\n");
                              out.write("													aria-hidden=\"true\">\r\n");
                              out.write("													<div class=\"modal-dialog\" role=\"document\">\r\n");
                              out.write("														<div class=\"modal-content\">\r\n");
                              out.write("															<div class=\"modal-header\">\r\n");
                              out.write("																<h5 class=\"modal-title\" id=\"exampleModalLabel\">แก้ไข : ");
                              out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${item.title }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
                              out.write("</h5>\r\n");
                              out.write("															</div>\r\n");
                              out.write("															<div class=\"modal-body\">\r\n");
                              out.write("																<label>หัวข้อ : </label>\r\n");
                              out.write("																<input type=\"text\" class=\"form-control\" value=\"");
                              out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${item.title }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
                              out.write("\" required>\r\n");
                              out.write("																\r\n");
                              out.write("																<label>โครงการ : </label>\r\n");
                              out.write("																");
                              if (_jspx_meth_html_005fselect_005f0(_jspx_th_logic_005fiterate_005f0, _jspx_page_context))
                              return;
                              out.write("\r\n");
                              out.write("																\r\n");
                              out.write("																<label>รายละเอียด : </label>\r\n");
                              out.write("																<input type=\"text\"  class=\"form-control\" value=\"");
                              out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${item.remark }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
                              out.write("\" required>\r\n");
                              out.write("																<label>วันที่ส่งคำร้อง : </label>\r\n");
                              out.write("																<input type=\"Date\"  class=\"form-control\" value=\"");
                              out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${item.date }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
                              out.write("\" required>\r\n");
                              out.write("																<label>ไฟล์ : </label>\r\n");
                              out.write("																<input type=\"file\"  class=\"form-control\" value=\"");
                              out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${item.file }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
                              out.write("\" required>\r\n");
                              out.write("\r\n");
                              out.write("															</div>\r\n");
                              out.write("															<div class=\"modal-footer\">\r\n");
                              out.write("																<button type=\"button\" class=\"btn btn-primary\" onclick=\"save()\">Save Change</button>\r\n");
                              out.write("																<button type=\"button\" class=\"btn btn-cancel\" data-dismiss=\"modal\">Cancel</button>\r\n");
                              out.write("															</div>\r\n");
                              out.write("														</div>\r\n");
                              out.write("													</div>\r\n");
                              out.write("												</div>\r\n");
                              out.write("\r\n");
                              out.write("								");
                              int evalDoAfterBody = _jspx_th_logic_005fiterate_005f0.doAfterBody();
                              item = (java.lang.Object) _jspx_page_context.findAttribute("item");
                              index = (java.lang.Integer) _jspx_page_context.findAttribute("index");
                              if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
                              break;
                            } while (true);
                            if (_jspx_eval_logic_005fiterate_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
                              out = _jspx_page_context.popBody();
                            }
                          }
                          if (_jspx_th_logic_005fiterate_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
                            return;
                          }
                          _005fjspx_005ftagPool_005flogic_005fiterate_0026_005fproperty_005fname_005findexId_005fid.reuse(_jspx_th_logic_005fiterate_005f0);
                          _jspx_th_logic_005fiterate_005f0_reused = true;
                        } finally {
                          org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_logic_005fiterate_005f0, _jsp_getInstanceManager(), _jspx_th_logic_005fiterate_005f0_reused);
                        }
                        out.write("\r\n");
                        out.write("						    	\r\n");
                        out.write("						  </tbody>\r\n");
                        out.write("						</table>\r\n");
                        out.write("					");
                        int evalDoAfterBody = _jspx_th_logic_005fnotEmpty_005f0.doAfterBody();
                        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
                          break;
                      } while (true);
                    }
                    if (_jspx_th_logic_005fnotEmpty_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
                      return;
                    }
                    _005fjspx_005ftagPool_005flogic_005fnotEmpty_0026_005fproperty_005fname.reuse(_jspx_th_logic_005fnotEmpty_005f0);
                    _jspx_th_logic_005fnotEmpty_005f0_reused = true;
                  } finally {
                    org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_logic_005fnotEmpty_005f0, _jsp_getInstanceManager(), _jspx_th_logic_005fnotEmpty_005f0_reused);
                  }
                  out.write("\r\n");
                  out.write("					");
                  int evalDoAfterBody = _jspx_th_logic_005fpresent_005f0.doAfterBody();
                  if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
                    break;
                } while (true);
              }
              if (_jspx_th_logic_005fpresent_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
                return;
              }
              _005fjspx_005ftagPool_005flogic_005fpresent_0026_005fproperty_005fname.reuse(_jspx_th_logic_005fpresent_005f0);
              _jspx_th_logic_005fpresent_005f0_reused = true;
            } finally {
              org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_logic_005fpresent_005f0, _jsp_getInstanceManager(), _jspx_th_logic_005fpresent_005f0_reused);
            }
            out.write("\r\n");
            out.write("					</div>\r\n");
            out.write("					<button class=\"btn-blue btn-sm\" onclick=\"add()\">รายงานปัญหา</button>\r\n");
            out.write("				</div>\r\n");
            out.write("				\r\n");
            out.write("			</div>\r\n");
            out.write("		</div>\r\n");
            out.write("	\r\n");
            out.write("	</section>\r\n");
            out.write("	\r\n");
            out.write("\r\n");
            out.write("	<script src=\"js/jquery.min.js\"></script>\r\n");
            out.write("  <script src=\"js/popper.js\"></script>\r\n");
            out.write("  <script src=\"js/bootstrap.min.js\"></script>\r\n");
            out.write("  <script src=\"js/main.js\"></script>\r\n");
            out.write("  \r\n");
            out.write("\r\n");
            out.write("	\r\n");
            out.write("	</html>\r\n");
            out.write("	");
            int evalDoAfterBody = _jspx_th_html_005fform_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_html_005fform_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return;
        }
        _005fjspx_005ftagPool_005fhtml_005fform_0026_005fstyleId_005faction.reuse(_jspx_th_html_005fform_005f0);
        _jspx_th_html_005fform_005f0_reused = true;
      } finally {
        org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_html_005fform_005f0, _jsp_getInstanceManager(), _jspx_th_html_005fform_005f0_reused);
      }
      out.write("\r\n");
      out.write("</section>\r\n");
      out.write("</body>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_html_005fhidden_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_html_005fform_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  html:hidden
    org.apache.struts.taglib.html.HiddenTag _jspx_th_html_005fhidden_005f0 = (org.apache.struts.taglib.html.HiddenTag) _005fjspx_005ftagPool_005fhtml_005fhidden_0026_005fproperty_005fnobody.get(org.apache.struts.taglib.html.HiddenTag.class);
    boolean _jspx_th_html_005fhidden_005f0_reused = false;
    try {
      _jspx_th_html_005fhidden_005f0.setPageContext(_jspx_page_context);
      _jspx_th_html_005fhidden_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_html_005fform_005f0);
      // /page/feature/request.jsp(78,1) name = property type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_html_005fhidden_005f0.setProperty("mode");
      int _jspx_eval_html_005fhidden_005f0 = _jspx_th_html_005fhidden_005f0.doStartTag();
      if (_jspx_th_html_005fhidden_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fhtml_005fhidden_0026_005fproperty_005fnobody.reuse(_jspx_th_html_005fhidden_005f0);
      _jspx_th_html_005fhidden_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_html_005fhidden_005f0, _jsp_getInstanceManager(), _jspx_th_html_005fhidden_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_logic_005fiterate_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_logic_005fiterate_005f0);
      // /page/feature/request.jsp(117,8) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${item.request_status.id eq '1' }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("									<td align=\"center\"><a href=\"#\" class=\"btn btn-warning\" data-toggle=\"modal\"  data-target=\"#exampleModal");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${item.id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write('"');
          out.write('>');
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${item.request_status.name }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</a></td>\r\n");
          out.write("								");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_logic_005fiterate_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f1_reused = false;
    try {
      _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_logic_005fiterate_005f0);
      // /page/feature/request.jsp(121,8) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${item.request_status.id eq '2' }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
      if (_jspx_eval_c_005fif_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("									<td align=\"center\"><a href=\"#\" class=\"btn btn-warning\" data-toggle=\"modal\" data-target=\"#exampleModal");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${item.id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write('"');
          out.write('>');
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${item.request_status.name }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</a></td>\r\n");
          out.write("								");
          int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
      _jspx_th_c_005fif_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f2(javax.servlet.jsp.tagext.JspTag _jspx_th_logic_005fiterate_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f2 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f2_reused = false;
    try {
      _jspx_th_c_005fif_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f2.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_logic_005fiterate_005f0);
      // /page/feature/request.jsp(125,8) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f2.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${item.request_status.id eq '3' }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f2 = _jspx_th_c_005fif_005f2.doStartTag();
      if (_jspx_eval_c_005fif_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("									<td align=\"center\"><a href=\"#\" class=\"btn btn-warning\" data-toggle=\"modal\" data-target=\"#exampleModal");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${item.id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write('"');
          out.write('>');
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${item.request_status.name }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</a></td>\r\n");
          out.write("								");
          int evalDoAfterBody = _jspx_th_c_005fif_005f2.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f2);
      _jspx_th_c_005fif_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f2, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f3(javax.servlet.jsp.tagext.JspTag _jspx_th_logic_005fiterate_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f3 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f3_reused = false;
    try {
      _jspx_th_c_005fif_005f3.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f3.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_logic_005fiterate_005f0);
      // /page/feature/request.jsp(129,8) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f3.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${item.request_status.id eq '4' }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f3 = _jspx_th_c_005fif_005f3.doStartTag();
      if (_jspx_eval_c_005fif_005f3 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("									<td align=\"center\"><a href=\"#\" class=\"btn btn-success\" data-toggle=\"modal\" data-target=\"#exampleModal");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${item.id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write('"');
          out.write('>');
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${item.request_status.name }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</a></td>\r\n");
          out.write("								");
          int evalDoAfterBody = _jspx_th_c_005fif_005f3.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f3);
      _jspx_th_c_005fif_005f3_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f3, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f3_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f4(javax.servlet.jsp.tagext.JspTag _jspx_th_logic_005fiterate_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f4 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f4_reused = false;
    try {
      _jspx_th_c_005fif_005f4.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f4.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_logic_005fiterate_005f0);
      // /page/feature/request.jsp(133,8) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f4.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${item.request_status.id eq '5' }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f4 = _jspx_th_c_005fif_005f4.doStartTag();
      if (_jspx_eval_c_005fif_005f4 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("									<td align=\"center\"><a href=\"#\" class=\"btn btn-danger\" data-toggle=\"modal\" data-target=\"#exampleModal");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${item.id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write('"');
          out.write('>');
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${item.request_status.name }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</a></td>\r\n");
          out.write("								");
          int evalDoAfterBody = _jspx_th_c_005fif_005f4.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f4.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f4);
      _jspx_th_c_005fif_005f4_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f4, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f4_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f5(javax.servlet.jsp.tagext.JspTag _jspx_th_logic_005fiterate_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f5 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f5_reused = false;
    try {
      _jspx_th_c_005fif_005f5.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f5.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_logic_005fiterate_005f0);
      // /page/feature/request.jsp(144,8) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f5.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${item.request_status.id eq '1' }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f5 = _jspx_th_c_005fif_005f5.doStartTag();
      if (_jspx_eval_c_005fif_005f5 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("									<td>\r\n");
          out.write("										<button type=\"button\" data-toggle=\"modal\" data-target=\"#editModal");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${item.id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\" class=\"btn btn-primary btn-xs\">edit</button>\r\n");
          out.write("										<button type=\"button\" onclick=\"del('");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${item.id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("')\" class=\"btn btn-danger btn-xs\">delete</button>\r\n");
          out.write("									</td>\r\n");
          out.write("								\r\n");
          out.write("								");
          int evalDoAfterBody = _jspx_th_c_005fif_005f5.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f5.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f5);
      _jspx_th_c_005fif_005f5_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f5, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f5_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f6(javax.servlet.jsp.tagext.JspTag _jspx_th_logic_005fiterate_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f6 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f6_reused = false;
    try {
      _jspx_th_c_005fif_005f6.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f6.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_logic_005fiterate_005f0);
      // /page/feature/request.jsp(151,8) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f6.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${item.request_status.id ne '1' }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f6 = _jspx_th_c_005fif_005f6.doStartTag();
      if (_jspx_eval_c_005fif_005f6 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("									<td>\r\n");
          out.write("										<button type=\"button\" onclick=\"\"  class=\"btn btn-primary btn-xs\" disabled>edit</button>\r\n");
          out.write("										<button type=\"button\" onclick=\"\"  class=\"btn btn-danger btn-xs\" disabled>delete</button>\r\n");
          out.write("									</td>\r\n");
          out.write("								");
          int evalDoAfterBody = _jspx_th_c_005fif_005f6.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f6.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f6);
      _jspx_th_c_005fif_005f6_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f6, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f6_reused);
    }
    return false;
  }

  private boolean _jspx_meth_html_005fselect_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_logic_005fiterate_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  html:select
    org.apache.struts.taglib.html.SelectTag _jspx_th_html_005fselect_005f0 = (org.apache.struts.taglib.html.SelectTag) _005fjspx_005ftagPool_005fhtml_005fselect_0026_005fstyleClass_005fproperty.get(org.apache.struts.taglib.html.SelectTag.class);
    boolean _jspx_th_html_005fselect_005f0_reused = false;
    try {
      _jspx_th_html_005fselect_005f0.setPageContext(_jspx_page_context);
      _jspx_th_html_005fselect_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_logic_005fiterate_005f0);
      // /page/feature/request.jsp(196,16) name = property type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_html_005fselect_005f0.setProperty("project");
      // /page/feature/request.jsp(196,16) name = styleClass type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_html_005fselect_005f0.setStyleClass("form-control");
      int _jspx_eval_html_005fselect_005f0 = _jspx_th_html_005fselect_005f0.doStartTag();
      if (_jspx_eval_html_005fselect_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        if (_jspx_eval_html_005fselect_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
          out = org.apache.jasper.runtime.JspRuntimeLibrary.startBufferedBody(_jspx_page_context, _jspx_th_html_005fselect_005f0);
        }
        do {
          out.write("	\r\n");
          out.write("																	");
          if (_jspx_meth_html_005foptionsCollection_005f0(_jspx_th_html_005fselect_005f0, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("																");
          int evalDoAfterBody = _jspx_th_html_005fselect_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
        if (_jspx_eval_html_005fselect_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
          out = _jspx_page_context.popBody();
        }
      }
      if (_jspx_th_html_005fselect_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fhtml_005fselect_0026_005fstyleClass_005fproperty.reuse(_jspx_th_html_005fselect_005f0);
      _jspx_th_html_005fselect_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_html_005fselect_005f0, _jsp_getInstanceManager(), _jspx_th_html_005fselect_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_html_005foptionsCollection_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_html_005fselect_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  html:optionsCollection
    org.apache.struts.taglib.html.OptionsCollectionTag _jspx_th_html_005foptionsCollection_005f0 = (org.apache.struts.taglib.html.OptionsCollectionTag) _005fjspx_005ftagPool_005fhtml_005foptionsCollection_0026_005fvalue_005fproperty_005flabel_005fnobody.get(org.apache.struts.taglib.html.OptionsCollectionTag.class);
    boolean _jspx_th_html_005foptionsCollection_005f0_reused = false;
    try {
      _jspx_th_html_005foptionsCollection_005f0.setPageContext(_jspx_page_context);
      _jspx_th_html_005foptionsCollection_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_html_005fselect_005f0);
      // /page/feature/request.jsp(197,17) name = property type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_html_005foptionsCollection_005f0.setProperty("projectList");
      // /page/feature/request.jsp(197,17) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_html_005foptionsCollection_005f0.setValue("id");
      // /page/feature/request.jsp(197,17) name = label type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_html_005foptionsCollection_005f0.setLabel("name");
      int _jspx_eval_html_005foptionsCollection_005f0 = _jspx_th_html_005foptionsCollection_005f0.doStartTag();
      if (_jspx_th_html_005foptionsCollection_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fhtml_005foptionsCollection_0026_005fvalue_005fproperty_005flabel_005fnobody.reuse(_jspx_th_html_005foptionsCollection_005f0);
      _jspx_th_html_005foptionsCollection_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_html_005foptionsCollection_005f0, _jsp_getInstanceManager(), _jspx_th_html_005foptionsCollection_005f0_reused);
    }
    return false;
  }
}
